### ISSUE TITLE
basic_examples/simple_image_classifier.py: TypeError: __init__() got an unexpected keyword argument 'run'

### ISSUE THREAD

**Issue by Jasha10** [PyTorchLightning/pytorch-lightning#10006]
## 🐛 Bug

When I run `pl_examples/basic_examples/simple_image_classifier.py` using the instructions from `pl_examples/basic_examples/README.md`, I am getting a TypeError:

```text
$ python simple_image_classifier.py
...
Traceback (most recent call last):
  File "/home/jasha10/pysc/pytorch-lightning/pl_examples/basic_examples/simple_image_classifier.py", line 82, in <module>
    cli_main()
  File "/home/jasha10/pysc/pytorch-lightning/pl_examples/basic_examples/simple_image_classifier.py", line 73, in cli_main
    cli = LightningCLI(
TypeError: __init__() got an unexpected keyword argument 'run'
```

### Environment

```text
$ python ~/Downloads/collect_env_details.py
* CUDA:
        - available:         True
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.1
        - pytorch-lightning: 1.4.9
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.7
        - version:           #98~18.04.1-Ubuntu SMP Wed Sep 22 10:45:04 UTC 2021
```

**Comment by Jasha10** [comment]
Oops sorry, it looks like the issue was that the installed version of the LightningCLI class came from a different git commit than the version of `simple_image_classifier.py` that I was trying to run.
