### ISSUE TITLE
DeepSpeed ZeRO 3 CPU offloading crashes with RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by petrgeiger-incieve** [PyTorchLightning/pytorch-lightning#10378]
## 🐛 Bug

DeepSpeed ZeRO 3 CPU offloading crashes with RuntimeError: Tensors must be CUDA and dense. I 
add `bug_report_model.py` below with simple modification in trainer `strategy=deepspeed_stage_3_offload`. I also tried ZeRO 2 and it works flawlessly.

### To Reproduce
code:
```
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.plugins import DeepSpeedPlugin


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        max_steps=100,
        enable_model_summary=False,
        gpus=1,
        precision=16,
        strategy="deepspeed_stage_3_offload",
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()
```
error:
```
 % python ./boring_model.py 
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
initializing deepspeed distributed: GLOBAL_RANK: 0, MEMBER: 1/1
/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py:625: UserWarning: Inferring the batch size for internal deepspeed logging from the `train_dataloader()`. If you require skipping this, please pass `Trainer(strategy=DeepSpeedPlugin(logging_batch_size_per_gpu=batch_size))`
  rank_zero_warn(
Enabling DeepSpeed FP16.
[2021-11-05 18:05:46,363] [WARNING] [partition_parameters.py:456:__init__] zero.Init: the `config` argument is deprecated. Please use `config_dict_or_path` instead.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
[2021-11-05 18:05:46,369] [WARNING] [partition_parameters.py:456:__init__] zero.Init: the `config` argument is deprecated. Please use `config_dict_or_path` instead.
You have not specified an optimizer or scheduler within the DeepSpeed config. Using `configure_optimizers` to define optimizer and scheduler.
[2021-11-05 18:05:46,372] [WARNING] [engine.py:902:_configure_optimizer] **** You are using ZeRO with an untested optimizer, proceed with caution *****
Initializing ZeRO Stage 3
Using /home/geigerp/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
Emitting ninja build file /home/geigerp/.cache/torch_extensions/py39_cu113/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.45387792587280273 seconds
Using /home/geigerp/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.00033211708068847656 seconds
/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:393: UserWarning: The number of training samples (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:  50%|███████████████████████████████████████████▌                                           | 1/2 [00:00<00:00,  1.32it/s, loss=-0.269, v_num=11Traceback (most recent call last):                                                                                                   | 0/1 [00:00<?, ?it/s]
  File "/home/geigerp/Documents/projects/Freds/./boring_model.py", line 70, in <module>
    run()
  File "/home/geigerp/Documents/projects/Freds/./boring_model.py", line 65, in run
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
    return self._run_train()
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1312, in _run_train
    self.fit_loop.run()
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 146, in run
    self.on_advance_end()
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 246, in on_advance_end
    self._run_validation()
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 341, in _run_validation
    self.val_loop.run()
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 123, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 215, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 891, in validation_step
    return self.model(*args, **kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1347, in forward
    loss = self.module(*inputs, **kwargs)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1109, in _call_impl
    result = hook(self, input)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 1452, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 1569, in pre_sub_module_forward_function
    self.param_coordinator.prefetch_next_sub_modules(
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 361, in prefetch_next_sub_modules
    self._all_gather(params_to_prefetch, async_op=True)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 524, in _all_gather
    handles = partitioned_params[0].all_gather(
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 590, in all_gather
    return self._all_gather(param_list, async_op=async_op, hierarchy=hierarchy)
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 689, in _all_gather
    handle = self._allgather_param(param,
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 891, in _allgather_param
    handle = dist._all_gather_base(flat_tensor,
  File "/opt/miniconda3/envs/default/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2070, in _all_gather_base
    work = group._allgather_base(output_tensor, input_tensor)
RuntimeError: Tensors must be CUDA and dense
```

### Expected behavior

Flawless training.

### Environment

```
* CUDA:
        - GPU:
                - NVIDIA Tesla V100-SXM2-16GB
                - NVIDIA Tesla V100-SXM2-16GB
                - NVIDIA Tesla V100-SXM2-16GB
                - NVIDIA Tesla V100-SXM2-16GB
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0
        - pytorch-lightning: 1.5.0
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.7
        - version:           #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021
        - CUDA/cuDNN version: 11.3
        - How you installed PyTorch (`conda`, `pip`, source): conda
```

### Additional context
none

**Comment by SeanNaren** [comment]
Seems something has changed in the latest release (deepspeed 0.5.5). Could you try installing a previous version (`pip install deepspeed==0.5.4`) and seeing if this works?

I'll figure out what has changed in the latest release to cause this issue.

**Comment by SeanNaren** [comment]
I've pinged the deepspeed authors to get some hints as to what could've caused this regression between versions (cc @tjruwase)

**Comment by tjruwase** [comment]
@SeanNaren, thanks for the heads up. Let's sync on your repro on this?

**Comment by SeanNaren** [comment]
hey @tjruwase thanks for checking this out :)

@petrgeiger-incieve reprod works to reproduce the error with the latest lightning + latest deepspeed.

Has anything changed you know between 0.5.4 and 0.5.5 that could cause parameters to not be moved to device correctly when offloading + fp16 is enabled?

**Comment by tjruwase** [comment]
@SeanNaren, I have submitted a DS PR [1548](https://github.com/microsoft/DeepSpeed/pull/1548) for this issue.

**Comment by SeanNaren** [comment]
Amazing! thanks @tjruwase, once a release is made I'll close this issue

**Comment by SeanNaren** [comment]
I just saw a new release was made, `pip install deepspeed -U` should fix this issue :)
