### ISSUE TITLE
Exception in device=TPU:0

### ISSUE THREAD

**Issue by varDiii** [PyTorchLightning/pytorch-lightning#1047]
This error occours when initiate the trainer

```
Exception in device=TPU:0: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 500, in tpu_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1162, in run_pretrain_routine
    torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
AttributeError: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
```

**Comment by williamFalcon** [comment]
ummm.

updated to latest version and try again?

**Comment by nikanton** [comment]
Faced with the same problem. 
> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 507, in tpu_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 792, in run_pretrain_routine
    torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
AttributeError: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'

**Comment by williamFalcon** [comment]
need to use latest xla version

**Comment by nikanton** [comment]
helped
