### ISSUE TITLE
AttributeError: Can't get attribute 'JigsawModel' on <module '__main__' (built-in)>

### ISSUE THREAD

**Issue by ishandutta0098** [PyTorchLightning/pytorch-lightning#10511]
## 🐛 Bug

I am training a `roberta-base` model for a regression task in PyTorch Lightning. It works when I use it for 1 GPU but if I use it for more than one GPU I get an error.

## Error
```
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.dense.weight', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'JigsawModel' on <module '__main__' (built-in)>
NOTE! Installing ujson may make loading annotations faster.
```

## To Reproduce

The entire code has been put into Google Colab and can be accessed using [this link](https://colab.research.google.com/drive/1xr0Ib5ekXCkESSjd_wAKnKkLfHzaH2Fg?usp=sharing)

The dataset used for the code is available [here](https://www.kaggle.com/c/jigsaw-toxic-severity-rating/data)

## Relevant Code

Here is the relevant part of code for a quick glimpse:

### Model

```
class JigsawModel(pl.LightningModule):
    
    def __init__(self, model_name):
        super(JigsawModel, self).__init__()
        self.model = AutoModel.from_pretrained(model_name)
        self.drop = nn.Dropout(p=0.2)
        self.fc = nn.Linear(768, CONFIG['num_classes'])
        
    def forward(self, ids, mask):        
        out = self.model(input_ids=ids,attention_mask=mask,
                         output_hidden_states=False)
        out = self.drop(out[1])
        outputs = self.fc(out)
                    
        return outputs
    
    def training_step(self, batch, batch_idx):
        more_toxic_ids = batch['more_toxic_ids']
        more_toxic_mask = batch['more_toxic_mask']
        less_toxic_ids = batch['less_toxic_ids']
        less_toxic_mask = batch['less_toxic_mask']
        targets = batch['target']
        
        more_toxic_outputs = self(more_toxic_ids, more_toxic_mask)
        less_toxic_outputs = self(less_toxic_ids, less_toxic_mask)
        
        loss = self.criterion(more_toxic_outputs, less_toxic_outputs, targets)
        
        self.log("train_loss", loss, prog_bar=True, logger=True)
        
        return {"loss": loss}
    
    def validation_step(self, batch, batch_idx):
        more_toxic_ids = batch['more_toxic_ids']
        more_toxic_mask = batch['more_toxic_mask']
        less_toxic_ids = batch['less_toxic_ids']
        less_toxic_mask = batch['less_toxic_mask']
        targets = batch['target']
        
        more_toxic_outputs = self(more_toxic_ids, more_toxic_mask)
        less_toxic_outputs = self(less_toxic_ids, less_toxic_mask)
        
        loss = self.criterion(more_toxic_outputs, less_toxic_outputs, targets)
        
        self.log("val_loss", loss, prog_bar=True, logger=True)
        
        return {'val_loss': loss}      
        
    def configure_optimizers(self):
        
        optimizer = AdamW(self.parameters(), lr=CONFIG['learning_rate'], weight_decay=CONFIG['weight_decay'])
        scheduler = fetch_scheduler(optimizer)
        
        return dict(
            optimizer = optimizer,
            lr_scheduler = scheduler
        )
    
    def criterion(self, outputs1, outputs2, targets):
        return nn.MarginRankingLoss(margin=CONFIG['margin'])(outputs1, outputs2, targets)
```

```
logger = TensorBoardLogger("lightning_logs", name="toxic-comments")

checkpoint_callback = ModelCheckpoint(
  dirpath="jigsaw-comment-severity/checkpoints",
  filename="best-checkpoint",
  save_top_k=1,
  verbose=True,
  monitor="val_loss",
  mode="min"
)

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=2)

trainer = pl.Trainer(
  logger=logger,
  checkpoint_callback=checkpoint_callback,
  callbacks=[early_stopping_callback],
  max_epochs=CONFIG['epochs'],
  gpus=-1,
  progress_bar_refresh_rate=30,
  precision=16,
)
```

```
if __name__ == "__main__":    
    for fold in range(0, CONFIG['n_fold']):
        print(f"{y_}====== Fold: {fold} ======{sr_}")

        df_train = df[df.kfold != fold].reset_index(drop=True)
        df_valid = df[df.kfold == fold].reset_index(drop=True)  

        data_module = JigsawDataModule(df_train, df_valid)

        model = JigsawModel(CONFIG['model_name'])    
        trainer.fit(model, data_module)
```

At this point the error occurs. Kindly suggest a fix to the issue.

**Comment by rohitgr7** [comment]
here:
```py
trainer = pl.Trainer(
  logger=logger,
  checkpoint_callback=checkpoint_callback,
  callbacks=[early_stopping_callback],
  max_epochs=CONFIG['epochs'],
  gpus=-1,
  progress_bar_refresh_rate=30,
  precision=16,
)
```
with gpus = -1, it will select `ddp_` (`ddp_spawn` specifically) strategy to run the job. 
But I guess you are running in jupyter. Unfortunately, `ddp_` doesn't work in a notebook env.
https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#jupyter-notebooks
https://discuss.pytorch.org/t/distributeddataparallel-on-terminal-vs-jupyter-notebook/101404

**Comment by tchaton** [comment]
Dear @ishandutta0098,

Mind putting your model within a script and importing this model directly within our notebook. Pickle has sometimes trouble to pickle objects in __main__ script.

Best,
T.C

**Comment by gokul427** [comment]
please tell the resolution to solve this issue.

**Comment by rohitgr7** [comment]
ddp within notebooks is not supported @gokul427 

all you need to do is
```py
trainer = Trainer(..., strategy='ddp')
```
I'd suggest using the latest version.
