### ISSUE TITLE
Tuner fails with DDP in 1.5

### ISSUE THREAD

**Issue by RuRo** [PyTorchLightning/pytorch-lightning#10560]
## 🐛 Bug

Attempting to tune a model with `accelerator/strategy = "ddp"` leads to `TypeError: forward() takes 2 positional arguments but 3 were given` in pytorch-lightning 1.5+. It appears that the Tuner tries to pass the batch directly to `Model.forward` instead of to `training_step`.

### To Reproduce

```python
import pytorch_lightning
import torch


class RandomDatasetWithGT(torch.utils.data.Dataset):
    def __init__(self, length):
        self.len = length
        self.data = torch.randn(length, 32)
        self.gt = torch.randn(length, 2)

    def __getitem__(self, index):
        return self.data[index], self.gt[index]

    def __len__(self):
        return self.len


class BoringTunableModel(pytorch_lightning.LightningModule):
    def __init__(self, lr=0.01):
        super().__init__()
        self.save_hyperparameters()
        self.fc = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.fc(x)

    def training_step(self, batch, batch_idx):
        x, y = batch
        p = self(x)
        return torch.nn.functional.mse_loss(p, y)
        
    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=self.hparams.lr)

    def train_dataloader(self):
        return torch.utils.data.DataLoader(RandomDatasetWithGT(1024))


def main():
    model = BoringTunableModel()
    trainer = pytorch_lightning.Trainer(
        accelerator="ddp",
        gpus=-1,
        auto_lr_find=True,
    )
    trainer.tune(model)


if __name__ == "__main__":
    main()
```

The above script runs fine with `pytorch-lightning==1.4.9`.

### Full Traceback

```
Traceback (most recent call last):
  File "/tmp/tmp.OLCIKONagC/test.py", line 51, in <module>
    main()
  File "/tmp/tmp.OLCIKONagC/test.py", line 47, in main
    trainer.tune(model)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1092, in tune
    result = self.tuner._tune(model, scale_batch_size_kwargs=scale_batch_size_kwargs, lr_find_kwargs=lr_find_kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/tuner/tuning.py", line 53, in _tune
    result["lr_find"] = lr_find(self.trainer, model, **lr_find_kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/tuner/lr_finder.py", line 238, in lr_find
    trainer.tuner._run(model)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/tuner/tuning.py", line 63, in _run
    self.trainer._run(*args, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
    return self._run_train()
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1312, in _run_train
    self.fit_loop.run()
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 195, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1662, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 163, in optimizer_step
    optimizer.step(closure=closure, **kwargs)
  File "/usr/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/torch/optim/sgd.py", line 87, in step
    loss = closure()
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 148, in _wrap_closure
    closure_result = closure()
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    step_output = self._step_fn()
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 435, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 216, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/ruro/.local/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 439, in training_step
    return self.model(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```

### Environment

```
* CUDA:
	- GPU:
		- NVIDIA GeForce GTX 1050
	- available:         True
	- version:           11.4
* Packages:
	- numpy:             1.21.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.1
	- pytorch-lightning: 1.5.1
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         
	- python:            3.9.7
	- version:           #1 SMP PREEMPT Thu Sep 30 15:29:01 UTC 2021
```

cc @borda @rohitgr7 @akihironitta

**Comment by akihironitta** [comment]
Not sure if this is related to the error message, but I believe `trainer.tune(...)` has no support for DDP at this moment.

> For the moment, this feature only works with models having a single optimizer. LR Finder support for DDP and any of its variations is not implemented yet. It is coming soon.
> https://pytorch-lightning.readthedocs.io/en/latest/advanced/lr_finder.html?highlight=lr%20finder

> Batch size finder is not yet supported for DDP or any of its variations, it is coming soon.
> https://pytorch-lightning.readthedocs.io/en/latest/advanced/training_tricks.html?highlight=tuner#auto-scaling-of-batch-size

**Comment by RuRo** [comment]
@akihironitta that's strange, because I could swear that it used to mostly work before 1.5.

Is there an issue/PR where DDP support for Tuning is tracked?

**Comment by akihironitta** [comment]
> Edit: Also, perhaps if Tuning with DDP is not supported, then the trainer shouldn't let you call .tune in that case or at least warn you?

@RuRo Thanks for your feedback. I agree that it should raise an exception when used with DDP (or at least warn users).

**Comment by akihironitta** [comment]
> @akihironitta that's strange, because I could swear that it used to mostly work before 1.5.
> Is there an issue/PR where DDP support for Tuning is tracked?

@RuRo After looking back in the git log, it should probably be supported with DDP. The warnings in the docs were added two years ago without much information in #1835, so it might be that the docs are just outdated.

@SkafteNicki @rohitgr7 Does Lightning cover the support of `Tuner` with DDP?

**Comment by akihironitta** [comment]
Hi @RuRo, it seems like there's no reason why tuner is not supported with DDP, so we'll update the docs and fix any bugs related to tuner used with DDP as well.

**Comment by RuRo** [comment]
@akihironitta That's great news, thanks! )))

**Comment by bryant1410** [comment]
When I run tune with DDP it seems like each process is tuning independently, is that right? Each one is logging to the console different values found.

**Comment by carmocca** [comment]
@akihironitta What made you drop #10754?

Let's add this at least:

> I agree that it should raise an exception when used with DDP (or at least warn users)

**Comment by carmocca** [comment]
Then, let's pull that to a separate PR so we can close this :)

**Comment by mfoglio** [comment]
Since learning rate finder can't be used with ddp, what strategy do you suggest to use?
