### ISSUE TITLE
'dict_keyiterator' object has no attribute 'keys' when using a dictionary with multiple dataloaders in val_dataloader.

### ISSUE THREAD

**Issue by ashutoshml** [PyTorchLightning/pytorch-lightning#10809]
## 🐛 Bug

`trainer.fit` returns `AttributeError: 'dict_keyiterator' object has no attribute 'keys'` when using a dictionary with multiple data loaders in `val_dataloader`.
This behavior does not happen when there is a single dataloader in `val_dataloader`

 A similar behavior is observed with test and predict dataloaders. A possible fix is to encapsulate the return value of `val_dataloader` using `CombinedLoader`. This behavior can be made default internally too.

### To Reproduce

Please check colab link : https://colab.research.google.com/drive/1DNoEtOZR90zhkpk6aT_lz4gHehJ8A_96?usp=sharing

### Expected behavior

Training should continue as normal. 

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0+cu111
	- pytorch-lightning: 1.5.3
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

cc @justusschock @awaelchli @ninginthecloud

**Comment by rohitgr7** [comment]
in short instead of expecting a user to do this:
```
from pytorch_lightning.trainer.suppporters import CombinedLoader

def val_dataloader(self):
    return CombinedLoader({'a': loader1, 'b': loader2})
```

we can internally check and wrap CombinedDataloader around the dict

**Comment by justusschock** [comment]
For validation, only sequential loaders are supported. This is the case, since the way batches are fetched differs from train loaders.

For train loaders each batch will consist of a subbatch from each loader. For validation however, we first exhaust the first loader, then move on to the second one etc. But at every point you will only have a batch from the currently active loader.
With other approaches it would be impossible to provide arguments like `dataloader_idx` for the steps.

**Comment by rohitgr7** [comment]
@justusschock I think both are supported. https://github.com/PyTorchLightning/pytorch-lightning/blame/master/docs/source/guides/data.rst#L229-L234

It's just that we ask users to explicitly import and use CombinedLoader instead of wrapping it around if a dict is returned from val/test/pred dataloader.

**Comment by justusschock** [comment]
whoops, missed that, sorry. But then I think we should keep it that way. Because for sequentials it will be actually be tricky to determine which mode to use.

**Comment by rohitgr7** [comment]
for sequentials we can keep it as it is.. only for dicts we can wrap it around.

**Comment by justusschock** [comment]
I think that would be inconsequent from the API point of view. Either wrap it automatically all the time or never. If we're special casing a part here, that will probably lead to even more confusion

**Comment by rohitgr7** [comment]
wrapping the dictionary around `CombinedLoader` should work fine.

**Comment by andreimargeloiu** [comment]
Raising a warning would be great. I had the same issue, searched on google, and found this thread.

The [documentation](https://pytorch-lightning.readthedocs.io/en/stable/guides/data.html#concatenated-dataset) is inconsistent.

![CleanShot 2022-02-01 at 12 55 38](https://user-images.githubusercontent.com/18227298/151972255-0e410a10-bd4a-4181-aa51-d65d7956fb35.png)

**Comment by andreimargeloiu** [comment]
However, it would be useful to allow using different loaders separately. Forcing to use `CombinedLoader` is bad because often we don't need to revisit previously visited samples.

For example, I'm trying to have multiple different validation dataloaders, and using `CombinedLoader`is not applicable.

![CleanShot 2022-02-01 at 13 01 00](https://user-images.githubusercontent.com/18227298/151973133-7428a8ce-eadb-4bb0-8cfb-b3dff64225d7.png)

**Comment by rohitgr7** [comment]
hey @andreimargeloiu 

for val dataloaders, there are two possible cases:
1. Combined all dataloaders and generate a common batch that contains batches from all the dataloaders, one at a time.
2. Keep all the dataloaders separate and run each dataloader independently.

both of these are available in Lightning. Are you looking for something else?

**Comment by andreimargeloiu** [comment]
@rohitgr7 I would like using separate validation dataloaders as I have in the code below
![CleanShot 2022-02-01 at 13 33 31](https://user-images.githubusercontent.com/18227298/151977793-af2268d1-6d17-4d71-a366-82da5d9ee3b9.png)


However, this creates the following error:
```
Traceback (most recent call last):
  File "src/run_experiment_diet_network.py", line 503, in <module>
    train(args)
  File "src/run_experiment_diet_network.py", line 213, in train
    trainer.fit(model, data_module)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 86, in on_run_start
    self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_progress.current.ready)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/loops/utilities.py", line 121, in _update_dataloader_iter
    dataloader_iter = enumerate(data_fetcher, batch_idx)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 198, in __iter__
    self._apply_patch()
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 133, in _apply_patch
    apply_to_collections(self.loaders, self.loader_iters, (Iterator, DataLoader), _apply_patch_fn)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py", line 211, in apply_to_collections
    for v1, v2 in zip(data1, data2)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py", line 211, in <listcomp>
    for v1, v2 in zip(data1, data2)
  File "/home/am2770/miniconda3/envs/low-data/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py", line 197, in apply_to_collections
    zipped = {k: (data1[k], data2[k]) for k in data1.keys() | data2.keys()}
AttributeError: 'dict_keyiterator' object has no attribute 'keys'
```

Do you have any advice?

**Comment by rohitgr7** [comment]
you can't return a dictionary for val_dataloaders, if you want to combine them, then you have to use `CombinedLoader` wrapper, and if you want to use them separately, you have to send a list instead of a dictionary.

check out the docs here: https://pytorch-lightning.readthedocs.io/en/latest/guides/data.html#multiple-validation-test-predict-dataloaders

**Comment by nmerty** [comment]
This is still a problem when one is returning a dictionary of dataloaders in `train_dataloader()`, enables `overfit_batches` and has a defined `validation_step`. Then the train dataloaders are used for validation and the same _"'dict_keyiterator' object has no attribute 'keys'"_ error is thrown.

**Comment by rohitgr7** [comment]
yeah... I faces this issue before. have been updated on the master. Now whenever you set overfit_batches, it will disable validation. Next release in 2-3 weeks, or you can install from source.

**Comment by mirko-m** [comment]
@rohitgr7 @justusschock  When I return a list for the val_dataloaders I get the a `TypeError: object of type 'list_iterator' has no len()` (see below for the full traceback). Do you know how to fix this?

```
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1150/2747640908.py in <cell line: 1>()
----> 1 main(net, 2)

/tmp/ipykernel_1150/2585219909.py in main(net, workers_count)
     48     )
     49 
---> 50     trainer.fit(
     51       net,
     52       datamodule

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    694         """
    695         self.strategy.model = model
--> 696         self._call_and_handle_interrupt(
    697             self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    698         )

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    648                 return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
    649             else:
--> 650                 return trainer_fn(*args, **kwargs)
    651         # TODO(awaelchli): Unify both exceptions below, where `KeyboardError` doesn't re-raise
    652         except KeyboardInterrupt as exception:

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    733             ckpt_path, model_provided=True, model_connected=self.lightning_module is not None
    734         )
--> 735         results = self._run(model, ckpt_path=self.ckpt_path)
    736 
    737         assert self.state.stopped

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1164         self._checkpoint_connector.resume_end()
   1165 
-> 1166         results = self._run_stage()
   1167 
   1168         log.detail(f"{self.__class__.__name__}: trainer tearing down")

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _run_stage(self)
   1250         if self.predicting:
   1251             return self._run_predict()
-> 1252         return self._run_train()
   1253 
   1254     def _pre_training_routine(self):

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _run_train(self)
   1281 
   1282         with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1283             self.fit_loop.run()
   1284 
   1285     def _run_evaluate(self) -> _EVALUATE_OUTPUT:

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py in run(self, *args, **kwargs)
    198             try:
    199                 self.on_advance_start(*args, **kwargs)
--> 200                 self.advance(*args, **kwargs)
    201                 self.on_advance_end()
    202                 self._restarting = False

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py in advance(self)
    269         )
    270         with self.trainer.profiler.profile("run_training_epoch"):
--> 271             self._outputs = self.epoch_loop.run(self._data_fetcher)
    272 
    273     def on_advance_end(self) -> None:

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py in run(self, *args, **kwargs)
    199                 self.on_advance_start(*args, **kwargs)
    200                 self.advance(*args, **kwargs)
--> 201                 self.on_advance_end()
    202                 self._restarting = False
    203             except StopIteration:

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py in on_advance_end(self)
    239         if should_check_val:
    240             self.trainer.validating = True
--> 241             self._run_validation()
    242             self.trainer.training = True
    243 

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py in _run_validation(self)
    297 
    298         with torch.no_grad():
--> 299             self.val_loop.run()
    300 
    301     def _accumulated_batches_reached(self) -> bool:

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py in run(self, *args, **kwargs)
    198             try:
    199                 self.on_advance_start(*args, **kwargs)
--> 200                 self.advance(*args, **kwargs)
    201                 self.on_advance_end()
    202                 self._restarting = False

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py in advance(self, *args, **kwargs)
    153         if self.num_dataloaders > 1:
    154             kwargs["dataloader_idx"] = dataloader_idx
--> 155         dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
    156 
    157         # store batch level output per dataloader

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py in run(self, *args, **kwargs)
    193         self.reset()
    194 
--> 195         self.on_run_start(*args, **kwargs)
    196 
    197         while not self.done:

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py in on_run_start(self, data_fetcher, dl_max_batches, kwargs)
     86         self._reload_dataloader_state_dict(data_fetcher)
     87         # creates the iterator inside the fetcher but returns `self`
---> 88         self._data_fetcher = iter(data_fetcher)
     89         # add the previous `fetched` value to properly track `is_last_batch` with no prefetching
     90         data_fetcher.fetched += self.batch_progress.current.ready

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py in __iter__(self)
    177         self.reset()
    178         self.dataloader_iter = iter(self.dataloader)
--> 179         self._apply_patch()
    180         self.prefetching()
    181         return self

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py in _apply_patch(self)
    118                 patch_dataloader_iterator(loader, iterator, self)
    119 
--> 120         apply_to_collections(self.loaders, self.loader_iters, (Iterator, DataLoader), _apply_patch_fn)
    121 
    122     def _store_dataloader_iter_state(

~/python_venvs/cim_env/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py in apply_to_collections(data1, data2, dtype, function, wrong_dtype, *args, **kwargs)
    217     is_sequence = isinstance(data1, Sequence) and not isinstance(data1, str)
    218     if (is_namedtuple or is_sequence) and data2 is not None:
--> 219         assert len(data1) == len(data2), "Sequence collections have different sizes."
    220         out = [
    221             apply_to_collections(v1, v2, dtype, function, *args, wrong_dtype=wrong_dtype, **kwargs)

TypeError: object of type 'list_iterator' has no len()
```
