### ISSUE TITLE
ModelCheckpoint Saving top_k > 1 causes GPU + CPU error

### ISSUE THREAD

**Issue by angadkalra** [PyTorchLightning/pytorch-lightning#10926]
## 🐛 Bug

I updated pytorch-lightning to 1.5.4 and started saving top 5 models in ModelCheckpoint callback instead of top 1. I'm training ResNet101 3D for about 200 epochs on GCP VM using 4 V100 GPUs. Code is very simple and standard, nothing fancy, basically followed pytorch-lightning docs exactly to get fastest model training. I use gin-config to directly inject args. 
Randomly started seeing error below, it sometimes doesn't happen and sometimes does, so definitely can't reproduce. I can share my code if needed. Any help is appreciated! Workaround right now is training in parts by taking last.ckpt and continuing training, but annoying. 

```
Epoch 76: 100%|█████████████████████████| 157/157 [03:06<00:00,  1.19s/it, loss=0.168, v_num=96f9Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 136, in main
    ckpt_path=gin.query_parameter('Trainer.fit.ckpt_path')
  File "/imvaria/model-training/src/scripts/training/train.py", line 136, in main
    ckpt_path=gin.query_parameter('Trainer.fit.ckpt_path')
  File "/imvaria/model-training/src/scripts/training/train.py", line 136, in main
    ckpt_path=gin.query_parameter('Trainer.fit.ckpt_path')
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/imvaria/model-training/src/scripts/training/train.py", line 136, in main
    ckpt_path=gin.query_parameter('Trainer.fit.ckpt_path')
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 298, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 298, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 298, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1490, in call_hook
    callback_fx(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1490, in call_hook
    callback_fx(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1490, in call_hook
    callback_fx(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 321, in on_train_epoch_end
    self.save_checkpoint(trainer)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 321, in on_train_epoch_end
    self.save_checkpoint(trainer)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 321, in on_train_epoch_end
    self.save_checkpoint(trainer)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 388, in save_checkpoint
    self._save_top_k_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 388, in save_checkpoint
    self._save_top_k_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 388, in save_checkpoint
    self._save_top_k_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 675, in _save_top_k_checkpoint
    if self.check_monitor_top_k(trainer, current):
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 675, in _save_top_k_checkpoint
    if self.check_monitor_top_k(trainer, current):
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 675, in _save_top_k_checkpoint
    if self.check_monitor_top_k(trainer, current):
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 505, in check_monitor_top_k
    should_update_best_and_save = monitor_op(current, self.best_k_models[self.kth_best_model_path])
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 505, in check_monitor_top_k
    should_update_best_and_save = monitor_op(current, self.best_k_models[self.kth_best_model_path])
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 505, in check_monitor_top_k
    should_update_best_and_save = monitor_op(current, self.best_k_models[self.kth_best_model_path])
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cpu!
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 298, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")

Trainer caught error:
Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!
Stopping...
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1490, in call_hook
    callback_fx(*args, **kwargs)


Trainer caught error:
Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cpu!
Stopping...
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)

Trainer caught error:
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Stopping...

  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 321, in on_train_epoch_end
    self.save_checkpoint(trainer)

  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 388, in save_checkpoint
    self._save_top_k_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 675, in _save_top_k_checkpoint
    if self.check_monitor_top_k(trainer, current):
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 505, in check_monitor_top_k
    should_update_best_and_save = monitor_op(current, self.best_k_models[self.kth_best_model_path])
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!

Trainer caught error:
Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!
Stopping...


Training done!

Training done!

Training done!
Epoch 76: 100%|█████████████████████████| 157/157 [03:13<00:00,  1.23s/it, loss=0.168, v_num=96f9]
Training done!
```

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.4
- PyTorch Version (e.g., 1.10): 1.9.0+cu111
- Python version (e.g., 3.9): 3.7.10
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.1
- GPU models and configuration: V100 (4 GPUs) on GCP VM
- How you installed PyTorch (`conda`, `pip`, source): pip
- Any other relevant information:

### Additional context

Trainer setup:
```
# Setup Trainer
  trainer = Trainer(
      default_root_dir=results_dir,
      callbacks=callbacks,
      accelerator='gpu',
      strategy=DDPPlugin(find_unused_parameters=False),
      gpus=num_gpus,
      max_epochs=gin.query_parameter('Trainer.max_epochs'),
      num_sanity_val_steps=False,
      limit_val_batches=0 if is_calibrating else 1.0,
      logger=mlf_logger,
      gradient_clip_val=gin.query_parameter('Trainer.gradient_clip_val'),
      precision=16,
      profiler=False,
  )
```
ModelCheckpoint Callback setup:
```
results_dir = os.path.join(args.save_dir, mlflow_exp_name, f'{mlf_logger.run_id}')
  monitor_metric = gin.query_parameter('ModelCheckpoint.monitor')
  filename = '{epoch}_{' + f'{monitor_metric}' + ':.4f}'
  ckpt_callback = ModelCheckpoint(
      filename=filename,
      dirpath=results_dir,
      save_top_k=3,
      save_last=True,
      monitor=f'{monitor_metric}',
      mode=gin.query_parameter('ModelCheckpoint.mode'),
      verbose=True,
  )
```

cc @carmocca @awaelchli @ninginthecloud @jjenniferdai

**Comment by awaelchli** [comment]
Do you by any chance happen to see a warning similar like this one?

```
{current} is supposed to be a `torch.Tensor`. Saving checkpoint may not work correctly."
f" HINT: check the value of {self.monitor} in your validation loop
```

I'm asking because we have this code in our ModelCheckpoint: 

https://github.com/PyTorchLightning/pytorch-lightning/blob/a28b4cd0c0bba30c21cae571e650877f66cf5588/pytorch_lightning/callbacks/model_checkpoint.py#L482-L488

The line there  `current = torch.tensor(current)` could be problematic. If current is not a tensor, then t`orch.tensor(current)` will be on CPU. 

Does your x in `self.log(x)` sporadically become a non-tensor?

**Comment by carmocca** [comment]
> Does your x in self.log(x) sporadically become a non-tensor?

`self.log()` automatically converts to tensor:

https://github.com/PyTorchLightning/pytorch-lightning/blob/a28b4cd0c0bba30c21cae571e650877f66cf5588/pytorch_lightning/core/lightning.py#L374

I think the conversion in `ModelCheckpoint` isn't necessary.

**Comment by carmocca** [comment]
@angadkalra It will be hard to help if you cannot reproduce it.

Can you at least verify which of `current, self.best_k_models[self.kth_best_model_path]` is in CPU?

**Comment by angadkalra** [comment]
> Do you by any chance happen to see a warning similar like this one?
> 
> ```
> {current} is supposed to be a `torch.Tensor`. Saving checkpoint may not work correctly."
> f" HINT: check the value of {self.monitor} in your validation loop
> ```
> 
> I'm asking because we have this code in our ModelCheckpoint:
> 
> https://github.com/PyTorchLightning/pytorch-lightning/blob/a28b4cd0c0bba30c21cae571e650877f66cf5588/pytorch_lightning/callbacks/model_checkpoint.py#L482-L488
> 
> The line there `current = torch.tensor(current)` could be problematic. If current is not a tensor, then t`orch.tensor(current)` will be on CPU.
> 
> Does your x in `self.log(x)` sporadically become a non-tensor?

No I made sure all metrics that I log are tensors. The metric that ModelCheckpoint is monitoring is a custom metric I created using torchmetrics template, see below: 

```
"""Custom Model Metrics."""
import numpy as np
import torch
from torchmetrics import Metric
from torchmetrics.functional import recall, specificity


class SensAt90Spec(Metric):
    """Calculate Sensitivity when Specificity approx.

    equals 90.
    """
    def __init__(self, compute_on_step: bool = False) -> None:
        """Initialize Metric."""
        super().__init__(compute_on_step=compute_on_step)
        self.add_state('preds', default=[], dist_reduce_fx='cat')
        self.add_state('targets', default=[], dist_reduce_fx='cat')

    def update(self, batch_preds: torch.Tensor, batch_targets: torch.Tensor):
        """Update Epoch Preds and Targets."""
        self.preds.append(batch_preds)
        self.targets.append(batch_targets)
        return

    def _calculate_sens_at_90_spec(self, preds, targets):
        spec_90_thresh: float = 0.0
        spec: torch.Tensor = torch.tensor(0.0)
        for thresh in np.arange(0.50, 1.00, 0.01):
            spec = specificity(preds[:, 1], targets, threshold=thresh)
            if spec >= 0.90:
                spec_90_thresh = thresh
                break

        if spec_90_thresh:
            sens = recall(preds[:, 1], targets, threshold=spec_90_thresh)
        else:
            sens = torch.tensor(0.0)
            spec = torch.tensor(0.0)

        return sens, spec, spec_90_thresh

    def compute(self):
        """Compute Metric."""
        sens, _, _ = self._calculate_sens_at_90_spec(self.preds, self.targets)
        return torch.tensor(sens)


class ThreshAt90Spec(SensAt90Spec):
    """Calculate Threshold at 90 Specificity."""
    def compute(self):
        """Compute Metric."""
        _, _, thresh = self._calculate_sens_at_90_spec(self.preds, self.targets)
        return torch.tensor(thresh)


class Spec90(SensAt90Spec):
    """Calculate Specificity."""
    def compute(self):
        """Compute Metric."""
        _, spec, _ = self._calculate_sens_at_90_spec(self.preds, self.targets)
        return torch.tensor(spec)

```

And at the end of train and val I call this function:

```
def _calculate_epoch_metrics(self, outputs, phase):
        """Calculate metrics at end of epoch.

        This custom method calculates training and validation epoch-end
        metrics such as AUC. It uses the preds/targets stored in each
        model head to compute the metrics. Refer to PL Metric class docs
        for more details.

        Args:
            - outputs (list): List containing batch dicts returned from
                _get_loss_preds for each step in training/validation.
            - phase (str): String is either "train" or "valid".

        Returns:
            n/a
        """
        epoch_loss = torch.tensor([step['loss'] for step in outputs]).mean()
        self.log(f'{phase}_loss', epoch_loss)

        for head in self.model.model_heads:
            # Use Metrics API
            if phase == 'train':
                for metric_name, metric in head.train_metrics.items():
                    self.log(f'{head.name}_{metric_name}', metric)
            elif phase == 'valid':
                for metric_name, metric in head.valid_metrics.items():
                    self.log(f'{head.name}_{metric_name}', metric)
        return
```


> @angadkalra It will be hard to help if you cannot reproduce it.
> 
> Can you at least verify which of `current, self.best_k_models[self.kth_best_model_path]` is in CPU?

How would I go about verifying?

**Comment by angadkalra** [comment]
Also, I started seeing this:

```
/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py:285: UserWarning: Be aware that when using `ckpt_path`, callbacks used to create the checkpoint need to be provided during `Trainer` instantiation. Please add the following callbacks: ["ModelCheckpoint{'monitor': 'binary_classification_valid_SensAt90Spec', 'mode': 'max', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None, 'save_on_train_epoch_end': True}"].
  UserWarning,
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:248: UserWarning: You're resuming from a checkpoint that ended mid-epoch. Training will start from the beginning of the next epoch. This can cause unreliable results if further training is done, consider using an end of epoch checkpoint.
  "You're resuming from a checkpoint that ended mid-epoch."
Restored all states from the checkpoint file at /imvaria/data/saved_models/FibresolveStudy/02e25bac8b294a7d9fe08c453024e3c3/last.ckpt
```

I'm passing in the ModelCheckpoint callback exactly like that through callbacks arg in Trainer, so I don't know whats going on...Also how can last.ckpt be mid-epoch ending?

**Comment by angadkalra** [comment]
Problem fixed! My custom metric was causing the problem because I wasn't moving the sens, spec, and threshold tensors to GPU when initializing. I used .type_as(preds) in the compute() function and it runs fine now! Thanks for the help!
