### ISSUE TITLE
Callback derived class is called without trainer argument

### ISSUE THREAD

**Issue by oplatek** [PyTorchLightning/pytorch-lightning#1106]
## 🐛 Bug

The class `Callback(abc.ABC)` API expects `trainer` and sometimes `pl_module` to be supplied. E.g.:
```
def on_init_start(self, trainer):
    pass
```
[See the definition](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/base.py#L10)

However, the caller `TrainerCallbackHookMixin` **calls the callback methods without the `trainer` argument.** E.g.:

```
for callback in self.callbacks:
     callback.on_init_start(self)
```
[See the calls](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/callback_hook.py#L15)

### To Reproduce
[Follow the documentation for callbacks](https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html#early-stopping)

and expect similar output
```
Traceback (most recent call last):
  File "./train_encdec_pl.py", line 33, in <module>
    callbacks=[SavePredictionCB])
  File "/workspace/oplatek/code/demo/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 239, in __init__
    self.on_init_start()
  File "/workspace/oplatek/code/demo/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/callback_hook.py", line 18, in on_init_start
    callback.on_init_start(self)
TypeError: on_init_start() missing 1 required positional argument: 'trainer'
```

**Comment by oplatek** [comment]
Ping me if you want me to create a PR where I will add the `trainer` argument for each method TrainerCallbackHookMixin

**Comment by oplatek** [comment]
The issue is incorrectly described
