### ISSUE TITLE
Colab TPU error

### ISSUE THREAD

**Issue by patil-suraj** [PyTorchLightning/pytorch-lightning#1135]
I'm trying to run a LSTM model on TPU with colab. It throws me following error.
```
Exception in device=TPU:1: Aborted: Session 0275bc9f6430801b is not found.
Exception in device=TPU:3: Aborted: Session 780bc43376b5f650 is not found.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 500, in tpu_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 500, in tpu_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_pretrain_routine
    False)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_pretrain_routine
    False)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/evaluation_loop.py", line 251, in evaluate
    for batch_idx, batch in enumerate(dataloader):
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/evaluation_loop.py", line 251, in evaluate
    for batch_idx, batch in enumerate(dataloader):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py", line 31, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py", line 31, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py", line 34, in next
    xm.mark_step()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py", line 34, in next
    xm.mark_step()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 405, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 405, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Aborted: Session 0275bc9f6430801b is not found.
RuntimeError: Aborted: Session 780bc43376b5f650 is not found.
Exception in device=TPU:5: Aborted: Session e191a99b56d63c29 is not found.
Traceback (most recent call last):
```
Anyone has any ideas what this could mean ? 
Thanks in advance!

**Comment by Borda** [comment]
@hadim @jeffling could you check pls?

**Comment by Borda** [comment]
@patil-suraj may you pls share the example?

**Comment by patil-suraj** [comment]
I tried to run it with version 0.7.3 and it ran without any error :)
