### ISSUE TITLE
LightningModel.save_hyperparameters() tries to pickle ignored parameters

### ISSUE THREAD

**Issue by cowwoc** [PyTorchLightning/pytorch-lightning#11453]
### To Reproduce

1. Given:
```
class Predictor(LightningModule):
    def __init__(self, parameters: dict[str, Any], queue: Queue):
        super(Predictor, self).__init__()
        self.save_hyperparameters(parameters, ignore="queue")
```
2. Invoking `Predictor.load_from_checkpoint(model_path, queue=queue)` causes Predictor's constructor to get `queue` two times. Once in the `parameters` argument and once in the `queue` argument.

### Expected behavior

Invoking `self.save_hyperparameters(parameters, ignore="queue")` should not attempt to pickle `queue`, but it does and it ends up throwing the following exception:

```
  File "C:\Users\Gili\Documents\foobar\python\lib\site-packages\pytorch_lightning\core\mixins\hparams_mixin.py", line 105, in save_hyperparameters
    save_hyperparameters(self, *args, ignore=ignore, frame=frame)
  File "C:\Users\Gili\Documents\foobar\python\lib\site-packages\pytorch_lightning\utilities\parsing.py", line 251, in save_hyperparameters
    obj._hparams_initial = copy.deepcopy(obj._hparams)
  File "C:\Python39\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Python39\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\Python39\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "C:\Python39\lib\multiprocessing\managers.py", line 900, in __deepcopy__
    return self._getvalue()
  File "C:\Python39\lib\multiprocessing\managers.py", line 831, in _getvalue
    return self._callmethod('#GETVALUE')
  File "C:\Python39\lib\multiprocessing\managers.py", line 825, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Unserializable message: Traceback (most recent call last):
  File "C:\Python39\lib\multiprocessing\managers.py", line 300, in serve_client
    send(msg)
  File "C:\Python39\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Python39\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object

---------------------------------------------------------------------------
python-BaseException
```

### Environment

```
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3080
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.21.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0+cu113
        - pytorch-lightning: 1.5.8
        - tqdm:              4.62.3
* System:
        - OS:                Windows
        - architecture:
                - 64bit
                - WindowsPE
        - processor:         AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
        - python:            3.9.7
        - version:           10.0.19044
```

**Comment by cowwoc** [comment]
Caused by user error. Fixed using https://github.com/PyTorchLightning/pytorch-lightning/issues/9919#issuecomment-950518499
