### ISSUE TITLE
AttributeError: 'DataLoader' object has no attribute '__code__'

### ISSUE THREAD

**Issue by SongyiGao** [PyTorchLightning/pytorch-lightning#11495]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/11492

<div type='discussions-op-text'>

<sup>Originally posted by **SongyiGao** January 15, 2022</sup>
**My code:**

```py
....
algo = Rank(task=task)
algo.train_dataloader = train_dataloader
algo.val_dataloader= val_dataloader
trainer = pl.Trainer()
print("train_dataloader:",algo.train_dataloader)
print("val_dataloader:",algo.val_dataloader)
trainer.fit(algo)
```

**The Error massage:**

```py
train_dataloader: <torch.utils.data.dataloader.DataLoader object at 0x7f679a996e90>
val_dataloader: <torch.utils.data.dataloader.DataLoader object at 0x7f679aabeb10>

Traceback (most recent call last):
  File "/home/ubuntu/yi/resarch/quantopt/quantopt/algo/task/task.py", line 158, in <module>
    trainer.fit(algo)
  File "/home/ubuntu/anaconda3/envs/yi/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/ubuntu/anaconda3/envs/yi/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 849, in _run
    self.config_validator.verify_loop_configurations(model)
  File "/home/ubuntu/anaconda3/envs/yi/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 34, in verify_loop_configurations
    self.__verify_train_loop_configuration(model)
  File "/home/ubuntu/anaconda3/envs/yi/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 59, in __verify_train_loop_configuration
    has_train_dataloader = is_overridden("train_dataloader", model)
  File "/home/ubuntu/anaconda3/envs/yi/lib/python3.7/site-packages/pytorch_lightning/utilities/model_helpers.py", line 68, in is_overridden
    instance_code = getattr(instance_attr, "patch_loader_code", None) or instance_attr.__code__
AttributeError: 'DataLoader' object has no attribute '__code__'
`</div>
```

**Comment by awaelchli** [comment]
Hello
Thanks for reporting this. Please read our bug report template before posting the issue. Provide as much information as possible about your environment and the code you provide. The GitHub issues are meant for discussiong bugs, feature and in general the development of Lightning. The discussion forum is for coding help and questions. I see you duplicated this from a discussion. Let's close this and I will answer on the original discussion. 

The likely reason why you see this problem is because you are naively patching your module:

```py
algo.train_dataloader = train_dataloader
algo.val_dataloader= val_dataloader
```
