### ISSUE TITLE
Early stopping conditioned on metric `val_loss` which is not available

### ISSUE THREAD

**Issue by JackRio** [PyTorchLightning/pytorch-lightning#12095]
## 🐛 Bug

_Early stopping conditioned on metric `val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss`_

I looked at similar issues and tried changing the `lightning version` to 1.5.0 and 1.4.0 didn't work

[#490](https://github.com/PyTorchLightning/pytorch-lightning/issues/490) and [#554](https://github.com/asteroid-team/asteroid/issues/554)

### To Reproduce

The code runs perfectly fine on my windows 11 machine with torch(1.10.2), cuda(11.6), and pytorch lightning(1.5.10). When I try to run on the cluster using docker. It throws the above error only difference is docker has cuda(11.3).

Part of my code
```
early_stopping = EarlyStopping(monitor='val_loss')
lr_monitor = LearningRateMonitor(logging_interval='epoch')
checkpoint_callback = ModelCheckpoint(dirpath=main_conf["OUTPUT_DIR"])
wandb_logger = WandbLogger(project='dummy', name=main_conf["UNET_MODEL_NAME"], entity="dummy")
trainer = pl.Trainer(gpus=1, callbacks=[early_stopping, lr_monitor, checkpoint_callback], logger=wandb_logger, default_root_dir=main_conf["OUTPUT_DIR"])
trainer.fit(unet)

    def training_step(self, batch, batch_idx):
        X, y, idx = batch
        pred = self(X)
        loss = ACARMSELoss()(pred, y)

        self.log("train_loss", loss)
        return {"loss": loss, "idx": idx}

    def training_epoch_end(self, outputs):
        indexes = [x['idx'] for x in outputs]
        self.histo += indexes

    def on_train_end(self):
        bins = np.linspace(0, 18000, 31)
        histo_cpu = torch.cat(self.histo).detach().cpu()
        digitized = np.digitize(histo_cpu, bins)
        bin_means = [[i, histo_cpu[digitized == i].size()[0]] for i in range(1, len(bins))]
        table = wandb.Table(data=bin_means, columns=['index', 'count'])
        wandb.log({"Distribution Bar Plot": wandb.plot.bar(table, "index", 'count', title="Distribution of idx")})

    def validation_step(self, batch, batch_idx):
        X, y, idx = batch
        pred = self(X)
        val_loss = ACARMSELoss()(pred, y)

        self.log('val_loss', val_loss)
        return {"val_loss": val_loss}

    def validation_epoch_end(self, outputs):
        val_loss = torch.stack([x['val_loss'] for x in outputs]).mean()

        log = {"avg_val_loss": val_loss}
        self.log("avg_val_loss", val_loss)
        return {"log": log, "val_loss": val_loss}

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.conf["LR"])
        lr_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min')
        return {
            'optimizer': optimizer,
            'scheduler': lr_scheduler,
            'monitor': 'val_loss'
        }

```

### Environment

- PyTorch Lightning Version 1.5.10
- PyTorch Version 1.10.2
- Python version 3.7.9
- Docker 
- CUDA/cuDNN version: 11.3
- How you installed PyTorch: pip

### Additional context

The first training epoch does not even finish and it throws this error. I have a batch size of 32 with 7000 train samples meaning (219 train step and 41 val step). After 41 steps the training crashes

`Epoch 0:  16% 41/260 [00:47<04:12,  1.15s/it, loss=0.0755, v_num=d8j2]
`
Traceback
```
Traceback (most recent call last):
  File "src/unet/main.py", line 70, in <module>
    main()
  File "src/unet/main.py", line 42, in main
    trainer.fit(unet)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 298, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1495, in call_hook
    callback_fx(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 189, in on_train_epoch_end
    self._run_early_stopping_check(trainer)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 200, in _run_early_stopping_check
    if trainer.fast_dev_run or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 151, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss`
```

**Comment by rohitgr7** [comment]
the training step at which it crashed doesn't seem to be the total batches that you have inside dataloader, but training epoch end is triggered at step 41, which is weird. Are you using `val_check_interval`?

Also can you make sure that inside the docker run, the version is still >=1.5?

**Comment by JackRio** [comment]
No, I haven't set `val_check_interval` it should be the default (1.0).

I checked the version inside the docker it is `1.5.10 `

**Comment by JackRio** [comment]
Okay, I found the issue, the mounted input directory had incorrect CSV files(all created using Val dataset which solves why it was ending at 41 steps since that are the steps for validation data with 32 batch size) which is used by the data loader.  My local CSV files were correct. So the issue was at my end sorry for the inconvenience and thanks for the help

**Comment by flalix** [comment]
I fixed the problem by changing 'loss' to 'train_loss' in EarlyStopping()

EarlyStopping(monitor='loss', patience=2)
to
EarlyStopping(monitor='train_loss', patience=2)

since my training_step logs -> self.log("train_loss", ...)

    def training_step(self, batch, batch_idx):
        
        input_ids      = batch["input_ids"]
        attention_mask = batch["attention_mask"]
        labels         = batch["labels"]
        
        loss, outputs  = self(input_ids, attention_mask, labels)
        self.training_step_outputs.append(loss)

        self.log("train_loss", loss, prog_bar=True, logger=True)

        return {"loss": loss, "predictions": outputs, "labels": labels}
