### ISSUE TITLE
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

### ISSUE THREAD

**Issue by iqbalfarz** [PyTorchLightning/pytorch-lightning#12257]
I am running a simple MNIST classification using PL and want to run on multi-node.

The code is 
```python
import os

import torch
from pytorch_lightning import LightningModule, Trainer, seed_everything
seed_everything(42, workers=True) # seed everything to get almost same result all the times.

from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, random_split
from torchmetrics import Accuracy
from torchvision import transforms
from torchvision.datasets import MNIST

PATH_DATASETS = os.environ.get("PATH_DATASETS", "/mnt/hdd/muhammad")
AVAIL_GPUS = min(2, torch.cuda.device_count())
BATCH_SIZE = 256 if AVAIL_GPUS else 64


# initializing environmental variables
# os.environ["MASTER_PORT"]="12500"
# os.environ["WORLD_SIZE"]="2"
# os.environ["NODE_RANK"]="0"
# os.environ["MASTER_ADDR"]="172.21.12.6"



class LitMNIST(LightningModule):
    def __init__(self, data_dir=PATH_DATASETS, hidden_size=64, learning_rate=2e-4):

        super().__init__()

        # Set our init args as class attributes
        self.data_dir = data_dir
        self.hidden_size = hidden_size
        self.learning_rate = learning_rate

        # Hardcode some dataset specific attributes
        self.num_classes = 10
        self.dims = (1, 28, 28)
        channels, width, height = self.dims
        self.transform = transforms.Compose(
            [
                transforms.ToTensor(),
                transforms.Normalize((0.1307,), (0.3081,)),
            ]
        )

        # Define PyTorch model
        self.model = nn.Sequential(
            nn.Flatten(),
            nn.Linear(channels * width * height, hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size, self.num_classes),
        )

        self.accuracy = Accuracy()

    def forward(self, x):
        x = self.model(x)
        return F.log_softmax(x, dim=1)

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        loss = F.nll_loss(logits, y)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        loss = F.nll_loss(logits, y)
        preds = torch.argmax(logits, dim=1)
        self.accuracy(preds, y)

        # Calling self.log will surface up scalars for you in TensorBoard
        self.log("val_loss", loss, prog_bar=True)
        self.log("val_acc", self.accuracy, prog_bar=True)
        return loss

    def test_step(self, batch, batch_idx):
        # Here we just reuse the validation_step for testing
        return self.validation_step(batch, batch_idx)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.learning_rate)
        return optimizer

    ####################
    # DATA RELATED HOOKS
    ####################

    def prepare_data(self):
        # download
        MNIST(self.data_dir, train=True, download=True)
        MNIST(self.data_dir, train=False, download=True)

    def setup(self, stage=None):

        # Assign train/val datasets for use in dataloaders
        if stage == "fit" or stage is None:
            mnist_full = MNIST(self.data_dir, train=True, transform=self.transform)
            self.mnist_train, self.mnist_val = random_split(mnist_full, [55000, 5000])

        # Assign test dataset for use in dataloader(s)
        if stage == "test" or stage is None:
            self.mnist_test = MNIST(self.data_dir, train=False, transform=self.transform)

    def train_dataloader(self):
        return DataLoader(self.mnist_train, batch_size=BATCH_SIZE)

    def val_dataloader(self):
        return DataLoader(self.mnist_val, batch_size=BATCH_SIZE)

    def test_dataloader(self):
        return DataLoader(self.mnist_test, batch_size=BATCH_SIZE)




if __name__=="__main__":
    model = LitMNIST()
    trainer = Trainer(
        gpus=AVAIL_GPUS,
        max_epochs=10,
        progress_bar_refresh_rate=20,
        strategy="ddp",
        num_nodes=2,
        auto_select_gpus=True,
        
    )
    trainer.fit(model)


# from argparse import ArgumentParser

# def main(args):
#     model = LitMNIST()
#     trainer = Trainer.from_argparse_args(args)
#     trainer.fit(model)

# if __name__=="__main__":
#     parser = ArgumentParser()
#     parser = Trainer.add_argparse_args(parser)
#     args = parser.parse_args()

#     main(args)


```

### I am having two nodes

__node 1:__
```
OS: Ubuntu
GPUs: 4 (GeForce RTX 2080 Ti)
CPUs: 24
```

__node 2:__
```
OS: Ubuntu
GPUs: 8 (RTX A6000)
CPUs: 256
```

<hr><hr>

__Script running on NODE 1:__
```NCCL_DEBUG=INFO MASTER_ADDR=172.21.12.6 MASTER_PORT=1234 NODE_RANK=0 python train_mnist_light.py```

__Script running on NODE 2:__
```NCCL_DEBUG=INFO MASTER_ADDR=172.21.12.6 MASTER_PORT=1234 NODE_RANK=1 python train_mnist_light.py```

<hr><hr>

__Error on NODE 1:__
```
Global seed set to 42
/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/callback_connector.py:90: LightningDeprecationWarning: Setting `Trainer(progress_bar_refresh_rate=20)` is deprecated in v1.5 and will be removed in v1.7. Please pass `pytorch_lightning.callbacks.progress.TQDMProgressBar` with `refresh_rate` directly to the Trainer's `callbacks` argument instead. Or, to disable the progress bar pass `enable_progress_bar = False` to the Trainer.
  rank_zero_deprecation(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Global seed set to 42
Global seed set to 42
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Global seed set to 42
initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

gpu56:403432:403432 [0] NCCL INFO Bootstrap : Using enp6s0:172.21.12.6<0>
gpu56:403432:403432 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu56:403432:403432 [0] NCCL INFO NET/IB : No device found.
gpu56:403432:403432 [0] NCCL INFO NET/Socket : Using [0]enp6s0:172.21.12.6<0>
gpu56:403432:403432 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.3
gpu56:403506:403506 [1] NCCL INFO Bootstrap : Using enp6s0:172.21.12.6<0>
gpu56:403506:403506 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu56:403506:403506 [1] NCCL INFO NET/IB : No device found.
gpu56:403506:403506 [1] NCCL INFO NET/Socket : Using [0]enp6s0:172.21.12.6<0>
gpu56:403506:403506 [1] NCCL INFO Using network Socket
gpu56:403506:403777 [1] NCCL INFO Could not enable P2P between dev 1(=9000) and dev 0(=7000)
gpu56:403506:403777 [1] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=9000)
gpu56:403506:403777 [1] NCCL INFO Could not enable P2P between dev 1(=9000) and dev 0(=7000)
gpu56:403506:403777 [1] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=9000)
gpu56:403432:403776 [0] NCCL INFO Could not enable P2P between dev 1(=9000) and dev 0(=7000)
gpu56:403432:403776 [0] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=9000)
gpu56:403432:403776 [0] NCCL INFO Could not enable P2P between dev 1(=9000) and dev 0(=7000)
gpu56:403432:403776 [0] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=9000)
gpu56:403432:403776 [0] NCCL INFO Channel 00/02 :    0   1   2   3
gpu56:403432:403776 [0] NCCL INFO Channel 01/02 :    0   1   2   3
gpu56:403432:403776 [0] NCCL INFO Trees [0] 1/2/-1->0->-1 [1] 1/-1/-1->0->2
gpu56:403432:403776 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
gpu56:403506:403777 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
gpu56:403506:403777 [1] NCCL INFO Setting affinity for GPU 1 to ffffff
gpu56:403506:403777 [1] NCCL INFO Could not enable P2P between dev 1(=9000) and dev 0(=7000)
gpu56:403432:403776 [0] NCCL INFO Channel 00 : 3[25000] -> 0[7000] [receive] via NET/Socket/0
gpu56:403506:403777 [1] NCCL INFO Could not enable P2P between dev 1(=9000) and dev 0(=7000)
gpu56:403432:403776 [0] NCCL INFO Channel 01 : 3[25000] -> 0[7000] [receive] via NET/Socket/0
gpu56:403432:403776 [0] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=9000)
gpu56:403432:403776 [0] NCCL INFO Channel 00 : 0[7000] -> 1[9000] via direct shared memory
gpu56:403432:403776 [0] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=9000)
gpu56:403432:403776 [0] NCCL INFO Channel 01 : 0[7000] -> 1[9000] via direct shared memory
gpu56:403506:403777 [1] NCCL INFO Channel 00 : 1[9000] -> 2[1000] [send] via NET/Socket/0
gpu56:403506:403777 [1] NCCL INFO Channel 01 : 1[9000] -> 2[1000] [send] via NET/Socket/0
gpu56:403432:403776 [0] NCCL INFO Connected all rings
gpu56:403432:403776 [0] NCCL INFO Channel 00 : 2[1000] -> 0[7000] [receive] via NET/Socket/0
gpu56:403432:403776 [0] NCCL INFO Channel 01 : 2[1000] -> 0[7000] [receive] via NET/Socket/0
gpu56:403432:403776 [0] NCCL INFO Channel 00 : 0[7000] -> 2[1000] [send] via NET/Socket/0
gpu56:403432:403776 [0] NCCL INFO Channel 01 : 0[7000] -> 2[1000] [send] via NET/Socket/0

gpu56:403506:403777 [1] include/socket.h:409 NCCL WARN Net : Connect to 169.254.3.1<34341> failed : No route to host
gpu56:403506:403777 [1] NCCL INFO transport/net_socket.cc:316 -> 2
gpu56:403506:403777 [1] NCCL INFO include/net.h:21 -> 2
gpu56:403506:403777 [1] NCCL INFO transport/net.cc:210 -> 2
gpu56:403506:403777 [1] NCCL INFO transport.cc:111 -> 2
gpu56:403506:403777 [1] NCCL INFO init.cc:778 -> 2
gpu56:403506:403777 [1] NCCL INFO init.cc:904 -> 2
gpu56:403506:403777 [1] NCCL INFO group.cc:72 -> 2 [Async thread]
Traceback (most recent call last):
  File "/home/muhammad/Gender Recognition/model_training/train_mnist_light.py", line 135, in <module>
    trainer.fit(model)
  File "/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1435, in _call_setup_hook
    self.training_type_plugin.barrier("pre_setup")
  File "/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 403, in barrier
    torch.distributed.barrier(device_ids=self.determine_ddp_device_ids())
  File "/home/muhammad/anaconda3/envs/distributed_training/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1640811806235/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
```

__Error on NODE 2:__
```
Global seed set to 42
Global seed set to 42
Global seed set to 42
initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Global seed set to 42
initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
zlabs-gamd6:3193532:3193532 [1] NCCL INFO Bootstrap : Using eno1:172.24.133.238<0>
zlabs-gamd6:3193532:3193532 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
zlabs-gamd6:3193360:3193360 [0] NCCL INFO Bootstrap : Using eno1:172.24.133.238<0>
zlabs-gamd6:3193360:3193360 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
zlabs-gamd6:3193532:3193532 [1] NCCL INFO NET/IB : No device found.
zlabs-gamd6:3193532:3193532 [1] NCCL INFO NET/Socket : Using [0]eno1:172.24.133.238<0> [1]enxb03af2b6059f:169.254.3.1<0> [2]veth1f05ad1:fe80::902b:2dff:fede:5cb5%veth1f05ad1<0>
zlabs-gamd6:3193532:3193532 [1] NCCL INFO Using network Socket
zlabs-gamd6:3193360:3193360 [0] NCCL INFO NET/IB : No device found.
zlabs-gamd6:3193360:3193360 [0] NCCL INFO NET/Socket : Using [0]eno1:172.24.133.238<0> [1]enxb03af2b6059f:169.254.3.1<0> [2]veth1f05ad1:fe80::902b:2dff:fede:5cb5%veth1f05ad1<0>
zlabs-gamd6:3193360:3193360 [0] NCCL INFO Using network Socket
zlabs-gamd6:3193360:3193582 [0] NCCL INFO Trees [0] 3/-1/-1->2->0 [1] 3/0/-1->2->-1
zlabs-gamd6:3193360:3193582 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,00000000,00000000,ffffffff,ffffffff
zlabs-gamd6:3193532:3193581 [1] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2
zlabs-gamd6:3193532:3193581 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,ffffffff,00000000,00000000,ffffffff,ffffffff
zlabs-gamd6:3193532:3193581 [1] NCCL INFO Channel 00 : 3[25000] -> 0[7000] [send] via NET/Socket/1
zlabs-gamd6:3193360:3193582 [0] NCCL INFO Channel 00 : 1[9000] -> 2[1000] [receive] via NET/Socket/1
zlabs-gamd6:3193532:3193581 [1] NCCL INFO Channel 01 : 3[25000] -> 0[7000] [send] via NET/Socket/1
zlabs-gamd6:3193360:3193582 [0] NCCL INFO Channel 01 : 1[9000] -> 2[1000] [receive] via NET/Socket/1
zlabs-gamd6:3193360:3193582 [0] NCCL INFO Channel 00 : 2[1000] -> 3[25000] via P2P/IPC
zlabs-gamd6:3193360:3193582 [0] NCCL INFO Channel 01 : 2[1000] -> 3[25000] via P2P/IPC
zlabs-gamd6:3193532:3193581 [1] NCCL INFO Connected all rings
zlabs-gamd6:3193532:3193581 [1] NCCL INFO Channel 00 : 3[25000] -> 2[1000] via P2P/IPC
zlabs-gamd6:3193532:3193581 [1] NCCL INFO Channel 01 : 3[25000] -> 2[1000] via P2P/IPC

hang...
```

cc @borda @rohitgr7 @justusschock @kaushikb11 @awaelchli @akihironitta

**Comment by awaelchli** [comment]
@iqbalfarz I believe the problem is that you have an unbalanced number of GPUs in each node. On node 1, the script will want to run with 4 gpus and on node 2 it will want to run with 8. However, the number you set for gpus=X needs to be the same value on both nodes. Unbalanced node size is currently NOT supported (I know this wasn't obvious from any of our docs). 

Can you manually set gpus=4 to verify that it works this way at least?

**Comment by iqbalfarz** [comment]
Hi @awaelchli , in the .py file, I used `min(2, ....)`, it means on both machine 2 gpus will be selected, right. But still, let me try. But the same code is running using `gloo` backend.

**Comment by awaelchli** [comment]
> I used min(2, ....), it means on both machine 2 gpus will be selected, right


No, certainly not. `torch.cuda.device_count()` will return 4 on node1 and and 8 on node 2, and hence `AVAIL_GPUS` will also take these values on each node.

> But the same code is running using gloo backend.

I'm surprised it does. It shouldn't.

**Comment by awaelchli** [comment]
When setting num_nodes=2 and gpus=4 (on both nodes!!) you should see this in the terminal of node 1:

```
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/8
initializing distributed: GLOBAL_RANK: 0, MEMBER: 2/8
initializing distributed: GLOBAL_RANK: 0, MEMBER: 3/8
initializing distributed: GLOBAL_RANK: 0, MEMBER: 0/8
```

and this in the terminal of node 2:
```
initializing distributed: GLOBAL_RANK: 0, MEMBER: 4/8
initializing distributed: GLOBAL_RANK: 0, MEMBER: 5/8
initializing distributed: GLOBAL_RANK: 0, MEMBER: 6/8
initializing distributed: GLOBAL_RANK: 0, MEMBER: 7/8
```

Make sure that both nodes run the same code (sync your py files).
