### ISSUE TITLE
AttributeError: 'str' object has no attribute 'trainer'

### ISSUE THREAD

**Issue by zxwang96** [PyTorchLightning/pytorch-lightning#12451]
## 🐛 Bug

At the end of the training, I got the following error message
```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type               | Params
---------------------------------------------
0 | model | Transformer_ODE_AE | 947 K 
---------------------------------------------
947 K     Trainable params
0         Non-trainable params
947 K     Total params
3.791     Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]>>> Validation dataset length: 28560
>>> Training dataset length: 182327                                                                                                                                                                                
████████████████████████████████████████████| 210887/210887 [2:58:19<00:00, 19.71it/s, loss=55.4, v_num=3, train_loss_step=83.90, val_loss_step=68.30, val_loss_epoch=61.80, train_loss_epoch=51.20]
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/wang5389/workspace/dense-pose-pred/main_h36m.py", line 194, in <module>
    trainer.fit(learner)
  File "/home/wang5389/miniconda3/envs/pose-pred/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/wang5389/miniconda3/envs/pose-pred/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/wang5389/miniconda3/envs/pose-pred/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 947, in _test_impl
    self._data_connector.attach_data(model, test_dataloaders=dataloaders, datamodule=datamodule)
  File "/home/wang5389/miniconda3/envs/pose-pred/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 190, in attach_data
    self._copy_trainer_model_properties(model)
  File "/home/wang5389/miniconda3/envs/pose-pred/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 196, in _copy_trainer_model_properties
    m.trainer = proxy(self.trainer)
AttributeError: 'str' object has no attribute 'trainer'
```
I didn't modify any part of the trainer, can you help me solve this issue?

cc @justusschock @kaushikb11 @awaelchli @borda @ananthsub @ninginthecloud @jjenniferdai @rohitgr7 @akihironitta

**Comment by rohitgr7** [comment]
this is weird.
> File "/home/wang5389/workspace/dense-pose-pred/main_h36m.py", line 194, in <module>
    trainer.fit(learner)
  File "/home/wang5389/miniconda3/envs/pose-pred/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)

you are calling `trainer.fit`, but it's going over `trainer.test` internally.
can you share the code-snippet where you are calling the trainer?

**Comment by rohitgr7** [comment]
```py
trainer.test('best')
```
should be:
```py
trainer.test(ckpt_path='best')
```

**Comment by zxwang96** [comment]
Thanks, problem resolved!
