### ISSUE TITLE
pytorch_lightning.utilities.imports error

### ISSUE THREAD

**Issue by Django-Jiang** [PyTorchLightning/pytorch-lightning#12753]
### To Reproduce

```
(pytorch) fj@a-pc:~/code/MyBigDL$ python
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib import import_module
>>> import_module("python")
<module 'python' (namespace)>
>>> 
>>> import pytorch_lightning.utilities.imports
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py", line 88, in <module>
    _PYTHON_GREATER_EQUAL_3_8_0 = _compare_version("python", operator.ge, "3.8.0")
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py", line 77, in _compare_version
    pkg_version = Version(pkg_resources.get_distribution(package).version)
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pkg_resources/__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pkg_resources/__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/fj/anaconda3/envs/nano-pytorch/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python' distribution was not found and is required by the application
```

``
### Environment
```
* CUDA:
        - GPU:
        - available:         False
        - version:           10.2
* Packages:
        - numpy:             1.22.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cu102
        - pytorch-lightning: 1.6.0
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.13
```

**Comment by awaelchli** [comment]
Interesting! I think this is definitely the cause of #12752. Funny that we opened these related issues almost at the same time. 
Thanks for reporting!
