### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'get'

### ISSUE THREAD

**Issue by HiAleeYang** [PyTorchLightning/pytorch-lightning#12990]
https://github.com/PyTorchLightning/pytorch-lightning/blob/4818229be67e6eae7605824e66b232bfcb408f58/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L230
I face this problem when I restore my 'pt' file in test
Traceback (most recent call last):
  File "gaitgraph_casia_b.py", line 283, in <module>
    cli_main()
  File "gaitgraph_casia_b.py", line 273, in cli_main
    LightningCLI(
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 566, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 837, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in predict
    return self._call_and_handle_interrupt(
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1070, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _restore_modules_and_callbacks
    self._checkpoint_connector._restore_quantization_callbacks()
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 230, in _restore_quantization_callbacks
    callback_states = self._loaded_checkpoint.get("callbacks")
AttributeError: 'tuple' object has no attribute 'get'

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by carmocca** [comment]
Hi!

Are you passing a `ckpt_path`? If so, can you check what `print(torch.load(ckpt_path))` shows?

It looks to me like it's a tuple.

**Comment by HiAleeYang** [comment]
Yes, sorry. that's my fault.I use the wrong checkpoint file. 
`print(torch.load(ckpt_path)) `  is
(Data(x=[523639, 17, 3], y=[5497], angle=[5497], seq_num=[5497], walking_status=[5497]), defaultdict(<class 'dict'>, {'x': tensor([     0,     92,    194,  ..., 523449, 523532, 523639]), 'y': tensor([   0,    1,    2,  ..., 5495, 5496, 5497]), 'angle': tensor([   0,    1,    2,  ..., 5495, 5496, 5497]), 'seq_num': tensor([   0,    1,    2,  ..., 5495, 5496, 5497]), 'walking_status': tensor([   0,    1,    2,  ..., 5495, 5496, 5497])}))

Sorry for that, and thank you for your help!
