### ISSUE TITLE
Tracking - pytorch lightning fails to import with protobuf-4.21.1

### ISSUE THREAD

**Issue by shrinath-suresh** [PyTorchLightning/pytorch-lightning#13212]
## 🐛 Bug

pytorch-lightning import fails with latest version of google-protobuf ([4.21.1](https://pypi.org/project/protobuf/4.21.1/)) 

### To Reproduce

Install probuf 4.21.1 using pip

`pip install -U protobuf`

and import pytorch lightning

```
(base) $ python
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_lightning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py", line 102, in <module>
    _DEEPSPEED_GREATER_EQUAL_0_5_9 = _DEEPSPEED_AVAILABLE and _compare_version("deepspeed", operator.ge, "0.5.9")
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py", line 71, in _compare_version
    pkg = importlib.import_module(package)
  File "/home/ubuntu/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/deepspeed/__init__.py", line 12, in <module>
    from .runtime.engine import DeepSpeedEngine
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 17, in <module>
    from tensorboardX import SummaryWriter
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/writer.py", line 15, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/proto/event_pb2.py", line 15, in <module>
    from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/proto/summary_pb2.py", line 15, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/proto/tensor_pb2.py", line 15, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
>>> 

```

### Expected behavior

pytorch-lightning should get imported without any error

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.4
- PyTorch Version (e.g., 1.10): 1.11.0
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

protobuf version is tagged to `<=3.20.1` in [PTL requirements](https://github.com/PyTorchLightning/pytorch-lightning/blob/5a5b6161103042df4db99619dd0daaa33dffe5d7/requirements/base.txt#L11)

Downgrading the probuf version to 3.20.1 works as expected.

Creating this issue for tracking purpose to support new version of probuf (4.21.1)

**Comment by akihironitta** [comment]
Duplicate of #13159.

**Comment by akihironitta** [comment]
> Creating this issue for tracking purpose to support new version of probuf (4.21.1)

Maybe I should've waited before closing this issue, but I think the tracking issue should be https://github.com/tensorflow/tensorboard/issues/5708 instead of this issue in our repo since there's nothing we can do for that.
