### ISSUE TITLE
Allow for (nested) dictionaries as LightningModule.example_input_array

### ISSUE THREAD

**Issue by lkskstlr** [PyTorchLightning/pytorch-lightning#1515]
Thank you for this excellent library.

## 🚀 Feature

As far as I can tell, `LightningModule.example_input_array` can either be a `torch.Tensor`, a `tuple`, or a `list`. It would be cool to support nested dictionaries as well.

### Motivation

The  `LightningModule.forward` method does support nested dictionaries and for models with multiple inputs, this might be advantageous for keeping the code clean. Supporting this with `example_input_array` would allow such models to get input/output sizes in the weight summary.

Again, thank you very much for your work.

**Comment by HenryJia** [comment]
I believe this is already supported, both for multigpu and single GPU. The function to load it is recursive and will recurse into tuples, lists and dictionaries if they are nested

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/distrib_parts.py#L459

Can you provide a failure case for this?

**Comment by lkskstlr** [comment]
Thank you for your answer. I am not sure if we are talking about the same thing. Below is a minimal (non)-working example and it's output.

For me, the problem only occurs when using `example_input_array` which however I would like to use because I think the input and output sizes for the weights summary are quite useful.

```python
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import LightningModule, Trainer


class DictDataset(Dataset):
    def __init__(self):
        self.x = torch.rand(10 ** 3, 1, 96, 128)
        self.y = torch.rand(10 ** 3, 1, 96, 128)

    def __getitem__(self, idx):
        return {'x': self.x[idx], 'y': self.y[idx]}

    def __len__(self):
        return len(self.x)


class SingleInputDataset(Dataset):
    def __init__(self):
        self.x = torch.rand(10 ** 3, 1, 96, 128)

    def __getitem__(self, idx):
        return self.x[idx]

    def __len__(self):
        return len(self.x)


class DictModel(LightningModule):
    def __init__(self, use_example_input_array=False):
        # init superclass
        super().__init__()

        if use_example_input_array:
            self.example_input_array = {'x': torch.rand(2, 1, 96, 128), 'y': torch.rand(2, 1, 96, 128)}

        self.conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=1, stride=1)

    def forward(self, batch: dict):
        x = self.conv(batch['x'])
        z = batch['y'] * x

        return torch.sum(z, (1, 2))

    def training_step(self, batch, batch_idx):
        out = self(batch)
        loss = torch.mean(out ** 2)  # just something
        return {'loss': loss}

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=0.001)
        return optimizer

    def train_dataloader(self):
        return DataLoader(DictDataset(), batch_size=2, num_workers=6)


class SingleInputModel(LightningModule):
    def __init__(self):
        # init superclass
        super().__init__()

        self.example_input_array = torch.rand(2, 1, 96, 128)

        self.conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=1, stride=1)

    def forward(self, x):
        z = self.conv(x)
        return torch.sum(z, (1, 2))

    def training_step(self, batch, batch_idx):
        out = self(batch)
        loss = torch.mean(out ** 2)  # just something
        return {'loss': loss}

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=0.001)
        return optimizer

    def train_dataloader(self):
        return DataLoader(SingleInputDataset(), batch_size=2, num_workers=6)


if __name__ == "__main__":
    print(f"{'-'*10} Single Input Model {'-'*10}")
    model = SingleInputModel()
    trainer = Trainer(max_steps=10)
    trainer.fit(model)

    print(f"{'-' * 10} Dict Model w/o example_input_array {'-' * 10}")
    model = DictModel()
    trainer = Trainer(max_steps=10)
    trainer.fit(model)

    print(f"{'-' * 10} Dict Model w/  example_input_array {'-' * 10}")
    model = DictModel(use_example_input_array=True)
    trainer = Trainer(max_steps=10)
    trainer.fit(model)
```

Output
```
python example_input_array.py
---------- Single Input Model ----------
INFO:lightning:
  | Name | Type   | Params | In sizes        | Out sizes      
----------------------------------------------------------------
0 | conv | Conv2d | 10     | [2, 1, 96, 128] | [2, 1, 96, 128]
0it [00:00, ?it/s]/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/pytorch_lightning/utilities/warnings.py:18: RuntimeWarning: Displayed epoch numbers in the progress bar start from "1" until v0.6.x, but will start from "0" in v0.8.0.
  warnings.warn(*args, **kwargs)
Epoch 1:   2%|▋                                 | 10/500 [00:00<00:09, 49.35it/s, loss=869.160, v_num=11]
---------- Dict Model w/o example_input_array ----------
INFO:lightning:
  | Name | Type   | Params
----------------------------
0 | conv | Conv2d | 10    
Epoch 1:   2%|▋                                 | 10/500 [00:00<00:08, 56.17it/s, loss=245.262, v_num=12]
---------- Dict Model w/  example_input_array ----------
Traceback (most recent call last):
  File "example_input_array.py", line 99, in <module>
    trainer.fit(model)
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 732, in fit
    self.run_pretrain_routine(model)
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 801, in run_pretrain_routine
    ref_model.summarize(mode=self.weights_summary)
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1551, in summarize
    model_summary = ModelSummary(self, mode=mode)
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/pytorch_lightning/core/memory.py", line 29, in __init__
    self.summarize()
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/pytorch_lightning/core/memory.py", line 160, in summarize
    self.get_variable_sizes()
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/pytorch_lightning/core/memory.py", line 78, in get_variable_sizes
    out = m(input_)
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/lukas/anaconda2/envs/torch-cpu/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not dict
```

**Comment by williamFalcon** [comment]
fixed on master.
Will re-open if still an issue

**Comment by IgorDavidyuk** [comment]
> fixed on master.
> Will re-open if still an issue

Hello, could you please point to the commit?
I am facing this issue. My dataset passes me dicts with data, so I can not train on coda without explicitly transferring data
Well, the simple way is to rewrite the dataset, but it would be nice to have automatic transfer
