### ISSUE TITLE
Test demo error

### ISSUE THREAD

**Issue by as754770178** [PyTorchLightning/pytorch-lightning#1792]
```
Traceback (most recent call last):
  File "/home/zgz/github_code/pytorch-lightning/tests/base/models.py", line 15, in <module>
    from test_tube import HyperOptArgumentParser
ModuleNotFoundError: No module named 'test_tube'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zgz/github_code/pytorch-lightning/tests/callbacks/test_callbacks.py", line 2, in <module>
    import tests.base.utils as tutils
  File "/home/zgz/github_code/pytorch-lightning/tests/base/__init__.py", line 33, in <module>
    from tests.base.models import TestModelBase, DictHparamsModel
  File "/home/zgz/github_code/pytorch-lightning/tests/base/models.py", line 18, in <module>
    raise ImportError('Missing test-tube package.')
ImportError: Missing test-tube package.
```

When I run test code, report error: `ImportError: Missing test-tube package.`

**Comment by williamFalcon** [comment]
That model is meant for testing not as a demo... here's a demo 
https://colab.research.google.com/drive/1F_RNcHzTfFuQf-LeKvSlud6x7jXYkG31
