### ISSUE TITLE
Isuue with Colab TPU: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'

### ISSUE THREAD

**Issue by Alikerin** [PyTorchLightning/pytorch-lightning#1832]
Whenever I setup my colab runtime with the code provided in PyTorch-Lightning Documentation, Release 0.7.6rc1 on page 190: TPU support I get the follwing exception:

```
INFO:lightning:training on 8 TPU cores

INFO:lightning:INIT TPU local core: 0, global rank: 0
INFO:lightning:INIT TPU local core: 2, global rank: 2
Exception in device=TPU:2: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
INFO:lightning:INIT TPU local core: 3, global rank: 3
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 523, in tpu_train
    self.run_pretrain_routine(model)
INFO:lightning:INIT TPU local core: 4, global rank: 4
Exception in device=TPU:3: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 853, in run_pretrain_routine
    torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
AttributeError: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
Exception in device=TPU:4: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
INFO:lightning:INIT TPU local core: 5, global rank: 5
Traceback (most recent call last):
Exception in device=TPU:5: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 523, in tpu_train
    self.run_pretrain_routine(model)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 853, in run_pretrain_routine
    torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
AttributeError: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 523, in tpu_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 853, in run_pretrain_routine
    torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
AttributeError: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 523, in tpu_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 853, in run_pretrain_routine
    torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
INFO:lightning:INIT TPU local core: 6, global rank: 6
AttributeError: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
Exception in device=TPU:6: module 'torch_xla.core.xla_model' has no attribute 'rendezvous'
```
However, using the minimal code below provided in the MNIST on TPU notebook resolves the error.
```
VERSION = "20200325"  #@param ["1.5" , "20200325", "nightly"]
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION
```

- PyTorch Version (e.g., 1.0): 1.4.0a0+c272758
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Any other relevant information: Colab TPU runtime

**Comment by Borda** [comment]
@Alikerin mind try some new XLA version?
```
VERSION = "20200325"  #@param ["1.5" , "20200610", "nightly"]
```
I was testing this and worked for me https://github.com/PyTorchLightning/pytorch-lightning/pull/2094#issuecomment-644330374

**Comment by Borda** [comment]
@lezwon mind have a look ^^

**Comment by lezwon** [comment]
@Alikerin I tried the colab notebook. I am not receiving the error. Could you try again with an updated XLA version as @Borda suggested? If you still receive the error, do make a copy of the notebook and share it.

**Comment by Borda** [comment]
@Alikerin feel free to reopen if the issue holds... :rabbit:
