### ISSUE TITLE
Bug in GAN example

### ISSUE THREAD

**Issue by ternaus** [PyTorchLightning/pytorch-lightning#2009]
Bug in https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/generative_adversarial_net.py

When I run `python generative_adversarial_net.py `

I get
```
Traceback (most recent call last):
  File "generative_adversarial_net.py", line 218, in <module>
    main(hparams)
  File "generative_adversarial_net.py", line 192, in main
    model = GAN(hparams)
  File "generative_adversarial_net.py", line 90, in __init__
    self.generator = Generator(latent_dim=self.latent_dim, img_shape=mnist_shape)
  File "generative_adversarial_net.py", line 39, in __init__
    *block(latent_dim, 128, normalize=False),
  File "generative_adversarial_net.py", line 32, in block
    layers = [nn.Linear(in_feat, out_feat)]
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 72, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new(): argument 'size' must be tuple of ints, but found element of type Namespace at pos 2

```

**Comment by rohitgr7** [comment]
Replace with `model = GAN(**vars(hparams))` [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/fdbbe968256f6c68a5dbb840a2004b77a618ef61/pl_examples/domain_templates/generative_adversarial_net.py#L192).

**Comment by williamFalcon** [comment]
@ternaus @rohitgr7 mind submitting a PR to fix? :)

**Comment by ternaus** [comment]
Looks like the fix was merged.
