### ISSUE TITLE
[hparams] save_hyperparameters doesn't save kwargs

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#2188]
## ❓ Questions and Help

when I use hyperparemeters like docs:
```
class LitMNIST(LightningModule):

    def __init__(self, layer_1_dim=128, learning_rate=1e-2, **kwargs):
        super().__init__()
        # call this to save (layer_1_dim=128, learning_rate=1e-4) to the checkpoint
        self.save_hyperparameters()

```
model checkpoint doesn't save args in kwargs. But kwargs is important. Args such as `num_frames, img_size, img_std ...` must be used in creating `dataloader`, but it will be tedious if writes them in `__init__` explicitly .  it can make code clean if hides them in `kwargs`. 

Before I use `hparams`, it's ok. But now it's not recommended to use `hparams`,  is there any good idea to  deal with this problem?

**Comment by xiadingZ** [comment]
if don't use hparams, it will put all args of `model, dataset, dataloader...` if a `LightnModule`' s `__init__` method, and `save_hyperparameters ` doesn't save args in `kwargs`. It this really a good idea?

**Comment by Borda** [comment]
Could you please share your model example?

**Comment by xiadingZ** [comment]
> Could you please share your model example?

```
class LitMNIST(LightningModule):

    def __init__(self, layer_1_dim=128, learning_rate=1e-2, **kwargs):
        super().__init__()
        # call this to save (layer_1_dim=128, learning_rate=1e-4) to the checkpoint
        self.save_hyperparameters()
        self.kwargs = kwargs
        ...
    
    def train_dataloader(self):
        img_size = self.kwargs['img_size']
        ...
```

I can train this model, but when I load from checkpoint, it says kwargs hasn't `img_size`

**Comment by Borda** [comment]
> I can train this model, but when I load from checkpoint, it says kwargs hasn't `img_size`

I see, we need to ignore `kwargs` from the model hparams saving...

**Comment by s-rog** [comment]
```
Traceback (most recent call last):
  File "./training.py", line 101, in <module>
    main(hparam_trial)
  File "./training.py", line 86, in main
    model = module(hparams, fold_train, fold_val, data_dir+img_dir)
  File "../main/module.py", line 18, in __init__
    self.hparams = hparams
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 638, in __setattr__
    object.__setattr__(self, name, value)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 1695, in hparams
    self.save_hyperparameters(hp, frame=inspect.currentframe().f_back.f_back)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 1662, in save_hyperparameters
    cand_names = [k for k, v in init_args.items() if v == hp]
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 1662, in <listcomp>
    cand_names = [k for k, v in init_args.items() if v == hp]
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

I'm guessing this is why 0.8.0 causes this error, it's trying to save all args (including dataframes in my case) outside of hparams?
