### ISSUE TITLE
OmegaConf/hydra error unsupported `0.8.0rc2`

### ISSUE THREAD

**Issue by sudarshan85** [PyTorchLightning/pytorch-lightning#2197]
Hi,

I am using Hydra to setup my configurations variables for my trainer and model parameters. I'm using PL version `0.8.0rc2`. When I pass the params to my PL module and set the passed params to `self.hparams`, I get the following error:

```
ValueError: Unsupported config type of <class 'omegaconf.dictconfig.DictConfig'>.
```

I could add more code if that will help.
@Borda

**Comment by Borda** [comment]
@sudarshan85 mind pass a minimal example to reproduce?

**Comment by sudarshan85** [comment]
```
#!/usr/bin/env python

import torch
from torch import nn
from torch.nn import functional as F

from argparse import Namespace
from omegaconf import OmegaConf

from pytorch_lightning.core.lightning import LightningModule

class TestModel(LightningModule):
  def __init__(self, hparams):
    super(TestModel, self).__init__()
    self.hparams = hparams
    self.out = nn.Linear(hparams.size,1)
    
  def forward(self, x):
    return self.out(x)
    

if __name__=='__main__':
  hparams = OmegaConf.create({'size': 3})
#   hparams = Namespace(
#     size=3
#   )
  
  model = TestModel(hparams)
  print(model(torch.rand(hparams.size)))
```
When using `Namespace` from `argparse`, there is no error and its able to print the out value. But when using OmegaConf object, we get the following error:

```
Traceback (most recent call last):
  File "./omega_bug.py", line 28, in <module>    model = TestModel(hparams)  File "./omega_bug.py", line 15, in __init__    self.hparams = hparams
  File "/net/vaosl01/opt/NFS/su0/miniconda3/envs/tfool/lib/python3.7/site-packages/torch/nn/modules/module.py", line 638, in __setattr__
    object.__setattr__(self, name, value)  File "/net/vaosl01/opt/NFS/su0/miniconda3/envs/tfool/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1680, in hparams
    self.save_hyperparameters(hp, frame=inspect.currentframe().f_back.f_back)  File "/net/vaosl01/opt/NFS/su0/miniconda3/envs/tfool/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1655, in save_hyperparameters    self._set_hparams(hp)  File "/net/vaosl01/opt/NFS/su0/miniconda3/envs/tfool/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1665, in _set_hparams    raise ValueError(f'Unsupported config type of {type(hp)}.')
ValueError: Unsupported config type of <class 'omegaconf.dictconfig.DictConfig'>.
```

**Comment by anthonytec2** [comment]
#2139

**Comment by Borda** [comment]
feel free to reopen if needed :rabbit: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/c52497e85933abf0230800a3461a3053fc94101b/requirements/extra.txt#L12

**Comment by qiuhuaqi** [comment]
It seems the current Hydra version `0.11.3` doesn't support `omegaconf=2.0.0`?
I got this error when simply trying to `import hydra`

```
...
     5 from abc import abstractmethod
      6 import six
----> 7 from omegaconf import DictConfig, ListConfig, Config, MissingMandatoryValue
      8 
      9 from hydra.plugins import Plugin
ImportError: cannot import name 'Config'
```

Am I missing something? 
What's a good way to pass `DictConfig` object to Lightning's `self.hparams`?
