### ISSUE TITLE
Can't use None (anymore) in checkpoint_callback

### ISSUE THREAD

**Issue by s-rog** [PyTorchLightning/pytorch-lightning#2547]
## 🐛 Bug
using None in checkpoint_callback now errors out

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 562, in ddp_train
    q.put(self.checkpoint_callback.best_model_path)
AttributeError: 'NoneType' object has no attribute 'best_model_path'
```

### To Reproduce
`trainer = Trainer(checkpoint_callback=None)`

Ran into this issue from upgrading to masters, was using masters from a few commits ago before

Edit: `False` casuses the same error as well

**Comment by s-rog** [comment]
@williamFalcon I saw that this issue was mentioned and supposedly fixed in the merge, but I just tested with master and I'm still getting the same error

**Comment by s-rog** [comment]
```
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1018, in fit
    results = self.accelerator_backend.teardown(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/accelerator_backends/ddp_spawn_backend.py", line 52, in teardown
    self.trainer.checkpoint_callback.best_model_path = best_path
AttributeError: 'NoneType' object has no attribute 'best_model_path'
```
This is the error I get when I set `checkpoint_callback` to false on master (0.9.0rc6)

**Comment by awaelchli** [comment]
@s-rog I think your proposed fix is good. In case user sets checkpoint_callback to None, we should not try to set a path there.

**Comment by awaelchli** [comment]
Would you like to submit this in a PR?
