### ISSUE TITLE
Model Parallelism with (Distributed) Data Parallelism

### ISSUE THREAD

**Issue by sunwoo-kim** [PyTorchLightning/pytorch-lightning#2618]
## 🚀 Feature

As per title, this is something that PyTorch supports but PyTorchLightning does not.

### Motivation

A lot of the time, the entire model does not fit into a single GPU. It would be nice to share the load between multiple GPUs.

### Pitch

Allow a point the model to split into two or more parts, and Pytorch Lightning will automatically allocate the available gpus.

**Comment by rohitgr7** [comment]
Something like this? https://youtu.be/TM_jRrXYXxc?t=1904

**Comment by sunwoo-kim** [comment]
Any update on this issue?

**Comment by rohitgr7** [comment]
It's not supported out of the box yet, but still, you can do that by manually handling the process of transferring the model and input tensors to the device and using CPU backend in Trainer.

**Comment by george-gca** [comment]
@rohitgr7 how should I handle the gpu devices in my model? I mean, should I manually parse the args.gpus from Trainer in my model, to find out exactly which gpus should I use? Also, why should I use CPU backend in Trainer?

**Comment by rohitgr7** [comment]
> Also, why should I use CPU backend in Trainer?

@george-gca Currently, model parallelism is not supported out of the box by lightning so if you assign a GPU in Trainer, it will put the whole model on that device which is not actually model parallelism.

**Comment by george-gca** [comment]
Ok, I tried this @rohitgr7, set gpus=0, then manually move my model parts to each gpu, but got the following error:
```
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    main(Model, args)
  File "train.py", line 268, in main
    trainer.fit(model, dataset)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 440, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 45, in train
    self.trainer.train_loop.setup_training(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 153, in setup_training
    ref_model.summarize(mode=self.trainer.weights_summary)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1289, in summarize
    model_summary = ModelSummary(self, mode=mode)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/memory.py", line 174, in __init__
    self._layer_summary = self.summarize()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/memory.py", line 211, in summarize
    self._forward_example_input()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/memory.py", line 236, in _forward_example_input
    model(input_)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/models/srcaps2.py", line 416, in forward
    caps_block_result = caps_block(caps_block_result)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/models/srcaps2.py", line 260, in forward
    capsule = caps(capsule) + capsule
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/models/srcaps2.py", line 121, in forward
    stride=self.stride, padding=self.padding)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

any advice?
