### ISSUE TITLE
Apex with auto lr finder fails

### ISSUE THREAD

**Issue by michal2409** [PyTorchLightning/pytorch-lightning#2642]
Hi! I have this error when using together flags `precision=16, auto_lr_find=True` in `Trainer` . The error occurs when learning rate finder finish and before training starts. I guess it can happen because of calling `amp.initialize` for already initialized model i.e the first one it is called when for auto_lr_find and then the second one for the same model for training initialization.

```
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    trainer.fit(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1003, in fit
    results = self.single_gpu_train(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 182, in single_gpu_train
    model, optimizers = model.configure_apex(amp, model, self.optimizers, self.amp_level)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 1006, in configure_apex
    model, optimizers = amp.initialize(model, optimizers, opt_level=amp_level)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/frontend.py", line 358, in initialize
    return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 171, in _initialize
    check_params_fp32(models)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 87, in check_params_fp32
    name, param.type()))
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 32, in warn_or_err
    raise RuntimeError(msg)
RuntimeError: Found param unet.input_block.conv1.0.weight with type torch.cuda.HalfTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you do not need to call .half() on your model
before passing it, no matter what optimization level you choose.
```

**Comment by fablos** [comment]
Hi, experiencing similar issue when I call `trainer.test()` no matter how `auto_lr_find` is set: 

`
RuntimeError: Found param encoder.embedding.weight with type torch.cuda.HalfTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you do not need to call .half() on your model
before passing it, no matter what optimization level you choose.
`

Training phase runs smoothly

**Comment by edenlightning** [comment]
Same issue as https://github.com/PyTorchLightning/pytorch-lightning/issues/2655
