### ISSUE TITLE
Can't find PyTorch 1.6

### ISSUE THREAD

**Issue by zhenhuahu** [PyTorchLightning/pytorch-lightning#2697]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### I tried to use native amp and _[the document](https://pytorch-lightning.readthedocs.io/en/latest/apex.html#native-torch)_ says I need to have PyTorch 1.6. I went to [PyTorch's website](https://pytorch.org/) and can only find 1.5.1. I tried to install the Preview (Nightly) the error popped up:

torchvision 0.8.0 has requirement torch ==1.7.0 but you'll have torch 1.5.1 which is incompatible.

Can anyone tell me why? Thanks.

The error massages are:
ERROR: torchvision 0.8.0.dev20200724+cu101 has requirement torch==1.7.0.dev20200724+cu101, but you'll have torch 1.5.1 which is incompatible.
Traceback (most recent call last):
  File "pl_fuse_train_apex_1node_8gpu_16bit_amp_O2.py", line 7, in <module>
    from data.load_fuse_data import LoadFuseData
  File "/newDisk/users/huzhenhua/fuse_net/data/load_fuse_data.py", line 9, in <module>
    from data import my_transforms
  File "/newDisk/users/huzhenhua/fuse_net/data/my_transforms.py", line 11, in <module>
    from torchvision.transforms import transforms
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py", line 42, in <module>
    @torch.jit._script_if_tracing
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]:Linux
 - Packaging [e.g. pip, conda]: pip
 - Version [e.g. 0.5.2.1]

**Comment by zhenhuahu** [comment]
Already installed them in Docker. Turned out I need to specify wheels in that [html](https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html). Thanks.
