### ISSUE TITLE
Speed Drastically Decrease Under Horovod

### ISSUE THREAD

**Issue by KeeeeiZ** [PyTorchLightning/pytorch-lightning#2771]
## 🐛 Bug

If the backend is set to `horovod`, training speed will drop drastically.

### To Reproduce

I run the training job in docker, and the Dockerfile is shown below:

```Dockerfile
FROM nvidia/cuda:10.1-devel-ubuntu18.04

# TensorFlow version is tightly coupled to CUDA and cuDNN so it should be selected carefully
ENV TENSORFLOW_VERSION=2.1.0
ENV PYTORCH_VERSION=1.5.1
ENV TORCHVISION_VERSION=0.5.0
ENV CUDNN_VERSION=7.6.5.32-1+cuda10.1
ENV NCCL_VERSION=2.4.8-1+cuda10.1
ENV MXNET_VERSION=1.6.0

# Python 3.6 is supported by Ubuntu Bionic out of the box
ARG python=3.6
ENV PYTHON_VERSION=${python}

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        g++-4.8 \
        git \
        curl \
        vim \
        wget \
        ca-certificates \
        libcudnn7=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
        libpng-dev \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev \
        python${PYTHON_VERSION}-distutils \
        librdmacm1 \
        libibverbs1 \
        ibverbs-providers

RUN ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

# Install TensorFlow, Keras, PyTorch and MXNet
RUN pip install future typing
RUN pip install numpy \
        tensorflow-gpu==${TENSORFLOW_VERSION} \
        h5py
        # keras \

# RUN pip install https://download.pytorch.org/whl/cu101/torch-${PYTORCH_VERSION}-$(python -c "import wheel.pep425tags as w; print('-'.join(w.get_supported(None)[0][:-1]))")-linux_x86_64.whl \
# https://download.pytorch.org/whl/cu101/torchvision-${TORCHVISION_VERSION}-$(python -c "import wheel.pep425tags as w; print('-'.join(w.get_supported(None)[0][:-1]))")-linux_x86_64.whl
RUN pip install mxnet-cu101==${MXNET_VERSION}
COPY backbones backbones
RUN cd backbones && pip install -r requirements.txt


# Install Open MPI
RUN mkdir /tmp/openmpi && \
    cd /tmp/openmpi && \
    wget https://www.open-mpi.org/software/ompi/v4.0/downloads/openmpi-4.0.0.tar.gz && \
    tar zxf openmpi-4.0.0.tar.gz && \
    cd openmpi-4.0.0 && \
    ./configure --enable-orterun-prefix-by-default && \
    make -j $(nproc) all && \
    make install && \
    ldconfig && \
    rm -rf /tmp/openmpi

# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 \
         pip install --no-cache-dir horovod && \
    ldconfig

# Install OpenSSH for MPI to communicate between containers
RUN apt-get install -y --no-install-recommends openssh-client openssh-server && \
    mkdir -p /var/run/sshd

# Allow OpenSSH to talk to containers without asking for confirmation
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

# Download examples
RUN apt-get install -y --no-install-recommends subversion && \
    svn checkout https://github.com/horovod/horovod/trunk/examples && \
    rm -rf /examples/.svn

WORKDIR "/examples"
```
My GPUs include 4 NVIDIA P100.

My training script is in `/backbones`, and if I run the script below, it trains smoothly:

```shell
export CUDA_VISIBLE_DEVICES=0,1,2,3
python backbones/tasks/mask_lm/trainer.py \
--data_dirs $DATA_DIR \
--bert_config_file $CONFIG_FILE \
--vocab_file $VOCAB_FILE \
--max_epochs=30 \
--gpus=1 \
--progress_bar_refresh_rate 1 \
--checkpoint_callback=True \
--val_check_interval 1.0 \
--default_root_dir=$OUTPUT_DIR \
--gradient_clip_val=5.0 \
--batch_size=32 \
--distributed_backend=ddp \
--accumulate_grad_batches 16 \
--lr 1e-4 \
--weight_decay 0.01 \
--workers 1 \
--max_length 128
```

If I run the script below which is using `horovod`, the speed will be about 1/3 of the one using ddp:
```shell
export CUDA_VISIBLE_DEVICES=0,1,2,3
horovodrun -np 4 python backbones/tasks/mask_lm/trainer.py \
--data_dirs $DATA_DIR \
--bert_config_file $CONFIG_FILE \
--vocab_file $VOCAB_FILE \
--max_epochs=30 \
--progress_bar_refresh_rate 1 \
--checkpoint_callback=True \
--val_check_interval 1.0 \
--default_root_dir=$OUTPUT_DIR \
--gradient_clip_val=5.0 \
--batch_size=32 \
--accumulate_grad_batches 16 \
--lr 1e-4 \
--weight_decay 0.01 \
--workers 1 \
--max_length 128 \
--distributed_backend horovod
```

### Expected behavior

The training speed under `horovod` will at least be around the one under `ddp`, not 1/3 or 1/4.

**Comment by Borda** [comment]
@tgaddair mind check this one?

**Comment by tgaddair** [comment]
Hey @KeeeeiZ, can you run `horovodrun --check-build` and provide the output here?  My guess is that you're not using NCCL.

Note that `HOROVOD_GPU_OPERATIONS=NCCL` is unreleased (coming in v0.20.0).  For now, you should use `HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL` instead.  That is likely the source of the issue.

**Comment by Borda** [comment]
How about using PL docker image - https://hub.docker.com/repository/docker/pytorchlightning/pytorch_lightning
with all already installed libraries...

**Comment by KeeeeiZ** [comment]
> Hey @KeeeeiZ, can you run `horovodrun --check-build` and provide the output here? My guess is that you're not using NCCL.
> 
> Note that `HOROVOD_GPU_OPERATIONS=NCCL` is unreleased (coming in v0.20.0). For now, you should use `HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL` instead. That is likely the source of the issue.

The output is as below:
```
Horovod v0.19.5:

Available Frameworks:
    [X] TensorFlow
    [X] PyTorch
    [X] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo
```
Just like what you mentioned, `NCCL` is not available.

I rebuilt the docker image with `HOROVOD_GPU_ALLREDUCE=NCCL` and `HOROVOD_GPU_BROADCAST=NCCL`, now the performance is as expected. Thanks a lot!

But since my final goal is to run horovod distributedly, I also tried the training script on two machines with a total of 8 GPUs according to the instructions on 
https://github.com/horovod/horovod#running-horovod. The script works fine if the docker image is not built with `HOROVOD_GPU_ALLREDUCE=NCCL` and `HOROVOD_GPU_BROADCAST=NCCL`. After I rebuilt the image, the script gave the log below, and I am not sure if the problem is due to configs of  horovod or pytorch-lighting:

```
[1,6]<stderr>:Traceback (most recent call last):
[1,6]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 224, in <module>
[1,6]<stderr>:    main()
[1,6]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 220, in main
[1,6]<stderr>:    trainer.fit(model)
[1,6]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,6]<stderr>:    results = self.horovod_train(model)
[1,6]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,6]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,6]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,6]<stderr>:    synchronize(handle)
[1,6]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,6]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,6]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,7]<stderr>:Traceback (most recent call last):
[1,7]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 224, in <module>
[1,7]<stderr>:    main()
[1,7]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 220, in main
[1,7]<stderr>:    trainer.fit(model)
[1,7]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,7]<stderr>:    results = self.horovod_train(model)
[1,7]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,7]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,7]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,7]<stderr>:    synchronize(handle)
[1,7]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,7]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,7]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 219, in <module>
[1,3]<stderr>:    main()
[1,3]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 215, in main
[1,3]<stderr>:    trainer.fit(model)
[1,3]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,3]<stderr>:    results = self.horovod_train(model)
[1,3]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,3]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,3]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,3]<stderr>:    synchronize(handle)
[1,3]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,3]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,3]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 219, in <module>
[1,0]<stderr>:    main()
[1,0]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 215, in main
[1,0]<stderr>:    trainer.fit(model)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,0]<stderr>:    results = self.horovod_train(model)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,0]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,0]<stderr>:    synchronize(handle)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,0]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,0]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 219, in <module>
[1,2]<stderr>:    main()
[1,2]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 215, in main
[1,2]<stderr>:    trainer.fit(model)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,2]<stderr>:    results = self.horovod_train(model)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,2]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,2]<stderr>:    synchronize(handle)
[1,2]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,2]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,2]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 219, in <module>
[1,1]<stderr>:    main()
[1,1]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 215, in main
[1,1]<stderr>:    trainer.fit(model)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,1]<stderr>:    results = self.horovod_train(model)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,1]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,1]<stderr>:    synchronize(handle)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,1]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,1]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,5]<stderr>:Traceback (most recent call last):
[1,5]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 224, in <module>
[1,5]<stderr>:    main()
[1,5]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 220, in main
[1,5]<stderr>:    trainer.fit(model)
[1,5]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,5]<stderr>:    results = self.horovod_train(model)
[1,5]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,5]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,5]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,5]<stderr>:    synchronize(handle)
[1,5]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,5]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,5]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,4]<stderr>:Traceback (most recent call last):
[1,4]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 224, in <module>
[1,4]<stderr>:    main()
[1,4]<stderr>:  File "backbones/tasks/mask_lm/trainer.py", line 220, in main
[1,4]<stderr>:    trainer.fit(model)
[1,4]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1000, in fit
[1,4]<stderr>:    results = self.horovod_train(model)
[1,4]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 308, in horovod_train
[1,4]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
[1,4]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 481, in broadcast_parameters
[1,4]<stderr>:    synchronize(handle)
[1,4]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 505, in synchronize
[1,4]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,4]<stderr>:RuntimeError: Mismatched BROADCAST CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[28623,1],6]
  Exit code:    1
```

My start up command is:
`horovodrun -np 8 -H ip1:4,ip2:4 -p 12345 python backbones/tasks/mask_lm/trainer.py`
and the newer Dockerfile is just the old one with two new lines in the beginning:
```Dockerfile
ENV HOROVOD_GPU_ALLREDUCE=NCCL
ENV HOROVOD_GPU_BROADCAST=NCCL
```

**Comment by KeeeeiZ** [comment]
> How about using PL docker image - https://hub.docker.com/repository/docker/pytorchlightning/pytorch_lightning
> with all already installed libraries...

Thanks for the link. Is this image a superset of the one on https://hub.docker.com/r/horovod/horovod ? I am not sure what major differences it would make if I rebuild my image with just changing the beginning of the Dockerfile from `FROM nvidia/cuda:10.1-devel-ubuntu18.04` to `FROM pytorchlightning/pytorch_lightning`.

**Comment by Borda** [comment]
it is not based on Horovod docker image but CUDA and installed Horovod together with other Pl requirements

**Comment by tgaddair** [comment]
Hey @KeeeeiZ, is it possible that one of the hosts is running with the new image, while the other is running with the old image?  That error message suggests that one machine is using NCCL and another is not.

**Comment by KeeeeiZ** [comment]
> Hey @KeeeeiZ, is it possible that one of the hosts is running with the new image, while the other is running with the old image? That error message suggests that one machine is using NCCL and another is not.

Thanks for the tip @tgaddair  ! My training script is now running without bugs. But the log below shows that inifiniband device is not found. (My primary host machine's name is translation 1)
```
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO Bootstrap : Using [0]lo:127.0.0.1<0>
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO NET/IB : No device found.
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
[1,0]<stdout>:NCCL version 2.4.8+cuda10.1
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO Bootstrap : Using [0]lo:127.0.0.1<0>
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO Bootstrap : Using [0]lo:127.0.0.1<0>
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO Bootstrap : Using [0]lo:127.0.0.1<0>
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO NET/IB : No device found.
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO NET/IB : No device found.
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO NET/IB : No device found.
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO Setting affinity for GPU 2 to 0fff
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO Setting affinity for GPU 1 to 0fff
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO Setting affinity for GPU 3 to 0fff
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO Channel 00 :    0   1   2   3
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO Ring 00 : 3[3] -> 0[0] via direct shared memory
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO Ring 00 : 1[1] -> 2[2] via direct shared memory
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via direct shared memory
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO Ring 00 : 2[2] -> 3[3] via direct shared memory
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO Using 256 threads, Min Comp Cap 6, Trees disabled
[1,3]<stdout>:translation-1:1749:1957 [3] NCCL INFO comm 0x7fc76c2fb0f0 rank 3 nranks 4 cudaDev 3 nvmlDev 2 - Init COMPLETE
[1,1]<stdout>:translation-1:1747:1958 [1] NCCL INFO comm 0x7f24b82faf90 rank 1 nranks 4 cudaDev 1 nvmlDev 0 - Init COMPLETE
[1,0]<stdout>:translation-1:1746:1951 [0] NCCL INFO comm 0x7faefc3097f0 rank 0 nranks 4 cudaDev 0 nvmlDev 3 - Init COMPLETE
[1,2]<stdout>:translation-1:1748:1959 [2] NCCL INFO comm 0x7f04602fb010 rank 2 nranks 4 cudaDev 2 nvmlDev 1 - Init COMPLETE
```

My guess is I need to configure IB manually and the following instruction is what I found after searching since my system is Ubuntu.
https://techcommunity.microsoft.com/t5/azure-compute/configuring-infiniband-for-ubuntu-hpc-and-gpu-vms/ba-p/1221351

I am not sure I need to install all this stuff both inside docker and on the host machine, or one of them. 

I have read your replies under other questions and thought you are quite familiar with NCCL, horovod, pytorch-lighting and so on. So if it is OK, I will just continue to ask here. Thanks a lot.

**Comment by tgaddair** [comment]
Hey @KeeeeiZ, have you gone through the [nv_peer_memory](https://github.com/Mellanox/nv_peer_memory) walkthrough to install the kernel module for GPUDirect?  This should be installed in the host, not the container.  That should be sufficient to make use of your Infiniband card for RDMA in NCCL.

**Comment by KeeeeiZ** [comment]
> Hey @KeeeeiZ, have you gone through the [nv_peer_memory](https://github.com/Mellanox/nv_peer_memory) walkthrough to install the kernel module for GPUDirect? This should be installed in the host, not the container. That should be sufficient to make use of your Infiniband card for RDMA in NCCL.

I finally managed to start the script with all the environmental requirements including IB interfaces set. But, when I try to run the task on **2** machines, I got infinitely stuck with the log
```
...
[1,0]<stdout>:translation-0:4325:4536 [0] NCCL INFO Ring 00 : 4 -> 0 [receive] via NET/IB/0
[1,1]<stdout>:translation-0:4326:4538 [1] NCCL INFO comm 0x7fd5bc3124c0 rank 1 nranks 8 cudaDev 1 nvmlDev 1 - Init COMPLETE
[1,4]<stdout>:translation-1:5597:5808 [0] NCCL INFO Ring 00 : 0 -> 4 [receive] via NET/IB/0
[1,0]<stdout>:translation-0:4325:4536 [0] NCCL INFO Ring 00 : 0 -> 4 [send] via NET/IB/0
[1,0]<stdout>:translation-0:4325:4536 [0] NCCL INFO Trees [0] -1->0->1/4/-1
[1,0]<stdout>:translation-0:4325:4536 [0] NCCL INFO Using 256 threads, Min Comp Cap 6, Trees enabled up to size 149999
[1,4]<stdout>:translation-1:5597:5808 [0] NCCL INFO Trees [0] 0->4->5/-1/-1
[1,0]<stdout>:translation-0:4325:4536 [0] NCCL INFO comm 0x7effcc34dd10 rank 0 nranks 8 cudaDev 0 nvmlDev 0 - Init COMPLETE
[1,4]<stdout>:translation-1:5597:5808 [0] NCCL INFO comm 0x7fbf40322de0 rank 4 nranks 8 cudaDev 0 nvmlDev 1 - Init COMPLETE
[1,0]<stdout>:translation-0:4325:4536 [0] NCCL INFO Launch mode Parallel
```
I guess you might be familiar with the line `Launch mode Parallel` since I found other issues with the same problem.

My starting script is `NCCL_PROTO=^LL NCCL_DEBUG=INFO NCCL_SOCKET_IFNAME=eth0 NCCL_P2P_DISABLE=1 /bin/bash backbones/tasks/mask_lm/scripts/horovod_run_gpu.sh`(my IB interface is eth1 on both of my machines)

I have tried many combinations of `NCCL_xxx` configs but it does not work as the other issues I saw.
