### ISSUE TITLE
Supporting TPU pods

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#3058]
More context: https://cloud.google.com/tpu/docs/training-on-tpu-pods

**Comment by Borda** [comment]
@edenafek what is the point here, add some implementation or extend docs?
cc: @zcain117 mind have a look :]

**Comment by zcain117** [comment]
I've been doing some experiments this week with Pytorch Lightning + TPU pods.

I think I've got it mostly working: I am able to train successfully on a v3-32 and the model converges and number of batches looks correct, speed is much faster than v3-8.

However at the end of training I am running into issues with checkpoint saving. With a v3-32, there are 4 VMs. All 4 VMs are able to finish training and I see checkpoints written to disk.

1 VM (the main VM where I execute the start command) has no issues and I see:
```
2020-10-07 21:07:17 10.164.0.32 [0] Saving latest checkpoint..
Epoch 9: 100%|##########| 118/118 [00:06<00:00, 18.31it/s, loss=1.090, v_num=1]
2020-10-07 21:07:17 10.164.0.32 [0] /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: cleaning up ddp environment...
2020-10-07 21:07:17 10.164.0.32 [0]   warnings.warn(*args, **kwargs)
```

And that's the end of its print statements.

For the other 3 VMs, there is an error printed out (see next comment) but I still see checkpoints on disk.

In general, how would you like to handle checkpoints?  Right now it seems like Pytorch Lightning saves checkpoints for the best epoch, however in distributed training, I think each VM is making the decision of "best epoch" based on its own slice of the training data, so each VM might choose a different epoch as "best". How is this handled for the distributed GPU case?

**Comment by zcain117** [comment]
Error for 3 of the 4 VMs after training is done:

```
2020-10-06 23:23:29 10.164.0.24 [0] docker: network "host" is specified multiple times.
2020-10-06 23:23:29 10.164.0.24 [0] See 'docker run --help'.
2020-10-06 23:23:30 10.164.0.29 [1] docker: network "host" is specified multiple times.
2020-10-06 23:23:30 10.164.0.29 [1] See 'docker run --help'.
Process Process-1:
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py", line 388, in _run_cmd
    self._start_run(script_map)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py", line 383, in _start_run
    len(script_map), _run_script, script_map.values(), script_map.keys())
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/utils/utils.py", line 293, in parallel_work
    return [res for res in results]  # Iterating to re-raise any exceptions
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/utils/utils.py", line 293, in <listcomp>
    return [res for res in results]  # Iterating to re-raise any exceptions
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py", line 369, in _run_script
    'Remote command exitted with code: {}'.format(exit_code))
RuntimeError: Remote command exitted with code: 125
I am interpreting the "docker: network" message as an error, so I removed that flag and tried: python -m torch_xla.distributed.xla_dist --tpu=$TPU_NAME --docker-image=gcr.io/tpu-pytorch/xla:nightly_3.6 --env ANY_OTHER=ENV_VAR --docker-run-flag="--shm-size=16G" --docker-run-flag="-v ~/run_pl.sh:/tmp/run_pl.sh" --docker-run-flag="-v ~/pl.py:/tmp/pl.py" -- bash /tmp/run_pl.sh 2020-10-06 23:24:27 [] Command to distribute: "bash" "/tmp/run_pl.sh"

This crashed with: docker: Error response from daemon: create ~/run_pl.sh: " ~/run_pl.sh" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

Next I tried: python -m torch_xla.distributed.xla_dist --tpu=$TPU_NAME --docker-image=gcr.io/tpu-pytorch/xla:nightly_3.6 --env ANY_OTHER=ENV_VAR --docker-run-flag="--shm-size=16G" --docker-run-flag="-v=/home/zcain/run_pl.sh:/tmp/run_pl.sh" --docker-run-flag="-v=/home/zcain/pl.py:/tmp/pl.py" -- bash /tmp/run_pl.sh

This time, training succeeds but then during the checkpoint saving after training, there is a crash:

2020-10-06 23:31:05 10.164.0.27 [2] Traceback (most recent call last):
2020-10-06 23:31:05 10.164.0.27 [2]   File "/tmp/pl.py", line 57, in <module>
2020-10-06 23:31:05 10.164.0.27 [2]     trainer.fit(model, mnist_train, mnist_val)
2020-10-06 23:31:05 10.164.0.27 [2]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
2020-10-06 23:31:05 10.164.0.27 [2]     result = fn(self, *args, **kwargs)
2020-10-06 23:31:05 10.164.0.27 [2]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1079, in fit
2020-10-06 23:31:05 10.164.0.27 [2]     self.accelerator_backend.teardown(model)
2020-10-06 23:31:05 10.164.0.27 [2]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/accelerators/tpu_backend.py", line 67, in teardown
2020-10-06 23:31:05 10.164.0.27 [2]     ckpt = torch.load(last_path, map_location=lambda storage, loc: storage)
2020-10-06 23:31:05 10.164.0.27 [2]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
2020-10-06 23:31:05 10.164.0.27 [2]     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
2020-10-06 23:31:05 10.164.0.27 [2]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 853, in _load
2020-10-06 23:31:05 10.164.0.27 [2]     result = unpickler.load()
2020-10-06 23:31:05 10.164.0.27 [2]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/_utils.py", line 177, in _rebuild_xla_tensor
2020-10-06 23:31:05 10.164.0.27 [2]     tensor = torch.from_numpy(data).to(dtype=dtype, device=device)
2020-10-06 23:31:05 10.164.0.27 [2] RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:245 : Check failed: default_device_target != options_.global_device_map.end() 
2020-10-06 23:31:05 10.164.0.27 [2] *** Begin stack trace ***
2020-10-06 23:31:05 10.164.0.27 [2]     tensorflow::CurrentStackTrace()
2020-10-06 23:31:05 10.164.0.27 [2]     xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
2020-10-06 23:31:05 10.164.0.27 [2]     xla::ComputationClient::Create()
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     xla::ComputationClient::Get()
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     torch_xla::bridge::AtenDeviceToXlaDevice(c10::Device const&)
2020-10-06 23:31:05 10.164.0.27 [2]     torch_xla::bridge::GetXlaDevice(c10::optional<c10::Device> const&)
2020-10-06 23:31:05 10.164.0.27 [2]     torch_xla::AtenXlaType::empty(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)
2020-10-06 23:31:05 10.164.0.27 [2]     torch_xla::AtenXlaType::empty_strided(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)
2020-10-06 23:31:05 10.164.0.27 [2]     c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool> > >, at::Tensor (c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)>::call(c10::OperatorKernel*, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     at::empty_strided(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)
2020-10-06 23:31:05 10.164.0.27 [2]     at::empty_strided(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)
2020-10-06 23:31:05 10.164.0.27 [2]     at::empty_strided(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&)
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     at::native::to(at::Tensor const&, c10::Device, c10::ScalarType, bool, bool, c10::optional<c10::MemoryFormat>)
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     at::Tensor::to(c10::Device, c10::ScalarType, bool, bool, c10::optional<c10::MemoryFormat>) const
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     _PyCFunction_FastCallDict
2020-10-06 23:31:05 10.164.0.27 [2]     _PyCFunction_FastCallKeywords
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     _PyEval_EvalFrameDefault
2020-10-06 23:31:05 10.164.0.27 [2]     PyEval_EvalCodeEx
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     PyObject_Call
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     _PyCFunction_FastCallDict
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     _PyEval_EvalFrameDefault
2020-10-06 23:31:05 10.164.0.27 [2]     PyEval_EvalCodeEx
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     PyObject_Call
2020-10-06 23:31:05 10.164.0.27 [2]     _PyEval_EvalFrameDefault
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     _PyEval_EvalFrameDefault
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     _PyEval_EvalFrameDefault
2020-10-06 23:31:05 10.164.0.27 [2]     PyEval_EvalCodeEx
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     PyObject_Call
2020-10-06 23:31:05 10.164.0.27 [2]     _PyEval_EvalFrameDefault
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     _PyEval_EvalFrameDefault
2020-10-06 23:31:05 10.164.0.27 [2]     PyEval_EvalCodeEx
2020-10-06 23:31:05 10.164.0.27 [2]     PyEval_EvalCode
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2]     PyRun_FileExFlags
2020-10-06 23:31:05 10.164.0.27 [2]     PyRun_SimpleFileExFlags
2020-10-06 23:31:05 10.164.0.27 [2]     Py_Main
2020-10-06 23:31:05 10.164.0.27 [2]     main
2020-10-06 23:31:05 10.164.0.27 [2]     __libc_start_main
2020-10-06 23:31:05 10.164.0.27 [2] 
2020-10-06 23:31:05 10.164.0.27 [2] *** End stack trace ***
2020-10-06 23:31:05 10.164.0.27 [2] 
Process Process-1:
```

**Comment by Borda** [comment]
well, we have opened a few TPU checkpointing issue and some PR in progress, not sure if it is this case...

**Comment by zcain117** [comment]
1. What should our goal be with saving checkpoints? To me it seems sufficient to save checkpoints from just the master VM. I don't think the user would want one copy of checkpoints from every VM, but maybe I am wrong
2. Right now the [`teardown` tries to load the model in the main process](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/accelerators/tpu_backend.py#L75). This probably doesn't make sense for the distributed training case, except for maybe the master VM. Is the purpose of `load` just to verify that the checkpoint is not corrupted?

**Comment by zcain117** [comment]
Just to update: it seems like something broke between 0.9.0 and 0.10.0 with regard to TPU pods

I tried a bunch of combinations of software versions:

- `pip install pytorch-lightning` (no version - I think this would result in 1.0.6) + pytorch/xla nightly_3.6 docker image + pytorch-nightly TPU = `Check failed: default_device_target != options_.global_device_map.end()` (see below)
- `pip install pytorch-lightning==0.10.0` + r1.7_3.6 docker image + pytorch-1.7 TPU = `Check failed: default_device_target != options_.global_device_map.end()` (see below)
- `pip install pytorch-lightning==0.10.0` + r1.6_3.6 docker image + pytorch-1.6 TPU = `Check failed: default_device_target != options_.global_device_map.end()` (see below)
- `pip install pytorch-lightning==0.9.0` + r1.7_3.6 docker image + pytorch-1.7 TPU = trains but fails saving model just like [above](https://github.com/PyTorchLightning/pytorch-lightning/issues/3058#issuecomment-705220359)
- `pip install pytorch-lightning==0.9.0` + r1.6_3.6 docker image + pytorch-1.6 TPU = trains but fails saving model just like [above](https://github.com/PyTorchLightning/pytorch-lightning/issues/3058#issuecomment-705220359)
- `pip install pytorch-lightning==0.9.0` + nightly_3.6 docker image + pytorch-nightly TPU = trains but fails saving model just [above](https://github.com/PyTorchLightning/pytorch-lightning/issues/3058#issuecomment-705220359)

More detail for the "see below":
```
2020-11-13 00:41:39 10.164.0.65 [1] Traceback (most recent call last):
2020-11-13 00:41:39 10.164.0.65 [1]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/utilities/xla_device_utils.py", line 30, in inner_f
2020-11-13 00:41:39 10.164.0.65 [1]     queue.put(func(*args, **kwargs))
2020-11-13 00:41:39 10.164.0.65 [1]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/utilities/xla_device_utils.py", line 81, in _is_device_tpu
2020-11-13 00:41:39 10.164.0.65 [1]     device = xm.xla_device()
2020-11-13 00:41:39 10.164.0.65 [1]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 231, in xla_device
2020-11-13 00:41:39 10.164.0.65 [1]     devkind=devkind if devkind is not None else None)
2020-11-13 00:41:39 10.164.0.65 [1]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 136, in get_xla_supported_devices
2020-11-13 00:41:39 10.164.0.65 [1]     xla_devices = _DEVICES.value
2020-11-13 00:41:39 10.164.0.65 [1]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/utils/utils.py", line 32, in value
2020-11-13 00:41:39 10.164.0.65 [1]     self._value = self._gen_fn()
2020-11-13 00:41:39 10.164.0.65 [1]   File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 18, in <lambda>
2020-11-13 00:41:39 10.164.0.65 [1]     _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
2020-11-13 00:41:39 10.164.0.65 [1] RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:245 : Check failed: default_device_target != options_.global_device_map.end() 
```

So the summary is:
- `pytorch-lightning==0.9.0` is pretty close to working, we just have to fix the crash when the non-master process tries to save weights.
- `pytorch-lightning==0.10.0` and above are not able to start training due to this crash that I don't understand

**Comment by kaushikb11** [comment]
@edenlightning @tchaton What is this regarding?
