### ISSUE TITLE
Early stopping fails on horovod with cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by undertherain** [PyTorchLightning/pytorch-lightning#3381]
## 🐛 Bug
When I do early stopping with horovod distributed training, it fails with `cannot unpack non-iterable NoneType object` in tqdm.
If fails only on some sets of training data. Also I see from the logs that early stopping was initiated only three times, while I'm training on 4 workers. 
This makes me feel like the problem is that one of the workers did not initiate early stopping - presumably because each worker decides not by averaged, but by local validation loss. 
```
        result = pl.EvalResult(early_stop_on=loss, checkpoint_on=loss)
        result.log("val_loss", loss, sync_dist=True)
```
As you can see I'm asking pytorch-lightning to average validation loss, but as was the case in my previous issue   #3338 , the problem seems to be related to earlystopping using another dict.
Here's the full error message

```
Epoch 7:   0% 0/8 [00:00<?, ?it/s, loss=0.480, v_num=50]Traceback (most recent call last):
  File "main.py", line 72, in <module>       
    main()
  File "main.py", line 68, in main
    trainer.fit(model, data_module)
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1016, in fit
    results = self.accelerator_backend.train()
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/horovod_backend.py", line 108, in train
    result = self.trainer.run_pretrain_routine(self.trainer.model)
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1237, in run_pretrain_routine
    self.train()
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 396, in train
    self.run_training_epoch()
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 484, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 832, in run_training_batch
    opt_closure_result = self.optimizer_closure(
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 1065, in optimizer_closure
    model_ref.backward(self, closure_loss, optimizer, opt_idx)
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/pytorch_lightning/core/hooks.py", line 312, in backward
    loss.backward()
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Exception ignored in: <function tqdm.__del__ at 0x2b61156e6820>
Traceback (most recent call last):
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1086, in __del__
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1293, in close
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1471, in display
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1089, in __repr__
  File "/home/aca10027xu/.local/lib/python3.8/site-packages/tqdm/std.py", line 1433, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```
```
Without early stopping it works ok. 

### Environment
```
* CUDA:
	- GPU:
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.9.1rc1
	- tensorboard:       2.2.0
	- tqdm:              4.46.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.2
	- version:           #1 SMP Fri Apr 20 16:44:24 UTC 2018
```
also had it on lightning 0.9.0 - actually did an upgrade to rc hoping that it will magically fix the problem

**Comment by undertherain** [comment]
I've printed log dic from inside the `_validate_condition_metric` class:
```
{'val_early_stop_on': tensor(0.4890, device='cuda:0'), 'val_checkpoint_on': tensor(0.4890, device='cuda:0')}
{'val_early_stop_on': tensor(0.4890, device='cuda:0'), 'val_checkpoint_on': tensor(0.4890, device='cuda:0')}
{'val_early_stop_on': tensor(0.5420, device='cuda:1'), 'val_checkpoint_on': tensor(0.5420, device='cuda:1')}                                 
{'val_early_stop_on': tensor(0.5420, device='cuda:1'), 'val_checkpoint_on': tensor(0.5420, device='cuda:1')}
{'val_early_stop_on': tensor(1.0173, device='cuda:2'), 'val_checkpoint_on': tensor(1.0173, device='cuda:2')}
{'val_early_stop_on': tensor(0.4354, device='cuda:3'), 'val_checkpoint_on': tensor(0.4354, device='cuda:3')}
{'val_early_stop_on': tensor(1.0173, device='cuda:2'), 'val_checkpoint_on': tensor(1.0173, device='cuda:2')}
{'val_early_stop_on': tensor(0.4354, device='cuda:3'), 'val_checkpoint_on': tensor(0.4354, device='cuda:3')}

```
it indeed looks like every worker is doing checkpoint on own loss value :-\
how come that doing this on averaged loss is not a default behaviour and how I can enforce that? 

looks like one time is called from early stopping, once from checkpoint which I did not even ask for. 

So far I like lightning, and would really like to express my appreciation to the developers
but funnily, unlike with other frameworks where I struggle to make them do something sometimes, with lightning I struggle to make it _not_ do something :D

**Comment by edenlightning** [comment]
@tgaddair mind taking a look?

**Comment by tgaddair** [comment]
Sure, let me take a look.

**Comment by edenlightning** [comment]
@tgaddair any update?

**Comment by tgaddair** [comment]
Hey @edenlightning, not yet.  I will try to take a look this week.

**Comment by tgaddair** [comment]
Hey @undertherain, sorry for the late response.  Tried looking into this earlier but couldn't repro.  I suspect there may be a few things going on here:

1. Early stopping criteria being applied independently on each worker.  We should implement PL metrics aggregation for Horovod so the criteria can be applied consistently on every worker.
2. Something appears to be wrong with the params in the DistributedOptimizer.  Sounds like this is related but not clear to me how without being able to repro myself (see https://discuss.pytorch.org/t/how-to-do-only-one-forward-propagation-per-epoch-and-multiple-backward-propagations-on-graph/65396/9 for more context).

@undertherain if you can provide a minimal repro that, will help a lot.  I will also try to prioritize getting the metrics aggregation for Horovod to work in PL, which may also address this issue as a side effect.

**Comment by undertherain** [comment]
Thanks for looking at this
took a bit of time to make code not depending on my custom dataset
here I basically generate random tensors and predict 0 on horovod rank 0, and 1 in the rest of the workers

https://github.com/undertherain/pl_stopping_test/tree/01c8d98ba6136d7a9e1b26f07bb3b8d63eca2724

**Comment by tgaddair** [comment]
Thanks for putting this together @undertherain!  I'll take a look and get back to you.

**Comment by tgaddair** [comment]
Hey @undertherain, here's the error I'm getting on a machine with 4 GPUs, looks like one worker is triggering early stopping but the others do not, leading to segfault:

```
[1,0]<stderr>:Saving latest checkpoint..
[1,0]<stderr>:Epoch 00003: early stopping triggered.
[1,1]<stderr>:[agent2323-dca1:01229] *** Process received signal ***
[1,1]<stderr>:[agent2323-dca1:01229] Signal: Segmentation fault (11)
[1,1]<stderr>:[agent2323-dca1:01229] Signal code: Address not mapped (1)
[1,1]<stderr>:[agent2323-dca1:01229] Failing at address: 0x38
[1,1]<stderr>:[agent2323-dca1:01229] [ 0] [1,1]<stderr>:/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7fbed56fd0e0]
[1,1]<stderr>:[agent2323-dca1:01229] [ 1] /usr/local/lib/openmpi/mca_btl_vader.so(+0x495d)[0x7fbdd45a495d]
[1,1]<stderr>:[agent2323-dca1:01229] [1,1]<stderr>:[ 2] [1,1]<stderr>:/usr/local/lib/libopen-pal.so.40(opal_progress+0x2c)[0x7fbde16264bc]
[1,1]<stderr>:[agent2323-dca1:01229] [ 3] [1,1]<stderr>:/usr/local/lib/libopen-pal.so.40(ompi_sync_wait_mt+0xb5)[0x7fbde162cd65]
[1,1]<stderr>:[agent2323-dca1:01229] [ 4] [1,1]<stderr>:/usr/local/lib/libmpi.so.40(ompi_request_default_wait+0x1ef)[0x7fbde1e2e2cf]
[1,1]<stderr>:[agent2323-dca1:01229] [ 5] [1,1]<stderr>:/usr/local/lib/libmpi.so.40(ompi_coll_base_sendrecv_actual+0xca)[0x7fbde1e8745a]
[1,1]<stderr>:[agent2323-dca1:01229] [ 6] [1,1]<stderr>:/usr/local/lib/libmpi.so.40(ompi_coll_base_allreduce_intra_recursivedoubling+0x2b7)[0x7fbde1e87857]
[1,1]<stderr>:[agent2323-dca1:01229] [ 7] [1,1]<stderr>:/usr/local/lib/libmpi.so.40(PMPI_Allreduce+0x1a9)[0x7fbde1e43f29]
[1,1]<stderr>:[agent2323-dca1:01229] [ 8] [1,1]<stderr>:/usr/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common13MPIController19CrossRankBitwiseAndERSt6vectorIxSaIxEEi+0x2c)[0x7fbde21ba1cc]
[1,1]<stderr>:[agent2323-dca1:01229] [ 9] [1,1]<stderr>:/usr/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common16CacheCoordinator4syncESt10shared_ptrINS0_10ControllerEEb+0x19f)[0x7fbde21837df]
[1,1]<stderr>:[agent2323-dca1:01229] [10] [1,1]<stderr>:/usr/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common10Controller23CoordinateCacheAndStateERNS0_16CacheCoordinatorE+0x5f)[0x7fbde214ea8f]
[1,1]<stderr>:[agent2323-dca1:01229] [11] [1,1]<stderr>:/usr/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common10Controller19ComputeResponseListERSt6atomicIbERNS0_18HorovodGlobalStateE+0x2348)[0x7fbde2155f28]
[1,1]<stderr>:[agent2323-dca1:01229] [12] [1,1]<stderr>:/usr/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x6e5d8)[0x7fbde21715d8]
[1,1]<stderr>:[agent2323-dca1:01229] [13] [1,1]<stderr>:/usr/local/gcc-7.4/lib64/libstdc++.so.6(+0xb9ccf)[0x7fbed4978ccf]
[1,1]<stderr>:[agent2323-dca1:01229] [14] [1,1]<stderr>:/lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4)[0x7fbed56f34a4]
[1,1]<stderr>:[agent2323-dca1:01229] [15] [1,1]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fbed4d2ad0f]
[1,1]<stderr>:[agent2323-dca1:01229] *** End of error message ***
```

Is this consistent with the error you're seeing?

**Comment by tgaddair** [comment]
@undertherain can you try #3775 and see if it addresses your issue?  With this change, I was able to get your test script to run to completion successfully.  Note that this change requires Horovod >= v0.20.1.

**Comment by undertherain** [comment]
Yes it seems to work! Thanks!
