### ISSUE TITLE
Tpye error: 'int' Object is not callable when pytorch_lighning is upgraded to version 0.8.1 or above。However, in version 0.7.1, it works normally

### ISSUE THREAD

**Issue by zhouwuxiong** [PyTorchLightning/pytorch-lightning#3569]
Tpye error: 'int' Object is not callable when pytorch_lighning is upgraded to version 0.8.1 or above。However, in version 0.7.1, it works normally

Traceback (most recent call last):
  File "/home/zwx/pointNet_family/pointnet.pytorch-master/utils/mytrain.py", line 210, in <module>
    triner.fit(model)
  File "/home/zwx/anaconda3/envs/PCReg/lib/python3.6/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/zwx/anaconda3/envs/PCReg/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1084, in fit
    results = self.accelerator_backend.train(model)
  File "/home/zwx/anaconda3/envs/PCReg/lib/python3.6/site-packages/pytorch_lightning/accelerators/cpu_backend.py", line 39, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/zwx/anaconda3/envs/PCReg/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/home/zwx/anaconda3/envs/PCReg/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 347, in train
    model.train()
TypeError: 'int' object is not callable

What's the reason？ anything help will be appreciate

**Comment by ydcjeff** [comment]
@zhouwuxiong could you try 1.0.4 and see if this still exists?
If this still exists, please use [the colab](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) for reproducible example
