### ISSUE TITLE
Getting RuntimeError: chunk expects at least a 1-dimensional tensor when using custom collate_fn in ddp setting.

### ISSUE THREAD

**Issue by Rashindrie** [PyTorchLightning/pytorch-lightning#3757]
## ❓ How to use custom collate function in dataloader in 'ddp'?

Hi,

I would appreciate some help in setting up a custom collate function in a ddp setting. 

#### Summary

I defined a custom collate function since I need to pass inputs of varying size to my code. 

```
def custom_collate(iter_batch):
    return [(dp[0], torch.tensor(dp[1])) for dp in iter_batch]
```

Then I define a data loader as follows:

```
valid_dataloader = DataLoader(val_dataset, batch_size=self.params['batch_size'], shuffle=False,
                                           num_workers=self.params['num_workers'], collate_fn=my_collate)
```

and the Trainer as follows:
```
configs = { 'trainer_params': {
            'max_epochs': 150,
            'early_stop_callback': early_stop_callback,
            # 'checkpoint_callback': checkpoint_callback,
            'check_val_every_n_epoch': 1,
            'gpus': -1,
            'precision': 16,
        }}
runner = Trainer(
        logger=tt_logger,
        log_save_interval=100,
        train_percent_check=1.,
        val_percent_check=1.,
        num_sanity_val_steps=5,
        distributed_backend='ddp',
        **config['trainer_params'],
    )
```
However, I get the following error when I run the program.

```
/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 28 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)

Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "train_pl.py", line 351, in <module>
    runner.fit(experiment)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1064, in fit
    results = self.accelerator_backend.train()
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/accelerators/dp_backend.py", line 97, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1257, in _run_sanity_check
    eval_results = self._evaluate(model, self.val_dataloaders, max_batches, False)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 331, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 661, in evaluation_forward
    output = model(*args)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 72, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 36, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    res = scatter_map(inputs)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 17, in scatter_map
    return list(map(list, zip(*map(scatter_map, obj))))
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torch/cuda/comm.py", line 148, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: chunk expects at least a 1-dimensional tensor
```

#### Environment?

* CUDA:
	- GPU:
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.17.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.9.0
	- tqdm:              4.46.0
        - ray:              0.8.7
        - tensorflow:              2.1.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.7.4

**Comment by fabrahman** [comment]
@Rashindrie Hi, I am facing the same issue. Did you manage to solve this? Thanks

**Comment by Rashindrie** [comment]
Hi @fabrahman I could not solve it. I switched into using a batch size of 1 with gradient accumulation.
