### ISSUE TITLE
Calling self.log fails with: 'LitClassifier' object has no attribute 'log'

### ISSUE THREAD

**Issue by jseppanen** [PyTorchLightning/pytorch-lightning#3991]
## 🐛 Bug

Calling `self.log(...)` fails with `torch.nn.modules.module.ModuleAttributeError: 'LitClassifier' object has no attribute 'log'`

### To Reproduce

```
$ python pl_examples/basic_examples/mnist.py
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to MNIST/raw/train-images-idx3-ubyte.gz
 99%|████████████████████████████████████████████████████████████████████████████████▉ | 9789440/9912422 [00:01<00:00, 2487387.89it/s]Extracting MNIST/raw/train-images-idx3-ubyte.gz to MNIST/raw
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to MNIST/raw/train-labels-idx1-ubyte.gz
                                                                                                                                     Extracting MNIST/raw/train-labels-idx1-ubyte.gz to MNIST/raw                                 | 16384/28881 [00:00<00:00, 156850.09it/s]
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to MNIST/raw/t10k-images-idx3-ubyte.gz
                                                                                                                                     Extracting MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST/raw
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to MNIST/raw/t10k-labels-idx1-ubyte.gz:00<00:01, 491443.56it/s]
9920512it [00:03, 3030956.24it/s]                                                                                                     
32768it [00:01, 22745.39it/s]                                                                                                         
1654784it [00:01, 1581939.35it/s]                                                                                                     
0it [00:00, ?it/s]                                                                                                                   Extracting MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST/raw
Processing...
/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/torchvision/datasets/mnist.py:469: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427478/work/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
Done!
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: Could not log computational graph since the `model.example_input_array` attribute is not set or `input_array` was not given
  warnings.warn(*args, **kwargs)

  | Name | Type   | Params
--------------------------------
0 | l1   | Linear | 100 K 
1 | l2   | Linear | 1 K   
/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "pl_examples/basic_examples/mnist.py", line 112, in <module>
    cli_main()
  File "pl_examples/basic_examples/mnist.py", line 103, in cli_main
    trainer.fit(model, train_loader, val_loader)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1084, in fit
    results = self.accelerator_backend.train(model)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_backend.py", line 39, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1257, in _run_sanity_check
    eval_results = self._evaluate(model, self.val_dataloaders, max_batches, False)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 333, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 687, in evaluation_forward
    output = model.validation_step(*args)
  File "pl_examples/basic_examples/mnist.py", line 52, in validation_step
    self.log('valid_loss', loss)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'LitClassifier' object has no attribute 'log'
8192it [00:00, 13214.65it/s]                                                                                                          
```

### Expected behavior

Running `mnist.py` should train MNIST classifier without errors.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.9.0
	- tqdm:              4.50.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.9
	- version:           #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020

**Comment by jseppanen** [comment]
I tried downgrading pytorch to 1.5.1 but the error remains (though the exception class is now different, AttributeError):

```
...
  File "pl_examples/basic_examples/mnist.py", line 52, in validation_step
    self.log('valid_loss', loss)
  File "/home/jarno/miniconda3/envs/dev/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'LitClassifier' object has no attribute 'log'
```

**Comment by SkafteNicki** [comment]
Please update to v0.10.0 (or master) as `self.log` is a newly feature introduced.

**Comment by jseppanen** [comment]
That worked, thanks for your help!

File under: race condition in documentation :sweat_smile: 

![image](https://user-images.githubusercontent.com/83203/95486756-18c45400-099c-11eb-8d79-693043f24156.png)
