### ISSUE TITLE
MNIST example throwing error "you tried to log -1 which is not currently supported. Try a dict or a scalar/tensor."

### ISSUE THREAD

**Issue by bartmch** [PyTorchLightning/pytorch-lightning#4070]
Hi,
I had to re-install my environment and now my code is breaking at trainer.fit() with the error: 
`you tried to log -1 which is not currently supported. Try a dict or a scalar/tensor.`
I also tried the MNIST example that can be found [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/mnist.py) with the same error.
I started off with a clean environment and installed Lightning using `pip install pytorch-lightning`. As a result I'm using torch 1.6.0+cu101 and lightning 0.10.0. I'm not passing any arguments.

Thanks

**Comment by awaelchli** [comment]
Thanks for reporting. 
Please post the full stack trace so we know if this is coming from TensorBoard logger or something else.

**Comment by williamFalcon** [comment]
could you reproduce using boring model or a colab?

That exception was hiding a broader exception which has now been chained on master.

**Comment by nickums** [comment]
I am getting this error from the flash Trainer when it uses Tensorboard writer
because of the error AttributeError: module 'tensorflow' has no attribute 'io'

  self._experiment = SummaryWriter(log_dir=self.log_dir, **self._kwargs)
  File "C:\Python\Python38\lib\site-packages\torch\utils\tensorboard\writer.py", line 220, in __init__
    self._get_file_writer()
  File "C:\Python\Python38\lib\site-packages\torch\utils\tensorboard\writer.py", line 250, in _get_file_writer
    self.file_writer = FileWriter(self.log_dir, self.max_queue,
  File "C:\Python\Python38\lib\site-packages\torch\utils\tensorboard\writer.py", line 60, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Python\Python38\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 76, in __init__
    if not tf.io.gfile.exists(logdir):
  File "C:\Python\Python38\lib\site-packages\tensorboard\lazy.py", line 68, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Python/Python38/OurStuff/OpenCV_Imaging/objdet with flash 51.py", line 142, in <module>
    trainer.finetune(model, datamodule=datamodule, strategy="freeze")
  File "C:\Python\Python38\lib\site-packages\flash\core\trainer.py", line 157, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "C:\Python\Python38\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 458, in fit
    self._run(model)
  File "C:\Python\Python38\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 753, in _run
    self.pre_dispatch()
  File "C:\Python\Python38\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 783, in pre_dispatch
    self.logger.log_hyperparams(self.lightning_module.hparams_initial)
  File "C:\Python\Python38\lib\site-packages\pytorch_lightning\utilities\distributed.py", line 49, in wrapped_fn
    return fn(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\pytorch_lightning\loggers\tensorboard.py", line 185, in log_hyperparams
    self.log_metrics(metrics, 0)
  File "C:\Python\Python38\lib\site-packages\pytorch_lightning\utilities\distributed.py", line 49, in wrapped_fn
    return fn(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\pytorch_lightning\loggers\tensorboard.py", line 210, in log_metrics
    raise ValueError(m) from ex
ValueError: 
 you tried to log -1 which is not currently supported. Try a dict or a scalar/tensor.

**Comment by anil-bit** [comment]
@ nickums did you find the solution for this?

**Comment by nickums** [comment]
afraid not, I'm stuck. Trying to stick to torch due to troubles with tensorflow-gpu

**Comment by graceyangfan** [comment]
I meet the same error,Finially I find that it's caused by the file path the logger try to be saved is a read only path

**Comment by egafni** [comment]
yeah this naked exception produces an error message that is really confusing, file perms for me too

**Comment by alexyalunin** [comment]
Just `pip install tensorflow`
This error is due https://github.com/thu-ml/tianshou/issues/39

**Comment by nickums** [comment]
alexy  I have tensorflow 2.6.0 so reinstall does nothing, and I do not want to go down the tianshow rabbit hole. suggested.

**Comment by moonlightSong** [comment]
I had the same error but not with the MNIST example. The problem is I renamed "version_{a number}" to something else under the lightning_logs directory. After I remove that from the lightning_logs directory, the error disappeared.

**Comment by Norwalker** [comment]
> I had the same error but not with the MNIST example. The problem is I renamed "version_{a number}" to something else under the lightning_logs directory. After I remove that from the lightning_logs directory, the error disappeared.

yeah bingo. i face the same error when i use pytorch-lighting. then i remove the file named lighting_logs,and i delete relevant code。

**Comment by hom-bahrani** [comment]
Installing tensorflow doesn't get rid of the error, which looks like its coming from here https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/loggers/tensorboard.py#L271

**Comment by moneroexamples** [comment]
I also had this issue, but with `darts` and with `RNNModel`. Specifically I was using `log_tensorboard=True` in `RNNModel`. Setting this option to false `log_tensorboard=False` solved the problem.
