### ISSUE TITLE
training_step_end not working as expected - receives only input from a single GPU instead of two

### ISSUE THREAD

**Issue by swethmandava** [PyTorchLightning/pytorch-lightning#4290]
## 🐛 Bug

training_step_end not working as expected - receives only input from a single GPU instead of two

### To Reproduce

```
    def training_step(self, batch, batch_idx) -> Dict:
        t0 = time.time()

        loss_tensors, logits = self._step(batch)

        runtime = time.time() - t0

        logs = {name: loss for name, loss in zip(self.loss_names, loss_tensors)}
        # tokens per batch
        logs["tpb"] = batch["input_ids"].ne(self.pad).sum() + batch["labels"].ne(self.pad).sum()
        logs["bs"] = batch["input_ids"].shape[0]
        logs["src_pad_tok"] = batch["input_ids"].eq(self.pad).sum()
        logs["src_pad_frac"] = batch["input_ids"].eq(self.pad).float().mean()
        logs["batch_time"] = runtime
        # TODO(SS): make a wandb summary metric for this

        return {"loss": loss_tensors[0], "log": logs, "progress_bar":{"global_step":self.global_step}}

    def training_step_end(self, batch_parts):
        aggregated_parts = {}

        aggregated_parts["loss"] = sum([i["loss"] for i in batch_parts])/len(batch_parts)
        aggregated_parts["progress_bar"] = batch_parts[0]["progress_bar"]

        # Accumulate perf metrics across GPUS
        aggregated_parts["logs"] = {}
        aggregated_parts["logs"]["tpb"] = sum([i["logs"]["tpb"] for i in batch_parts])
        aggregated_parts["logs"]["src_pad_tok"] = sum([i["logs"]["src_pad_tok"] for i in batch_parts])
        aggregated_parts["logs"]["src_pad_frac"] = sum([i["logs"]["src_pad_frac"] for i in batch_parts])
        aggregated_parts["logs"]["batch_time"] = sum([i["logs"]["batch_time"] for i in batch_parts])/len(batch_parts)
        aggregated_parts["logs"]["bs"] = sum([i["logs"]["batch_time"] for i in batch_parts])

        return aggregated_parts

```

### Expected behavior

accumulate perf metrics across different GPUs

### Additional context

```
distributed_backend=ddp
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------
Epoch 0:   0%|                                                                 | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):
  File "finetune.py", line 490, in <module>
    main(args)
  File "finetune.py", line 465, in main
    logger=logger,
  File "/workspace/bart/lightning_base.py", line 374, in generic_train
    trainer.fit(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 302, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/accelerators/ddp_backend.py", line 129, in train
    results = self.ddp_train_tmp(process_idx=self.task_idx, mp_queue=None, model=model, is_master=True)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/accelerators/ddp_base_backend.py", line 170, in ddp_train_tmp
    results = self.train_or_test()
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/accelerators/base_backend.py", line 36, in train_or_test
    results = self.trainer.train()
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 349, in train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 446, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 566, in run_training_batch
    self.trainer.hiddens
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 640, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 300, in training_step
    training_step_output = self.trainer.call_hook('training_step_end', training_step_output)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 639, in call_hook
    output = hook_fx(*args, **kwargs)
  File "finetune.py", line 184, in training_step_end
    aggregated_parts["loss"] = sum([i["loss"] for i in batch_parts])/len(batch_parts)
  File "finetune.py", line 184, in <listcomp>
    aggregated_parts["loss"] = sum([i["loss"] for i in batch_parts])/len(batch_parts)
TypeError: string indices must be integers
```

When I print batch_parts, I only see one input
```
{'loss': tensor(5469.4434, device='cuda:0', grad_fn=<AddBackward0>), 'log': {'loss': tensor(5469.4434, device='cuda:0', grad_fn=<AddBackward0>), 'tpb': tensor(9328, device='cuda:0'), 'bs': 8, 'src_pad_tok': tensor(0, device='cuda:0'), 'src_pad_frac': tensor(0., device='cuda:0'), 'batch_time': 0.6451365947723389}, 'progress_bar': {'global_step': 0}}
```

**Comment by awaelchli** [comment]
> distributed_backend=ddp
> All DDP processes registered. Starting ddp with 2 processes

looks like you are using ddp. I'm pretty sure `training_step_end` does not apply to ddp.
also, logging via dict is deprecated, one should use the new `self.log` api. 
You can set `sync_dist=True` to aggregate accross gpus.

**Comment by ananyahjha93** [comment]
@swethmandava like Adrian mentioned, please updated to the latest version of Lightning and use the new metrics package to aggregated across GPUs.

**Comment by tchaton** [comment]
Hey @swethmandava,

If this bug persists when updating to latest stable of Pytorch Lightning and its new API. I would recommend for you to use  (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py) to prepare a template reproducing the bug. 

Best regards,
T.C

**Comment by swethmandava** [comment]
Updated pytorch lightning to 1.0.3 and code to do the following:

```
    def training_step(self, batch, batch_idx) -> Dict:
        t0 = time.time()

        loss_tensors, logits = self._step(batch)

        runtime = torch.tensor(time.time() - t0, device=logits.device)

        logs = {name: loss for name, loss in zip(self.loss_names, loss_tensors)}
        # tokens per batch
        tpb = batch["input_ids"].ne(self.pad).sum() + batch["labels"].ne(self.pad).sum()
        all_tpb = torch.tensor(batch["input_ids"].numel() + batch["labels"].numel(), device=logits.device) #include pad tokens
        bs = batch["input_ids"].shape[0]
        src_pad_tok = batch["input_ids"].eq(self.pad).sum()
        src_pad_frac = batch["input_ids"].eq(self.pad).float().mean()
        batch_time = runtime

        self.log("epoch_runtime", runtime, on_epoch=True, tbptt_reduce_fx=torch.sum, sync_dist=True, prog_bar=True)
        self.log("unpadded_tokens", tpb, on_epoch=True, tbptt_reduce_fx=torch.sum, sync_dist=True, sync_dist_op=torch.distributed.ReduceOp.SUM, prog_bar=True)
        self.log("all_tokens", all_tpb, on_epoch=True, tbptt_reduce_fx=torch.sum, sync_dist=True, sync_dist_op=torch.distributed.ReduceOp.SUM, prog_bar=True)
        self.log("epoch_tokens_per_second", all_tpb/runtime, on_epoch=True, tbptt_reduce_fx=torch.sum, sync_dist=True, sync_dist_op=torch.distributed.ReduceOp.SUM, prog_bar=True)
        self.log("iterations_per_second", 1/runtime, on_epoch=True, tbptt_reduce_fx=torch.sum, sync_dist=True, prog_bar=True)
        
        self.log("train_loss", loss_tensors[0], on_step=True, on_epoch=True, prog_bar=True)
        return
```

however, it prints loss=NaN on progress bar. I also am not sure how to access and modify it/s on the progress bar (for example, simply modify to tokens/s etc) in the absence of on_batch_end in pl_module

**Comment by swethmandava** [comment]
Another side effect of moving to 1.0.3 from 0.9.0 is a change in my convergence properties. while looking into the logs, i see validation is now done on all GPUs vs just one gpu in 0.9.0. early stopping is being triggered early now - is it checking for "any" gpu instead of "all" ? @tchaton

**Comment by awaelchli** [comment]
@swethmandava it should be working with the latest release. btw you can change the return statement to
`return loss_tensors[0]`

as far as I know, you cannot change the it/s display in tqdm progress bars. 
If you need to customize progress bar, you can sublcass our callback:  
https://pytorch-lightning.readthedocs.io/en/stable/generated/pytorch_lightning.callbacks.ProgressBar.html#pytorch_lightning.callbacks.ProgressBar

**Comment by FrancescoSaverioZuppichini** [comment]
same here, two gpus I only see one tensor
