### ISSUE TITLE
Last epoch run produces a tqdm exception

### ISSUE THREAD

**Issue by LakshyaMalhotra** [PyTorchLightning/pytorch-lightning#4404]
## ❓ Questions and Help

I have started using pytorch-lightning only recently. I'm just playing with MNIST data so as to get used to the API. Everything works perfectly fine but the last epoch run always produces an exception. I don't know if I'm doing something wrong or is it an issue with tqdm. Any help would be appreciated! Also, is there a way to print `loss` and `accuracy` without showing the progress bar? 
```
 | Name      | Type             | Params
-----------------------------------------------
0 | l1        | Linear           | 200 K 
1 | l2        | Linear           | 16 K  
2 | l3        | Linear           | 4 K   
3 | l4        | Linear           | 650   
4 | drop      | Dropout          | 0     
5 | criterion | CrossEntropyLoss | 0     
6 | train_acc | Accuracy         | 0     
7 | valid_acc | Accuracy         | 0     
Epoch 1: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 1017/1017 [00:09<00:00, 100.37it/s, loss=0.336, v_num=24, train_loss=2.33, train_acc=0.143Exception ignored in: <function tqdm.__del__ at 0x7fd9c4374f80>                                                                                                                                        
Traceback (most recent call last):
  File "/home/anaconda3/envs/pt-gpu/lib/python3.7/site-packages/tqdm/std.py", line 1128, in __del__
  File "/home/anaconda3/envs/pt-gpu/lib/python3.7/site-packages/tqdm/std.py", line 1341, in close
  File "/home/anaconda3/envs/pt-gpu/lib/python3.7/site-packages/tqdm/std.py", line 1520, in display
  File "/home/anaconda3/envs/pt-gpu/lib/python3.7/site-packages/tqdm/std.py", line 1131, in __repr__
  File "/home/anaconda3/envs/pt-gpu/lib/python3.7/site-packages/tqdm/std.py", line 1481, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```
Here is the python script I'm running:
```python
class ResNetPL(pl.LightningModule):
    def __init__(self, lr=1e-3):
        super().__init__()
        self.l1 = nn.Linear(28 * 28, 256)
        self.l2 = nn.Linear(256, 64)
        self.l3 = nn.Linear(64, 64)
        self.l4 = nn.Linear(64, 10)
        self.drop = nn.Dropout(p=0.6)
        self.criterion = nn.CrossEntropyLoss()
        self.train_acc = pl.metrics.Accuracy()
        self.valid_acc = pl.metrics.Accuracy()
        self.learning_rate = lr

    def forward(self, x):
        x = F.relu(self.l1(x))
        h1 = F.relu(self.l2(x))
        h2 = F.relu(self.l3(h1))
        do = self.drop(h1 + h2)
        logits = self.l4(do)
        return logits

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=self.learning_rate)
        return optimizer

    def training_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)

        # forward pass
        logits = self(x)  

        # compute the objective function
        loss = self.criterion(logits, y)

        self.train_acc(logits, y)

        self.log(
            "train_loss", loss, on_step=False, on_epoch=True, prog_bar=True
        )
        self.log(
            "train_acc",
            self.train_acc,
            on_step=False,
            on_epoch=True,
            prog_bar=True,
        )
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch

        x = x.view(x.size(0), -1)
        logits = self(x)
        loss = self.criterion(logits, y)

        # return the accuracy
        acc_valid = self.valid_acc(logits, y)
        
        self.log("loss", loss, on_step=False, on_epoch=False, prog_bar=False)
        self.log(
            "acc",
            self.valid_acc,
            on_step=False,
            on_epoch=False,
            prog_bar=False,
        )
        return {"loss_val": loss, "acc_val": acc_valid}

    def validation_epoch_end(self, val_step_outputs):
        avg_val_loss = torch.tensor(
            [x["loss_val"] for x in val_step_outputs]
        ).mean()
        avg_val_acc = torch.tensor(
            [x["acc_val"] for x in val_step_outputs]
        ).mean()
        self.log(
            "avg_val_loss",
            avg_val_loss,
            on_step=False,
            on_epoch=True,
            prog_bar=True,
        )
        self.log(
            "avg_val_acc",
            avg_val_acc,
            on_step=False,
            on_epoch=True,
            prog_bar=True,
        )

    def prepare_data(self):
        transform = transforms.Compose(
            [
                transforms.ToTensor(),
                transforms.Normalize(
                    (0.1307,),
                    (0.3081,),
                ),
            ]
        )
        mnist_data = torchvision.datasets.MNIST(
            "data", train=True, transform=transform, download=True
        )
        self.mnist_train, self.mnist_val = torch.utils.data.random_split(
            mnist_data, [55000, 5000]
        )

    def train_dataloader(self):
        train_loader = torch.utils.data.DataLoader(
            self.mnist_train,
            batch_size=64,
            shuffle=True,
            num_workers=8,
        )
        return train_loader

    def val_dataloader(self):
        val_loader = torch.utils.data.DataLoader(
            self.mnist_val, batch_size=32, shuffle=False, num_workers=8
        )
        return val_loader


if __name__ == "__main__":
    model = ResNetPL()
    trainer = pl.Trainer(gpus=1, max_epochs=2)

    # find the best lr
    lr_finder = trainer.tuner.lr_find(model)
    print(f"Best learning rate: {lr_finder.suggestion()}")

    # plot the lr curve
    fig = lr_finder.plot(suggest=True)
    fig.show()

    # set the best lr as the model lr
    model.learning_rate = lr_finder.suggestion()
    trainer.fit(model)
```
   

#### Environment:

 - OS: Linux
 - Packaging: pip
 - Version: 1.0.3

**Comment by bipinKrishnan** [comment]
Hey @LakshyaMalhotra , I was not able to reproduce your issue, I have copy pasted your code for "ResNetPL" class and after that ran with the following code on colab notebook:

```python
model = ResNetPL()
trainer = pl.Trainer(max_epochs=2, gpus=1, progress_bar_refresh_rate=60)

lr_best = trainer.tuner.lr_find(model)
model.learning_rate = lr_best.results['lr'][0]

trainer.fit(model)
```

**Comment by Vichoko** [comment]
Try setting `drop_last=False` attribute on DataLoader.

**Comment by LakshyaMalhotra** [comment]
@Vichoko I'm still having the same error even after setting `drop_last=True` in the dataloader.

**Comment by Vichoko** [comment]
Ok, my bad.
Now taking a further look I noted the aggregation behaviour you added on `validation_epoch_end` isn't needed as the loss and accuracy metrics are aggregated by themselves on epoch ended. I'd remove this method completely.

Also, I'd homologate the metric names on validation step as you are using 3 different types, loss and accuracy, then loss_val and acc_val and in the train step you are using train_loss and train_acc. I'm pretty sure that you don't need to return anything on train and Val steps, I'd remove those returns just to keep the code clear. And I'd stick to the train_{metric} and val_{metric} name convention.

Finally, I'd remove the keyword params of all the self.log calls you are using as they are chosen automatically depending on if you are training or evaluating for the most standard configuration.

**Comment by LakshyaMalhotra** [comment]
@Vichoko Thanks for your reply! Like you mentioned I changed my code but still I got the same error. Following is the updated code:
```
import os
import torch
import torchvision
from torchvision import transforms
import torch.nn as nn
import torch.nn.functional as F
import pytorch_lightning as pl

import matplotlib.pyplot as plt


class ResNetPL(pl.LightningModule):
    def __init__(self, lr=1e-3):
        super().__init__()
        self.l1 = nn.Linear(28 * 28, 256)
        self.l2 = nn.Linear(256, 64)
        self.l3 = nn.Linear(64, 64)
        self.l4 = nn.Linear(64, 10)
        self.drop = nn.Dropout(p=0.6)
        self.criterion = nn.CrossEntropyLoss()
        self.train_acc = pl.metrics.Accuracy()
        self.valid_acc = pl.metrics.Accuracy()
        self.learning_rate = lr

    def forward(self, x):
        x = F.relu(self.l1(x))
        h1 = F.relu(self.l2(x))
        h2 = F.relu(self.l3(h1))
        do = self.drop(h1 + h2)
        logits = self.l4(do)
        return logits

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=self.learning_rate)
        return optimizer

    def training_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)

        # forward pass
        logits = self(x)  # l: logits

        # compute the objective function
        train_loss = self.criterion(logits, y)

        self.train_acc(logits, y)

        self.log("train_loss", train_loss, prog_bar=True)
        self.log("train_acc", self.train_acc, prog_bar=True)
        return train_loss

    def validation_step(self, batch, batch_idx):
        x, y = batch

        x = x.view(x.size(0), -1)
        logits = self(x)
        valid_loss = self.criterion(logits, y)

        self.valid_acc(logits, y)
        self.log("valid_loss", valid_loss, prog_bar=True)
        self.log("valid_acc", self.valid_acc, prog_bar=True)

    def prepare_data(self):
        transform = transforms.Compose(
            [
                transforms.ToTensor(),
                transforms.Normalize((0.1307,), (0.3081,),),
            ]
        )
        mnist_data = torchvision.datasets.MNIST(
            "data", train=True, transform=transform, download=True
        )
        self.mnist_train, self.mnist_val = torch.utils.data.random_split(
            mnist_data, [55000, 5000]
        )

    def train_dataloader(self):
        train_loader = torch.utils.data.DataLoader(
            self.mnist_train, batch_size=64, shuffle=True, num_workers=8,
        )
        return train_loader

    def val_dataloader(self):
        val_loader = torch.utils.data.DataLoader(
            self.mnist_val, batch_size=32, shuffle=False, num_workers=8,
        )
        return val_loader


if __name__ == "__main__":
    model = ResNetPL()
    trainer = pl.Trainer(max_epochs=2)

    # find the best lr
    lr_finder = trainer.tuner.lr_find(model)
    print(f"Best learning rate: {lr_finder.suggestion()}")

    # plot the lr curve
    fig = lr_finder.plot(suggest=True)
    fig.show()

    # set the best lr as the model lr
    model.learning_rate = lr_finder.suggestion()
    trainer.fit(model)
```
The only way the code works without giving any error is when I remove the code for finding the best `learning_rate`.  Whenever I add the `lr_finder` in the code I end up in the same error.
