### ISSUE TITLE
Some test directories clash with standard library modules

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#4436]
Namely:

https://github.com/PyTorchLightning/pytorch-lightning/tree/master/tests/trainer/warnings
https://github.com/PyTorchLightning/pytorch-lightning/tree/master/tests/trainer/logging
(I haven't checked if there are more)

This is problematic, for example, when you run tests using a tool like PyCharm. This is because local modules take precedence over stdlib modules.

So you get errors like this one:

```
Traceback (most recent call last):
  File "/home/carmocca/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.6397.98/plugins/python-ce/helpers/pydev/pydevd.py", line 22, in <module>
    from _pydevd_bundle.pydevd_constants import IS_JYTH_LESS25, IS_PYCHARM, get_thread_id, get_current_thread_id, \
  File "/home/carmocca/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.6397.98/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_constants.py", line 216, in <module>
    from _pydev_imps._pydev_saved_modules import thread
  File "/home/carmocca/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.6397.98/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_saved_modules.py", line 21, in <module>
    import xmlrpc.client as xmlrpclib
  File "/usr/lib/python3.8/xmlrpc/client.py", line 136, in <module>
    import http.client
  File "/usr/lib/python3.8/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.8/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.8/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.8/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.8/email/utils.py", line 28, in <module>
    import random
  File "/usr/lib/python3.8/random.py", line 40, in <module>
    from warnings import warn as _warn
ImportError: cannot import name 'warn' from 'warnings' (/home/carmocca/projects/carmocca-lightning/tests/trainer/warnings/__init__.py)
```

We shoud rename them.

**Comment by edenlightning** [comment]
Thanks for the issue! Mind sending over a PR?
