### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.trainer.seed'

### ISSUE THREAD

**Issue by ferngonzalezp** [PyTorchLightning/pytorch-lightning#4513]
Hello, I updated pl to version 1.0.5  under my user environment of a HPC cluster managed by slurm which had installed pl version 0.7.6. When i launch a job i get the following error:

 `Traceback (most recent call last):
  File "train_pinn.py", line 3, in <module>
    from pytorch_lightning import trainer
  File "/home/2006011/fgonza01/.python-DL-3.6.9/site-packages/lib/python3.6/site-packages/pytorch_lightning/__init__.py", line 79, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/soft/Python3-DL1908/3.6.9/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2284, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/soft/Python3-DL1908/3.6.9/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2217, in _handle_ns
    loader.load_module(packageName)
  File "/soft/Python3-DL1908/3.6.9/lib/python3.6/site-packages/pytorch_lightning/__init__.py", line 55, in <module>
    from pytorch_lightning.trainer.seed import seed_everything
ModuleNotFoundError: No module named 'pytorch_lightning.trainer.seed'`  

It appears that version 1.0.5 no longer has a seed module under training but don't know why it is trying to import it. Any ideas how to fix this?

#### What's your environment?

 - OS: [Linux]
 - Packaging pip
 - Version 1.0.5

**Comment by ydcjeff** [comment]
You can import that with `from pytorch_lightning import seed_everything` in latest version.
