### ISSUE TITLE
On "import pytorch-lightning": AttributeError: python: undefined symbol: THCudaHalfTensor_normall

### ISSUE THREAD

**Issue by nihirv** [PyTorchLightning/pytorch-lightning#5027]
## 🐛 Bug

Simply by importing pytorch-lightning, I receive the following error: `AttributeError: python: undefined symbol: THCudaHalfTensor_normall`

Traceback:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pytorch_lightning
  File "/data/nv419/anaconda3/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 56, in <module>
    from pytorch_lightning import metrics
  File "/data/nv419/anaconda3/lib/python3.7/site-packages/pytorch_lightning/metrics/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.metric import Metric
  File "/data/nv419/anaconda3/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py", line 26, in <module>
    from pytorch_lightning.utilities.apply_func import apply_to_collection
  File "/data/nv419/anaconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/__init__.py", line 25, in <module>
    from apex import amp
  File "/data/nv419/anaconda3/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/__init__.py", line 12, in <module>
    from . import optimizers
  File "/data/nv419/anaconda3/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/optimizers/__init__.py", line 2, in <module>
    from .fp16_optimizer import FP16_Optimizer
  File "/data/nv419/anaconda3/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/optimizers/fp16_optimizer.py", line 8, in <module>
    lib.THCudaHalfTensor_normall.argtypes=[ctypes.c_void_p, ctypes.c_void_p]
  File "/data/nv419/anaconda3/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/data/nv419/anaconda3/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: THCudaHalfTensor_normall
```

### To Reproduce
`import pytorch-lightning`

### Expected behavior
For pytorch-lightning to import and be used correctly

### Environment
* CUDA:
        - GPU:
                - Tesla V100-PCIE-32GB
                - Tesla V100-PCIE-32GB
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.17.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.6.0+cu101
        - tqdm:              4.54.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.7.4
        - version:           #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020

### Additional context
pytorch-lightning version is 1.0.8 (couldn't import it in obviously...)

**Comment by awaelchli** [comment]
From your error message it looks like you have apex installed. 
Try to import apex: 
`from apex import amp`
and you will probably see the same error. Check your apex installation, maybe it is incompatible with your pytorch version or it wasn't correctly compiled.

**Comment by nihirv** [comment]
> From your error message it looks like you have apex installed.
> Try to import apex:
> `from apex import amp`
> and you will probably see the same error. Check your apex installation, maybe it is incompatible with your pytorch version or it wasn't correctly compiled.

This was the issue! Fixed it by uninstalling apex (`pip uninstall apex`). Thanks!

Closing the issue

**Comment by awaelchli** [comment]
Awesome! You're welcome
