### ISSUE TITLE
Wandb permission denied

### ISSUE THREAD

**Issue by Joohee-Park** [PyTorchLightning/pytorch-lightning#5078]
### Before asking: 
1. Try to find answers to your questions in [the Lightning Forum!](https://forums.pytorchlightning.ai/)
2. Search for similar [issues](https://github.com/PyTorchLightning/pytorch-lightning/issues).   
3. Search the [docs](https://pytorch-lightning.readthedocs.io/en/latest/).    

#### What is your question?

Hello! 

First of all, thank you for making this great library.

I tried to deploy the code which uses pytorch_lightning library on the hadoop cluster,
but I encountered the permission problem...
Is there anyway that I can import pytorch_lightning without root permission?

Thank you!

#### Code

```python
import pytorch_lightning as pl
```
```
Traceback (most recent call last):
  File "/data3/hadoop/yarn/local/usercache/chewie-park/appcache/application_1603778770965_1295035/container_e71_1603778770965_1295035_01_000038/./query_mapper.py", line 11, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/__init__.py", line 63, in <module>
    from pytorch_lightning.trainer import Trainer
  File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/trainer/__init__.py", line 18, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 32, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
  File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/loggers/__init__.py", line 59, in <module>
    from pytorch_lightning.loggers.wandb import WandbLogger
  File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/loggers/wandb.py", line 26, in <module>
    import wandb
  File "/usr/local/lib/python3.6/site-packages/wandb/__init__.py", line 116, in <module>
    api = InternalApi()
  File "/usr/local/lib/python3.6/site-packages/wandb/apis/internal.py", line 17, in __init__
    self.api = InternalApi(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 81, in __init__
    load_settings=load_settings, root_dir=self.default_settings.get("root_dir")
  File "/usr/local/lib/python3.6/site-packages/wandb/old/settings.py", line 25, in __init__
    self._global_settings.read([Settings._global_path()])
  File "/usr/local/lib/python3.6/site-packages/wandb/old/settings.py", line 105, in _global_path
    util.mkdir_exists_ok(config_dir)
  File "/usr/local/lib/python3.6/site-packages/wandb/util.py", line 632, in mkdir_exists_ok
    os.makedirs(path)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/.config'
```

   

#### What's your environment?

 - OS: Linux
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by jarivk** [comment]
Is there a workaround for this ? Any way to override root_dir ?

**Comment by rohitgr7** [comment]
you can ask about this on [wandb slack](wandb.me/slack) for more info since this is related to their internal api.

**Comment by karthi0804** [comment]
> Is there a workaround for this ? Any way to override root_dir ?

Hi did you manage to solve it?. I am also facing the same prob.
