### ISSUE TITLE
Dataloader with custom batch sampler

### ISSUE THREAD

**Issue by chagmgang** [PyTorchLightning/pytorch-lightning#5145]
### Before asking: 
1. Try to find answers to your questions in [the Lightning Forum!](https://forums.pytorchlightning.ai/)
2. Search for similar [issues](https://github.com/PyTorchLightning/pytorch-lightning/issues).   
3. Search the [docs](https://pytorch-lightning.readthedocs.io/en/latest/).    

#### What is your question?

I try to use custom IterationBasedBatchSampler.
When I try to trainer.fit(model, train_dataloader) with 'ddp' and multi gpu below error message is happened.

How can I use this IterationBasedBatchSampler?
Or what are the check points do I have to?

```
Traceback (most recent call last):
  File "lea_train_net.py", line 69, in <module>
    main(args)
  File "lea_train_net.py", line 58, in main
    trainer.fit(model, data_loader_train, data_loader_valid)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 143, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 298, in ddp_train
    results = self.train_or_test()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 65, in train_or_test
    results = self.trainer.train()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 521, in train
    self.train_loop.run_training_epoch()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 554, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/profiler/profilers.py", line 83, in profile_iterable
    value = next(iterator)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 46, in _with_is_last
    last = next(it)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 45, in default_collate
    elem = batch[0]
KeyError: 0
```

#### Code

My custom IterationBasedBatchSampler code is below
```
class IterationBasedBatchSampler(torch.utils.data.sampler.BatchSampler):
    """
    Wraps a BatchSampler, resampling from it until
    a specified number of iterations have been sampled
    """

    def __init__(self, batch_sampler, num_iterations, start_iter=0):
        self.batch_sampler = batch_sampler
        self.num_iterations = num_iterations
        self.start_iter = start_iter

    def __iter__(self):
        iteration = self.start_iter
        while iteration <= self.num_iterations:
            # if the underlying sampler has a set_epoch method, like
            # DistributedSampler, used for making each process see
            # a different split of the dataset, then set it
            if hasattr(self.batch_sampler.sampler, "set_epoch"):
                self.batch_sampler.sampler.set_epoch(iteration)
            for batch in self.batch_sampler:
                iteration += 1
                if iteration > self.num_iterations:
                    break
                yield batch

    def __len__(self):
        return self.num_iterations
```

And my train code is below.
```
trainer = pl.Trainer(
            gpus=2,
            distributed_backend='ddp',
            val_check_interval=1000,
            max_epochs=1,
            checkpoint_callback=checkpoint_callback,
            logger=logger)
trainer.fit(model,
            fake_dataloader_train,
            fake_dataloader_valid)
```

   

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by awaelchli** [comment]
Hi, I did some testing and by setting `Trainer(replace_sampler_ddp=False)` it seems to work. 
You will have to use DistributedSampler for the sampler you pass into your custom batch sampler if you use distributed multi-gpu. 
Also one thing that I found odd when testing your code is that you inherit from BatchSampler but never call super().init on it, so double check that this is right.

**Comment by awaelchli** [comment]
```python 
import os
import torch
from torch.utils.data import Dataset, SequentialSampler, BatchSampler
from pytorch_lightning import Trainer, LightningModule


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        """
        Testing PL Module

        Use as follows:
        - subclass
        - modify the behavior for what you want

        class TestModel(BaseTestModel):
            def training_step(...):
                # do your own thing

        or:

        model = BaseTestModel()
        model.training_epoch_end = None

        """
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def step(self, x):
        x = self.layer(x)
        out = torch.nn.functional.mse_loss(x, torch.ones_like(x))
        return out

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


class IterationBasedBatchSampler:
    """
    Wraps a BatchSampler, resampling from it until
    a specified number of iterations have been sampled
    """

    def __init__(self, batch_sampler, num_iterations, start_iter=0):
        self.batch_sampler = batch_sampler
        self.num_iterations = num_iterations
        self.start_iter = start_iter

    def __iter__(self):
        iteration = self.start_iter
        while iteration <= self.num_iterations:
            # if the underlying sampler has a set_epoch method, like
            # DistributedSampler, used for making each process see
            # a different split of the dataset, then set it
            if hasattr(self.batch_sampler.sampler, "set_epoch"):
                self.batch_sampler.sampler.set_epoch(iteration)
            for batch in self.batch_sampler:
                iteration += 1
                if iteration > self.num_iterations:
                    break
                yield batch

    def __len__(self):
        return self.num_iterations


def run_test():

    # fake data
    dataset = RandomDataset(32, 64)

    # here we may want to use DistributedSampler!
    batch_sampler = BatchSampler(SequentialSampler(range(len(dataset))), batch_size=4, drop_last=True)
    batch_sampler2 = IterationBasedBatchSampler(batch_sampler, num_iterations=10)
    train_data = torch.utils.data.DataLoader(dataset, batch_sampler=batch_sampler2)

    # model
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        max_epochs=1,
        weights_summary=None,
        gpus=2,
        accelerator="ddp",
        replace_sampler_ddp=False,  # <--- set this
    )
    trainer.fit(model, train_data)


if __name__ == '__main__':
    run_test()

```

**Comment by chagmgang** [comment]
Thanks for answering to my question. It's done.

**Comment by awaelchli** [comment]
You're welcome. Closing this now. Let me know in case other problems arise.

**Comment by ankitvad** [comment]
Hi, thanks a lot for the code sample! :) I wanted to ask about this line that you used:
```
# here we may want to use DistributedSampler!
    batch_sampler = BatchSampler(SequentialSampler(range(len(dataset))), batch_size=4, drop_last=True)
    batch_sampler2 = IterationBasedBatchSampler(batch_sampler, num_iterations=10)
    train_data = torch.utils.data.DataLoader(dataset, batch_sampler=batch_sampler2)
```
When you mention - here we may want to use DIstributedSampler? It doesn't seem you ended up using it in the code sample you provided? Does PL work as expected with multi-gpu and ddp when using the code sample you suggested above?
I see that there are a few other comments that talk about this and if the distributed sampler is necessary? 
@awaelchli

**Comment by awaelchli** [comment]
PyTorchLightning currently has the ability to replace the sampler for you and make a distributed sampler, but not when
- it is a custom sampler or
- when the dataloader has a batch sampler

In the code sample above, you, the user, would have to replace the sequential sampler with a DistributedSampler sampler yourself: 

```py
batch_sampler = BatchSampler(
    sampler=DistributedSampler(range(len(dataset)), world_size=..., rank=...), 
    batch_size=4, 
    drop_last=True,
    shuffle=False, # you may set shuffle
)
batch_sampler2 = IterationBasedBatchSampler(batch_sampler, num_iterations=10)
train_data = torch.utils.data.DataLoader(dataset, batch_sampler=batch_sampler2)
```

**Comment by ankitvad** [comment]
So basically with a custom sampler and using multi-gpu training, we would need to use the `DistributedSampler`?

**Comment by awaelchli** [comment]
Yes, otherwise the batch sampler on each device would "see" the same samples.

**Comment by ankitvad** [comment]
That makes sense! Thanks a lot! :) 
I think I updated my comment but you might have missed that!
Is an `IterationBasedBatchSampler` also necessary?

**Comment by awaelchli** [comment]
Is an IterationBasedBatchSampler also necessary?

This was the custom sampler in the question from @chagmgang. So my code sample is just referencing that. Their code was just taking an existing batch sampler and wrapping it into another one.

**Comment by svdeepak99** [comment]
> ```python
> replace_sampler_ddp=False,  # <--- set this
> ```

This have now been replaced by `use_distributed_sampler=False`

And thanks a lot @awaelchli for providing this answer. It's working perfectly! (with this 1 change above)
