### ISSUE TITLE
How can I stop WandbLogger instance being instantiated when calling load_from_checkpoint?

### ISSUE THREAD

**Issue by kyoungrok0517** [PyTorchLightning/pytorch-lightning#5180]
Hello. I have a checkpoint that used `wandb` during training. Now I want to use the trained model for inference in Hadoop environment. Each node loads the checkpoint, reads data, then infer. 

What prevents me is the following error. When I call `load_from_checkpoint()`, the code tries to re-instate `WandbLogger` instance. Then `WandbLogger` tries to read or create global config at `/home/.config`, which is not accessible from worker processes. In fact I don't need  a logger during my inference so I want to avoid the logger instance being loaded or let the logger to look for global config from different path (e.g. current dir). How can I achieve this?

```
Traceback (most recent call last):
File "/data3/hadoop/yarn/local/usercache/chewie-park/appcache/application_1603778770965_1295035/container_e71_1603778770965_1295035_01_000038/./query_mapper.py", line 11, in <module>
import pytorch_lightning as pl
File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/__init__.py", line 63, in <module>
from pytorch_lightning.trainer import Trainer
File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/trainer/__init__.py", line 18, in <module>
from pytorch_lightning.trainer.trainer import Trainer
File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 32, in <module>
from pytorch_lightning.loggers import LightningLoggerBase
File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/loggers/__init__.py", line 59, in <module>
from pytorch_lightning.loggers.wandb import WandbLogger
File "/usr/local/lib/python3.6/site-packages/pytorch_lightning/loggers/wandb.py", line 26, in <module>
import wandb
File "/usr/local/lib/python3.6/site-packages/wandb/__init__.py", line 116, in <module>
api = InternalApi()
File "/usr/local/lib/python3.6/site-packages/wandb/apis/internal.py", line 17, in __init__
self.api = InternalApi(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 81, in __init__
load_settings=load_settings, root_dir=self.default_settings.get("root_dir")
File "/usr/local/lib/python3.6/site-packages/wandb/old/settings.py", line 25, in __init__
self._global_settings.read([Settings._global_path()])
File "/usr/local/lib/python3.6/site-packages/wandb/old/settings.py", line 105, in _global_path
util.mkdir_exists_ok(config_dir)
File "/usr/local/lib/python3.6/site-packages/wandb/util.py", line 632, in mkdir_exists_ok
os.makedirs(path)
File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
makedirs(head, mode, exist_ok)
File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/.config'
```

**Comment by awaelchli** [comment]
It looks like you can't do `import wandb` in that environment. Maybe it is something that should be reported to wandb? You could try to uninstall wandb, then it shouldn't lead to the import.

**Comment by awaelchli** [comment]
Did my suggestion work or did you find any other solution?
PL does not install wandb by default, it's an optional requirement. If wandb is available in the environment, Lightning will try to import it, this is simply becaue it is part of the "__init__.py" file of the loggers module. If the import fails, then there must be something wrong with the installation of wandb, or an unsupported platform.

**Comment by kyoungrok0517** [comment]
I think that worked. My colleague tried that and gave me no additional
feedback, likely because somehow succeeded in loading the model. Thanks for
the comment :)

2021년 1월 20일 (수) 오전 11:55, Adrian Wälchli <notifications@github.com>님이 작성:

**Comment by karthi0804** [comment]
Hi @awaelchli can u pls help me to solve this similar prob? I am using pytorch-lightning 1.2.6, torch 1.8.1 and wandb 0.10.23. I have disabled wandb while executing.
```
> /home/karthi/Documents/Work/sw/intentionprediction/main.py(1)<module>()
-> import matplotlib
(Pdb) b pl_module.py:87
Breakpoint 1 at /home/karthi/Documents/Work/sw/intentionprediction/pl_module.py:87
(Pdb) c
Global seed set to 0
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Global seed set to 0
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
Traceback (most recent call last):
  File "/usr/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/usr/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/karthi/Documents/Work/sw/intentionprediction/main.py", line 199, in <module>
    main()
  File "/home/karthi/Documents/Work/sw/intentionprediction/main.py", line 64, in main
    train(cp)
  File "/home/karthi/Documents/Work/sw/intentionprediction/main.py", line 113, in train
    trainer.fit(pl_model, train_dataloader=train_loader, val_dataloaders=[val_loader, tb_loader])
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 602, in run_train
    self._pre_training_routine()
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _pre_training_routine
    self.on_pretrain_routine_start(ref_model)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 130, in on_pretrain_routine_start
    callback.on_pretrain_routine_start(self, model)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 205, in on_pretrain_routine_start
    self.__resolve_ckpt_dir(trainer)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 464, in __resolve_ckpt_dir
    self._fs.makedirs(self.dirpath, exist_ok=True)
  File "/home/karthi/venv_lyft/lib/python3.7/site-packages/fsspec/implementations/local.py", line 40, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Vpo9UwBtb3a8vVzmkRdyGF'
Uncaught exception. Entering post mortem debugging
```

**Comment by awaelchli** [comment]
What did you pass to init? And what hyperparameters are you logging?
does wandb.init by itself work without Lightning?
Please provide instructions what I need to run to get this error.

**Comment by karthi0804** [comment]
> What did you pass to init? And what hyperparameters are you logging?
> does wandb.init by itself work without Lightning?
> Please provide instructions what I need to run to get this error.

@awaelchli Sorry for not being specific. Please find the details. When I initialize the trainer as specified below and debug using command line pdb, I get the error.
```
    from pytorch_lightning.loggers import WandbLogger
    trainer = pl.Trainer(gpus=0,
                         logger=WandbLogger(entity=wb_entity,
                                            project=wb_project,
                                            id=None ),
                         max_epochs=100,
                         resume_from_checkpoint=pretrained_chk_path,
                         weights_summary='full',
                         callbacks=[progressbar_callback, print_callback, checkpoint_callback],
                         plugins=[DDPPlugin(find_unused_parameters=True)])
```
The workaround that I do is: I initialize trainer (without Logger) by setting the  `profile` to `simple`, `fast_dev_run` to `True` and debug my code. I don't get any errors.
```
    trainer = pl.Trainer(gpus=0,
                         profiler='simple',
                         fast_dev_run=True,
                         weights_summary='full',
                         callbacks=[progressbar_callback, print_callback],
                         plugins=[DDPPlugin(find_unused_parameters=True)])
``` 
NOTE: wandb works well in **normal execution without pdb**. I log the losses, metrics, images, and videos. All works well.

**Comment by wuwo007** [comment]
@karthi0804  Hello, Have you solved the above problem? I encountered the same problem when using pytorch_lightning and pdb. Looking forward your reply.

**Comment by karthi0804** [comment]
> @karthi0804 Hello, Have you solved the above problem? I encountered the same problem when using pytorch_lightning and pdb. Looking forward your reply.

Hi, No. I still get an error when using pdb to debug. I have not tested the latest versions. As I mentioned above, I use the workaround for debugging. I think it is some problem with wandb integration with pl.

**Comment by awaelchli** [comment]
Hey guys! Sorry to reply delayed on this. Please if it's not too much to ask, open a new issue with your specific new problem since this issue here is a bit older. Make sure to provide all information to reproduce the issue, with a runnable code example. Since it is a third-party integration problem, it is important for us to reproduce this or we won't be able to help much. Thank you for the help.

**Comment by ForrestPi** [comment]
how to slove the problem?
