### ISSUE TITLE
dp + manual_optimization is not working on PL 1.2.1

### ISSUE THREAD

**Issue by okojoalg** [PyTorchLightning/pytorch-lightning#6348]
## 🐛 Bug

dp + manual optimization is not working on PL 1.2.1
I am setting automatic optimization = False in my model and giving `Trainer()` `accelerator='dp'`

### Expected behavior
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 492, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 653, in run_training_batch
    self._curr_step_result = self.training_step(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 293, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 157, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/dp.py", line 61, in training_step
    return self.model(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/usr/local/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/overrides/data_parallel.py", line 74, in forward
    output = super().forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 48, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/workdir/flow-based-test/StableGlowModel.py", line 131, in training_step
    opt.step()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 219, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 135, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 278, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 283, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 160, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/optim/adamax.py", line 67, in step
    exp_avg, exp_inf = state['exp_avg'], state['exp_inf']
KeyError: 'exp_avg'
```

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by awaelchli** [comment]
thanks for reporting this
is this reproducible with the bug_report_model?

**Comment by okojoalg** [comment]
thanks for your comment.
it took time to reproduce the bug report with a simple model.
we can reproduce it with the following model.

``` python
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
import torchvision
import torchvision.datasets as datasets
import pytorch_lightning as pl
from pytorch_lightning.utilities.seed import seed_everything


class Model(pl.LightningModule):

    def __init__(self, channel=3):
        super(Model, self).__init__()
        self.automatic_optimization = False
        self.nn = nn.Sequential(*[nn.Conv2d(channel, channel, 1) for _ in range(32)])

    def forward(self, input):
        z = self.nn(input)
        return z

    def configure_optimizers(self):
        optimizer = torch.optim.Adamax(self.parameters(), lr=1e-4)
        return [optimizer]

    def training_step(self, batch, batch_idx):
        z = self(batch[0])
        loss = torch.nn.functional.mse_loss(z, batch[0])
        opt = self.optimizers()
        self.manual_backward(loss, opt)
        opt.step()
        opt.zero_grad()


if __name__ == '__main__':
    train_ds = datasets.CIFAR10(
        root='/data',
        train=True,
        download=True,
        transform=torchvision.transforms.Compose([
            torchvision.transforms.ToTensor(),
        ]))

    train_dl = DataLoader(
        train_ds,
        shuffle=True,
        batch_size=32,
        num_workers=8,
        drop_last=True)

    trainer_kwargs = {
        'gpus': 2,
        'accelerator': 'dp',
    }

    seed_everything(42)
    model = Model()
    trainer = pl.Trainer(**trainer_kwargs)
    trainer.fit(model, train_dl)
```

**Comment by awaelchli** [comment]
thanks for the repro script, very helpful. So far what I have observed is that the failure is random!

**Comment by awaelchli** [comment]
Hi, I found out why this happens. In Lightning, the training_step runs inside the DataParallel.forward, which means this runs on the replicas. But the DP replicas don't maintain state from the root device, therefore it gives a KeyError. For reference, I made a pure PyTorch example: 

```python
import torch
import torch.nn as nn


class Model(nn.Module):

    def __init__(self, channel=3):
        super(Model, self).__init__()
        self.nn = nn.Sequential(*[nn.Conv2d(channel, channel, 1) for _ in range(32)])
        self.optimizer = torch.optim.Adamax(self.parameters(), lr=1e-4)

    def forward(self, input):
        z = self.nn(input)
        z.sum().backward()
        self.optimizer.step()
        self.optimizer.zero_grad()
        return z

    def training_step(self, batch, batch_idx):
        z = self(batch[0])
        loss = torch.nn.functional.mse_loss(z, batch[0])
        opt = self.optimizers()
        self.manual_backward(loss, opt)
        opt.step()
        opt.zero_grad()


if __name__ == '__main__':
    device = torch.device("cuda", 0)
    model = Model().to(device)
    model = nn.DataParallel(model, device_ids=[0, 1])
    model(torch.rand(2, 3, 5, 5).to(device))
```

Adamax has a state, but it does not get copied to the replicas. Same with other optimizers like Adam. 
If you try SGD (which doesn't maintain state) you will see it works.


I don't see an obvious way to fix this, as this is how DP is implemented in PyTorch. I believe the best we can do is bring awareness in our docs that DP does not maintain state. And this is not just specific to the optimizers here. Any state assigned to the module will be discarded outside the replicas.
I hope this answer helps and sorry for the delay.

**Comment by bestpredicts** [comment]
mark
