### ISSUE TITLE
fit hangs on single GPU

### ISSUE THREAD

**Issue by fonnesbeck** [PyTorchLightning/pytorch-lightning#6381]
## 🐛 Bug

I have a relatively simple model that I am trying to fit using a GPU (both on AWS and Colab):

```python
model = nn.Sequential(
    nn.Linear(len(predictors), 128),
    nn.ReLU(),
    nn.Linear(128, 128),
    nn.Dropout(0.4),
    nn.ReLU(),
    nn.Linear(128, 1)
)

regression = Task(model, loss_fn=nn.functional.mse_loss, optimizer=optim.Adam)
```

I'm fitting it using the following command:

```python
pl.Trainer(gpus=1, num_sanity_val_steps=0).fit(
    regression, 
    DataLoader(train_data, batch_size=32, num_workers=4), 
    DataLoader(test_data, batch_size=32, num_workers=4))
```

where the my dataset uses FloatTensors that are sent to `cuda()`. 

```python
class PitchDataset(Dataset):
    
    def __init__(self, df, subset_n=None):
        if subset_n:
            self.data = df.sample(subset_n).reset_index()
        else:
            self.data = df.reset_index()

        self.data -= self.data.mean()
        self.data /= self.data.std()

    def __len__(self):
        return self.data.shape[0]
    
    def __getitem__(self, index):
        X = self.data.loc[index, predictors].values
        y = self.data.loc[index, ['arv']]
            
        return FloatTensor(X).cuda(), FloatTensor(y).cuda()
```

However, when run it hangs before the first epoch:

<img width="579" alt="Screen Shot 2021-03-06 at 2 56 47 PM" src="https://user-images.githubusercontent.com/81476/110220592-3da9ee00-7e8c-11eb-8df5-fd0909748b75.png">

When I don't use the GPU, it runs fine. If I remove `num_sanity_val_steps=0` then it hangs on the sanity check.

### Environment

I've tried this both on Colab and on an AWS Deep Learning AMI with one GPU. 

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Debian
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8.6 (AWS), 3.7 (Colab)
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Tesla K80 (AWS), Tesla P100-PCIE-16GB (Colab)

**Comment by awaelchli** [comment]
`return FloatTensor(X).cuda(), FloatTensor(y).cuda()` in your dataset looks suspicious. This shouldn't be in the dataset code (also PyTorch does not recommend this). 

Remove it and try again.

**Comment by awaelchli** [comment]
Can you please attach a small runnable code sample using our bug report template? I can't reproduce this with just the snippets that you have provided. Thanks

**Comment by awaelchli** [comment]
Hello again, any updates here? Were you able to find the problem in the meantime?

**Comment by fonnesbeck** [comment]
I was not able to, no. I have just been running it on CPU.

**Comment by awaelchli** [comment]
If I try to replicate your example I get the error:

```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "repro12.py", line 15, in __getitem__
    return torch.FloatTensor(data).cuda()
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/torch/cuda/__init__.py", line 160, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```
Which makes sense because we have `num_workers > 0` and try to move tensors to CUDA in the dataloader worker:

```python 
import os
import torch
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        data = self.data[index]
        return torch.FloatTensor(data).cuda()

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=4)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=4)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=4)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=2,
        max_epochs=1,
        gpus=1,
        weights_summary=None,
    )
    trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)
    trainer.test(model, test_dataloaders=test_data)


if __name__ == '__main__':
    run()
```
Please let me know what I can do to reproduce it.

**Comment by awaelchli** [comment]
It's possible that your dataloader workers are stalling. Please try `num_workers=0` and see if that solves the hang.

**Comment by fonnesbeck** [comment]
Yeah, that works. Thanks.

**Comment by xiaoyang-RL9** [comment]
It really works. Thanks a lot! It is indeed the datasets are set wrong. Just re-write the Dataset and the Dataloader with a popular example.
