### ISSUE TITLE
Random job failures caused by the CheckpointConnector on slurm managed hpc

### ISSUE THREAD

**Issue by dln22** [PyTorchLightning/pytorch-lightning#6544]
## 🐛 Bug

I recently created a small machine learning code using `Pytorch-lightning and Optuna`. The code allows to train and hyper-optimise a number of pre-selected models for a particular purpose. The Optuna hyper-parameter optimisation trials are stored in sqlite file (this is one of the storage options allowed by Optuna). Everything works fine if I run it on a non-slurm managed computing system. However, the moment I run it on slurm platform, my jobs crash randomly (sometimes they run to completion and sometimes they crash straight away). I have checked that it has nothing to do with how many parallel jobs I run, as even a single job can crash. Examining the Python traceback (please see the traceback below), I could see that the issue happens in the `trainer/connectors/checkpoint_connector.py` module. Namely, in the `CheckpointConnector.restore_weights` method at the following line of code:
```python
did_restore_hpc_weights = self.restore_hpc_weights_if_needed(model)
```
The exact error message says that no database journal file can be found. I am no sqlite expert, but I think the journal files are created during transactions as a backup option in case something goes wrong and are destroyed afterwards. I am not sure why pytorch-ligthning tries to use them. Apart from that, I have noticed that If I run a number of jobs in parallel, where the jobs are disjoint and each using a different sqlite file, if one job crashes the other crash as well. This is very weird given that the jobs should be completely separate. I managed to find a workaround for this issue by modifying the `CheckpointConnector.restore_weights` method as follows:
```python
        # if script called from hpc resubmit, load weights
        #did_restore_hpc_weights = self.restore_hpc_weights_if_needed(model)
        did_restore_hpc_weights = False
```

This seems to fix the random jobs crash problem, though I am not sure if there are any side-effects. Howevr, all my jobs train and optimise fine with the above addition. I would welcome any comments, it could be that the actual issue is located elsewhere (e.g. Optuna), but I thought it is important to post it here. Please see below additional details:

- OS - Linux
- conda environment:
    - name: osc_env
    - channels:
        - rdkit
       - defaults
       - pytorch
       - dglteam
    - dependencies:
        - python=3.7.7
        - pytorch=1.6.0
        - torchvision=0.7.0
        - torchaudio=0.6.0
        - cudatoolkit=10.2
        - rdkit=2020.09.1.0
        - dgl-cuda10.2=0.5.2
        - pip=20.2.4
    - pip:
        - pytorch_lightning==1.0.4
        - scikit-learn==0.23.2
        - tqdm==4.51.0
        - pyyaml==5.3.1
        - networkx==2.5
        - matplotlib==3.3.2
        - seaborn==0.11.0
       - optuna==2.3.0
       - dgllife==0.2.6

- traceback
```
2021-03-16 09:24:59,517 ERROR    finished with exception - optunawrapper.py 111  start_hpo root [[MainThread]]
Traceback (most recent call last):
  File "/rds/user/dln22/hpc-work/ML_jobs/ZhouLiML-git/oscml/hpo/optunawrapper.py", line 91, in start_hpo
    gc_after_trial=True)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/optuna/study.py", line 315, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/optuna/_optimize.py", line 114, in _optimize
    for _ in _iter
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/optuna/_optimize.py", line 156, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/optuna/_optimize.py", line 189, in _run_trial
    value = func(trial)
  File "/rds/user/dln22/hpc-work/ML_jobs/ZhouLiML-git/oscml/hpo/optunawrapper.py", line 25, in decorator
    raise exc
  File "/rds/user/dln22/hpc-work/ML_jobs/ZhouLiML-git/oscml/hpo/optunawrapper.py", line 16, in decorator
    value = objective(trial)
  File "/rds/user/dln22/hpc-work/ML_jobs/ZhouLiML-git/oscml/hpo/objective.py", line 230, in objective
    trial, trial_number, total_number_trials, str(cv_index))
  File "/rds/user/dln22/hpc-work/ML_jobs/ZhouLiML-git/oscml/hpo/objective.py", line 107, in fit_or_test
    trainer.fit(model, train_dataloader=train_dl, val_dataloaders=val_dl)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 440, in fit
    results = self.accelerator_backend.train()
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 45, in train
    self.trainer.train_loop.setup_training(model)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 165, in setup_training
    self.trainer.checkpoint_connector.restore_weights(model)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 67, in restore_weights
    did_restore_hpc_weights = self.restore_hpc_weights_if_needed(model)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 198, in restore_hpc_weights_if_needed
    files = [os.path.basename(f['name']) for f in fs.listdir(folderpath)]
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/fsspec/spec.py", line 1081, in listdir
    return self.ls(path, detail=detail, **kwargs)
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/fsspec/implementations/local.py", line 50, in ls
    return [self.info(f) for f in paths]
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/fsspec/implementations/local.py", line 50, in <listcomp>
    return [self.info(f) for f in paths]
  File "/home/dln22/.conda/envs/osc_env/lib/python3.7/site-packages/fsspec/implementations/local.py", line 60, in info
    out = os.stat(path, follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory: '/rds/user/dln22/hpc-work/ML_jobs/ZhouLiML-git/m3_atfp_hopv15.db-journal'
```

**Comment by tchaton** [comment]
Dear @dln22,

Could you share a reproducible script which fails sometimes with the BoringModel ?

Best,
T.C

**Comment by edenlightning** [comment]
Please feel free to reopen with a reproducible example.

**Comment by championsnet** [comment]
I am getting the same error occasionally. Did you find any solutions?
