### ISSUE TITLE
Possible race condition when trying to save and access checkpoints with 12 GPUs across 2 nodes

### ISSUE THREAD

**Issue by amorehead** [PyTorchLightning/pytorch-lightning#6700]
## 🐛 Bug

Hello.

I have recently been trying to get a simple MNIST image classifier up and running with Lightning and Weights and Biases's WandbLogger for Lightning, but I have been encountering an odd issue lately. When I launch my Lightning script on my GPU computing cluster with 2 GPU nodes with 6 GPUs each (i.e. DDP - 12 GPUs total, with 42 CPU cores allocated to each node as dataloader workers), my model completes a handful of epochs, say 3, before it initiates early stopping and begins to save "several" checkpoints. (As an aside, I was also curious why it looks like duplicate checkpoints are getting created for each GPU, but we can come back to this later.)

When my job goes to call Trainer.test(), it crashes saying that it was expecting a certain checkpoint to be written to disk already so it can load that one for testing, but the checkpoint does not appear to the underlying OS as though it was written beforehand, thus causing a FileNotFoundError. To me, unless I'm simply misunderstanding how to accommodate multiple GPUs and nodes for checkpointing followed by testing, this seems like it may be a race condition happening between job threads. Any thoughts or ideas as to what may be going on here? Below is my entire image classifier training script contained in a fork of the PL project template. Below is my stack trace for the missing file error. I should mention that the checkpoints that are listed in the FileNotFoundErrors are, in fact, not being written to disk (something I verified manually after the job crashed).

Also, thank you in advance for your time and help!

GitHub Fork of PL Project Template:
https://github.com/amorehead/deep-learning-hpc-project-template/blob/master/project/lit_image_classifier.py # training script
https://github.com/amorehead/deep-learning-hpc-project-template/blob/master/train.bash # script for executing lit_image_classifier.py on cluster

Stack Trace:
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine/bip198/scratch/acmwhb/Repositories/Personal_Repositories/deep-learning-hpc-project-template/project/checkpoints/LitClassifier-epoch=03-val_au
roc=0.89-v6.ckpt'
Traceback (most recent call last):
File "/gpfs/alpine/bip198/scratch/acmwhb/Repositories/Personal_Repositories/deep-learning-hpc-project-template/project/lit_image_classifier.py", line 189, in
cli_main()
File "/gpfs/alpine/bip198/scratch/acmwhb/Repositories/Personal_Repositories/deep-learning-hpc-project-template/project/lit_image_classifier.py", line 179, in cli_main
result = trainer.test(test_dataloaders=test_loader)
File "/gpfs/alpine/scratch/acmwhb/bip198/Repositories/Personal_Repositories/deep-learning-hpc-project-template/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 916, in test
results = self.__test_using_best_weights(ckpt_path, test_dataloaders)
File "/gpfs/alpine/scratch/acmwhb/bip198/Repositories/Personal_Repositories/deep-learning-hpc-project-template/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 946, in _test_using
best_weights
ckpt = pl_load(ckpt_path, map_location=lambda storage, loc: storage)
File "/gpfs/alpine/scratch/acmwhb/bip198/Repositories/Personal_Repositories/deep-learning-hpc-project-template/venv/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py", line 31, in load
with fs.open(path_or_url, "rb") as f:
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/spec.py", line 943, in open
**kwargs,
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/implementations/local.py", line 118, in _open
return LocalFileOpener(path, mode, fs=self, **kwargs)
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/implementations/local.py", line 200, in init
self._open()
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/implementations/local.py", line 205, in _open
self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine/bip198/scratch/acmwhb/Repositories/Personal_Repositories/deep-learning-hpc-project-template/project/checkpoints/LitClassifier-epoch=03-val_au
roc=0.90-v6.ckpt'
Global seed set to 42
Traceback (most recent call last):
File "/gpfs/alpine/bip198/scratch/acmwhb/Repositories/Personal_Repositories/deep-learning-hpc-project-template/project/lit_image_classifier.py", line 189, in
cli_main()
File "/gpfs/alpine/bip198/scratch/acmwhb/Repositories/Personal_Repositories/deep-learning-hpc-project-template/project/lit_image_classifier.py", line 179, in cli_main
result = trainer.test(test_dataloaders=test_loader)
File "/gpfs/alpine/scratch/acmwhb/bip198/Repositories/Personal_Repositories/deep-learning-hpc-project-template/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 916, in test
results = self.__test_using_best_weights(ckpt_path, test_dataloaders)
File "/gpfs/alpine/scratch/acmwhb/bip198/Repositories/Personal_Repositories/deep-learning-hpc-project-template/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 946, in _test_using
best_weights
ckpt = pl_load(ckpt_path, map_location=lambda storage, loc: storage)
File "/gpfs/alpine/scratch/acmwhb/bip198/Repositories/Personal_Repositories/deep-learning-hpc-project-template/venv/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py", line 31, in load
with fs.open(path_or_url, "rb") as f:
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/spec.py", line 943, in open
**kwargs,
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/implementations/local.py", line 118, in _open
return LocalFileOpener(path, mode, fs=self, **kwargs)
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/implementations/local.py", line 200, in init
self._open()
File "/ccs/home/acmwhb/.local/lib/python3.6/site-packages/fsspec/implementations/local.py", line 205, in _open
self.f = open(self.path, mode=self.mode)

### Expected behavior

I should be able to run a simple MNIST training example (i.e. https://github.com/amorehead/deep-learning-hpc-project-template/blob/master/project/lit_image_classifier.py and https://github.com/amorehead/deep-learning-hpc-project-template/blob/master/train.bash) with multiple GPUs distributed across more than one GPU node (with 6 GPUs per node).

### Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Red Hat Enterprise Linux Server release 7.6 (Maipo)
 - How you installed PyTorch (`conda`, `pip`, source): Source
 - Build command you used (if compiling from source): Very custom (i.e. https://github.com/open-ce/pytorch-feedstock and https://github.com/open-ce/pytorch-lightning-feedstock)
 - Python version: 3.6.12
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Tesla V100-SXM2-16GB
 - Any other relevant information: Running on Oak Ridge National Laboratory's Summit compute system

### Additional context

I am not sure if Lightning's automatic checkpointing mechanism has been tested with multi-GPU node, multi-GPU configurations on a custom PowerPC architecture before, so this may be (although hopefully is not) a unique issue.

**Comment by awaelchli** [comment]
If you can confirm that this is unrelated to multi-node, just multi-gpu, I can probably take a look. 
Unfortunately you did not include the Lightning that you have installed. Are you running the latest?

**Comment by amorehead** [comment]
@awaelchli,

This issue is occurring when using multiple GPUs on a single node and also when using multiple GPUs across multiple nodes. And yes, I am running the latest dev version of Lighting (i.e. 1.3.0dev).

Thank you in advance for your time and help.

**Comment by amorehead** [comment]
Update: Not using the sync_dist flag in my self.log() calls appears to have been the root issue. I've been using this flag in other projects of mine, but none that have been run with multiple GPUs (yet).
