### ISSUE TITLE
AttributeError: 'DataModule' object has no attribute 'has_teardown_None'

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#7286]
## 🐛 Bug

AttributeError: 'DataModule' object has no attribute 'has_teardown_None'

Happens when Ctrl+C a GPU training script. 

### To Reproduce

1. `git checkout b6706470c1e7a1db47f5dc2440fe3b970bdf209c` (current master)
2. `python pl_examples/basic_examples/simple_image_classifier.py --trainer.gpus 1`
3. press Ctrl+C

Error:
```
^C/home/adrian/repositories/pytorch-lightning/pytorch_lightning/utilities/distributed.py:69: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  warnings.warn(*args, **kwargs)
Traceback (most recent call last):
  File "pl_examples/basic_examples/simple_image_classifier.py", line 86, in <module>
    cli_main()
  File "pl_examples/basic_examples/simple_image_classifier.py", line 79, in cli_main
    cli = LightningCLI(LitClassifier, MNISTDataModule, seed_everything_default=1234)
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/utilities/cli.py", line 174, in __init__
    self.fit()
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/utilities/cli.py", line 264, in fit
    self.trainer.fit(**self.fit_kwargs)
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 858, in fit
    self._launch(model, train_dataloader=train_dataloader, val_dataloaders=val_dataloaders, datamodule=datamodule)
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 494, in _launch
    self.call_teardown_hook(model)
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1141, in call_teardown_hook
    called = getattr(self.datamodule, f'has_teardown_{state}')
AttributeError: 'MNISTDataModule' object has no attribute 'has_teardown_None'
Exception ignored in: <function tqdm.__del__ at 0x7f4b56365a60>
Traceback (most recent call last):
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/tqdm/std.py", line 1299, in close
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/tqdm/std.py", line 1492, in display
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __str__
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/tqdm/std.py", line 1450, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```

### Expected behavior

No error.

### Environment

* CUDA:
        - GPU:
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.20.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1+cu111
        - pytorch-lightning: 1.3.0rc2
        - tqdm:              4.60.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.8
        - version:           #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020

**Comment by ananthsub** [comment]
I think @carmocca is working on this with https://github.com/PyTorchLightning/pytorch-lightning/pull/7173

**Comment by carmocca** [comment]
That's correct! Thanks for pinging

**Comment by awaelchli** [comment]
Ok, but no duplicate right?
Is the refactor required or can we bring this fix in for 1.3? I have not yet looked closely what the issue is.

**Comment by carmocca** [comment]
> Ok, but no duplicate right?

This was reported in Slack and lazy me didn't create an issue and jumped straight into fixing it 😝 

> Is the refactor required or can we bring this fix in for 1.3?

The refactor is required and I would like that it makes it to 1.3, this way we don't have to worry about conflicts for the 1.4 bugfix releases.

**Comment by GuillaumeTong** [comment]
Hi, is there a temporary workaround for this issue in 1.3.0rc1? Such as maybe defining a dummy 'has_teardown_None' attribute for our datamodule? We have come to rely on some of the new features in 1.3 and cannot easily downgrade but would like to avoid waiting as much as possible.
Thank you

**Comment by carmocca** [comment]
@GuillaumeTong we plan to include #7173 into 1.3 which should fix it. 

> Such as maybe defining a dummy 'has_teardown_None' attribute for our datamodule? 

Yes, this workaround would work.

`self.has_teardown_None = False`
