### ISSUE TITLE
`log_gpu_memory='all'` options raise Error in python3.6.9. (TypeError: __init__() got an unexpected keyword argument 'capture_output')

### ISSUE THREAD

**Issue by ssaru** [PyTorchLightning/pytorch-lightning#735]
### Common bugs:
1. Tensorboard not showing in Jupyter-notebook see [issue 79](https://github.com/PyTorchLightning/pytorch-lightning/issues/79).    
2. PyTorch 1.1.0 vs 1.2.0 support [see FAQ](https://github.com/PyTorchLightning/pytorch-lightning#faq)    

### To Reproduce

1. Trainer options `log_gpu_memory='all'`
2. Run `trainer.fit()`
3. See error

```
Epoch 1:   0%|                                   | 1/1407 [00:03<1:18:10,  3.34s/batch, batch_nb=0, gpu=0, loss=0.566, v_nb=3]Traceback (most recent call last):
  File "train.py", line 100, in <module>
    train(dataset_root)
  File "train.py", line 91, in train
    trainer.fit(model)
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 351, in fit
    self.single_gpu_train(model)
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/trainer/dp_mixin.py", line 77, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 471, in run_pretrain_routine
    self.train()
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/trainer/train_loop_mixin.py", line 60, in train
    self.run_training_epoch()
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/trainer/train_loop_mixin.py", line 126, in run_training_epoch
    self.log_metrics(batch_step_metrics, grad_norm_dic)
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/trainer/logging_mixin.py", line 20, in log_metrics
    mem_map = memory.get_memory_profile(self.log_gpu_memory)
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/root_module/memory.py", line 200, in get_memory_profile
    memory_map = get_gpu_memory_map()
  File "/home/ubuntu/Documents/dev/keti-bio/contraction_detector/env/lib/python3.6/site-packages/pytorch_lightning/root_module/memory.py", line 228, in get_gpu_memory_map
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

#### Code sample

```
trainer = Trainer(early_stop_callback=earlystopping_callback,
                      checkpoint_callback=checkpoint_callback,
                      gpus=1,
                      log_gpu_memory='all',
                      min_nb_epochs=1,
                      max_nb_epochs=10,
                      train_percent_check=1,
                      test_percent_check=1,
                      val_percent_check=1,
                      nb_sanity_val_steps=0)
    trainer.fit(model)
```

### Expected behavior
Just train with progress bar

### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 430.26
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] pytorch-lightning==0.5.3.2
[pip3] torch==1.4.0
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.5.0
[conda] Could not collect
```

i find some site. in python3.6 **`capture_output` parameter does not exist.**

https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output/53209196

**Comment by awaelchli** [comment]
Hi, this should be fixed on master and is now backward compatible with Python 3.6. 
See [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/7de51f78ac2ec09b230e1cb8a786f872de3b861f/pytorch_lightning/core/memory.py#L269).

**Comment by awaelchli** [comment]
@Borda can be closed I think :)
