### ISSUE TITLE
stochastic_weight_avg not working - ` can't pickle _thread.lock objects`

### ISSUE THREAD

**Issue by tetapunto** [PyTorchLightning/pytorch-lightning#7379]
Hi all, 
I am having an issue when try to use stochastic_weight_avg inside Trainer.

Below some parts of my code, that work without any issues on multi gpu if stochastic_weight_avg =False

```python
    loggers = [
        TensorBoardLogger(save_dir=default_root_dir, name="lightning_logs"),
        aml_logger,
    ]
    
    checkpoint_callback = ModelCheckpoint(
        dirpath="./outputs",
        save_top_k=1,
        verbose=True,
        monitor="mAP",
        mode="max",
        prefix="",
    )
    
    early_stop = EarlyStopping(
        monitor="val_loss", patience=patience, strict=False, verbose=False, mode="min"
    )
    
    trainer_kwargs = {
        "fast_dev_run": False,
        "default_root_dir": '/outputs/',
        "gpus": [1, 2, 3, 4],
        "num_sanity_val_steps": 1,
        "deterministic": True,
        "max_epochs": 30,
        "accumulate_grad_batches": 1,
        "distributed_backend": 'ddp',
        "replace_sampler_ddp": False,
        "reload_dataloaders_every_epoch": True,
        'precision': 16,
        'amp_backend': 'native',
        'stochastic_weight_avg': True
    
    }
    trainer = Trainer(
        logger=loggers,
        callbacks=[early_stop, checkpoint_callback],
        **trainer_kwargs,
    )
    
    model = MyModel(
        train_df=train_df, valid_df=valid_df,
        **model_kwargs
    )
    
    log.info("Starting training...")
    trainer.fit(model)
    log.info("Finished training")
    torch.save(model.model.state_dict(), model_out_path)
```

when I set stochastic_weight_avg, I face this error:
```
`Traceback (most recent call last):
  File "train.py", line 45, in <module>
    stochastic_weight_avg: Param("activate stochastic_weight_avg or not", type=bool) = False,
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/site-packages/fastscript/core.py", line 79, in call_parse
    return _f()
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "train.py", line 153, in main
    trainer.fit(model)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 459, in fit
    self.call_hook("on_before_accelerator_backend_setup", model)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1095, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 35, in on_before_accelerator_backend_setup
    callback.on_before_accelerator_backend_setup(self, model)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/site-packages/pytorch_lightning/callbacks/swa.py", line 142, in on_before_accelerator_backend_setup
    self._average_model = deepcopy(pl_module)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 216, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/svision-devuser/.azureml/envs/azureml_a3c17fde7d5c8e74dac8e0694ed6410d/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects`
```

**Comment by tchaton** [comment]
Dear @tetapunto,

Would you mind reproducing this behaviour with the boring Model and collecting your environment.

Best,
T.C
