### ISSUE TITLE
How to save model weights to mlflow tracking server while using MLFLogger to save metrics.

### ISSUE THREAD

**Issue by yudai09** [PyTorchLightning/pytorch-lightning#741]
## ❓ Questions and Help

Anybody knows simple way to accomplish it?
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I'm searching for a way to save model weights to mlflow tracking server while using `MLFLogger` to save metrics.
my problem is, I cannot find a way to save model weight to same `run` which was created inside  MLFLogger.
When I run `mlflow.pytorch.log_model()` after `trainer.fit()`,  metrics and model weight are saved to different run.

#### Code

  
```
    mlf_logger = MLFlowLogger(
        experiment_name="WatchNetExperiment",
    )

    trainer = pl.Trainer(gpus=hparams.gpus, distributed_backend='dp', min_nb_epochs=hparams.min_epochs, max_nb_epochs=hparams.max_epochs, logger=mlf_logger)
    trainer.fit(model)
    mlflow.pytorch.log_model(model.model, "my_model")
```

#### What have you tried?

To work around the problem, I stopped to use MLFLogger and modify my training code to save metrics at `train_step()` and `validation_end`.

#### What's your environment?

 - OS: Linux
 - Packaging conda
 - Version 0.5.3.2

**Comment by williamFalcon** [comment]
@neggert ?

**Comment by festeh** [comment]
@yudai09  try `mlflow.pytorch.log_model(model.model, "my_model", run_id=mfl_logger.run_id)`

**Comment by yudai09** [comment]
@festeh thank you. it works.

**Comment by nsidn98** [comment]
> @yudai09 try `mlflow.pytorch.log_model(model.model, "my_model", run_id=mfl_logger.run_id)`

This isn't working. Getting the following error:
```
Traceback (most recent call last):
  File "pythor/RL/Value/value_algos.py", line 276, in <module>
    main(args)
  File "pythor/RL/Value/value_algos.py", line 243, in main
    trainer.fit(model)
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 887, in fit
    self.run_pretrain_routine(model)
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1015, in run_pretrain_routine
    self.train()
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 376, in train
    self.run_training_teardown()
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 668, in run_training_teardown
    self.on_train_end()
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/trainer/callback_hook.py", line 53, in on_train_end
    callback.on_train_end(self, self.get_model())
  File "/Users/Downloads/PyThor/pythor/bots/rlCallback.py", line 51, in on_train_end
    mlflow.pytorch.log_model(pl_module.net, "my_model",run_id=pl_module.logger.run_id)
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/mlflow/pytorch/__init__.py", line 158, in log_model
    registered_model_name=registered_model_name, **kwargs)
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/mlflow/models/__init__.py", line 101, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Users/opt/miniconda3/envs/py36/lib/python3.6/site-packages/mlflow/pytorch/__init__.py", line 249, in save_model
    torch.save(pytorch_model, model_path, pickle_module=pickle_module, **kwargs)
TypeError: save() got an unexpected keyword argument 'run_id'
```

**Comment by yudai09** [comment]
@nsidn98 sorry, I was wrong. I replied `it works` without confirming.
After that, I tried it by myself and noticed it do not work and wrote the following code to workaround the problem.
https://gitlab.com/chowagiken/mlflow_with_pytorch_lightning/-/blob/master/train.py#L43
```
    # log model to MLFLow tracking server
    with TemporaryDirectory() as tdname:
        pytorch_model_path = os.path.join(tdname, "my_model")
        mlflow.pytorch.save_model(module.model, pytorch_model_path)
        client = mlflow.tracking.MlflowClient()
        client.log_artifact(mlf_logger._run_id, pytorch_model_path)
```
1. save model weights to temporal file path.
2. create a new mlflow client
3. save artifact via the client using run_id that was used during trainings.

I know it's just a workaround and not straight forward way to log the model weight.

**Comment by jedrzejkozal** [comment]
I think you can avoid creating TemporaryDirectory by calling log_model in context manger with proper run id set:
```
with mlflow.start_run(run_id=mlf_logger.run_id):
    mlflow.pytorch.log_model(model.model, "my_model")
```

**Comment by davidefiocco** [comment]
@yudai09 can you reopen this as this doesn't look solved to me? Current solutions seem workarounds. I tried to make use of them but with no success.

**Comment by zacharymostowsky** [comment]
Hey all - I was having the same problem. My solution was to explicitly set the `run_id` attribute on the `MLFlowLogger`. It seems like we should be able to pass this into `__init__()`. If you dig into the `MLFlowLogger.experiment()` method you'll find that the run_id will always be None the first time anything is logged.

```
experiment_name = 'test'
experiment = mlflow.get_experiment_by_name(experiment_name)
exp_id = experiment.experiment_id if experiment else mlflow.create_experiment(experiment_name)

with mlflow.start_run(experiment_id=exp_id) as run:
    run_id = run.info.run_id
    print(f'Run ID: {run_id}')

    mlf_logger = MLFlowLogger(
        experiment_name=experiment_name,
        tracking_uri=tracking_uri
    )
    
    # ** We need to explicitly set this to log to the same run opened in the notebook **
    mlf_logger._run_id = run_id

    trainer = pl.Trainer(logger=mlf_logger)

    trainer.fit(model, datamodule=data_module)  # Data Module defined outside this scope
```

**Comment by zacharymostowsky** [comment]
I will add that I have been unable to use `MLFlowLogger.log_model()` or `MLFlowLogger.experiment.log_model()`. Neither method seems to exist. I currently have to use `mlflow.pytorch.log_model()` which logs to the correct run still but I would like to just use the `MLFlowLogger` over the `mlflow` library directly.

**Comment by pocca2048** [comment]
@zacharymostowsky `self.logger.experiment` returns a `MlflowClient` and `log_model` is in `mlflow.pytorch.log_model()`. So you can't use `log_model` there...
I think [mlflow documentation](https://mlflow.org/docs/latest/python_api/mlflow.pytorch.html#module-mlflow.pytorch) is more useful than pytorch-lightning documentation.

**Comment by piseabhijeet** [comment]
> I will add that I have been unable to use `MLFlowLogger.log_model()` or `MLFlowLogger.experiment.log_model()`. Neither method seems to exist. I currently have to use `mlflow.pytorch.log_model()` which logs to the correct run still but I would like to just use the `MLFlowLogger` over the `mlflow` library directly.

Hi @zacharymostowsky 

I agree with you. Also there are some pytorch lighning models which mlflow cannot log and gives me this error:
![image](https://user-images.githubusercontent.com/57705684/131974620-8b149aab-19bd-441d-a4ee-dfd59b681d90.png)

i suspect models should be inherited from nn.module class and not pytorch lightning. Any idea?

**Comment by ericjmcd** [comment]
I just came across this issue now and this thread helped me to a better? solution.  Digging through the code there is a check for MLFLOW_RUN_ID env var so I'm going with:
```
os.environ['MLFLOW_RUN_ID'] = trainer.logger.run_id  # Hack to force MLFlow to 'know' about this run
mlflow.pytorch.log_model(trainer.model.model, "models")
```

MLFlow's fluent.py has:
```
client = MlflowClient()
if run_id:
    existing_run_id = run_id
elif _RUN_ID_ENV_VAR in os.environ:   # _RUN_ID_ENV_VAR is defined as "MLFLOW_RUN_ID"
    existing_run_id = os.environ[_RUN_ID_ENV_VAR]
    del os.environ[_RUN_ID_ENV_VAR]
else:
    existing_run_id = None
```

**Comment by chikubee** [comment]
@ZhangHangjianMA / @zacharymostowsky 
I tried exactly the solution you suggested but that does not work for me. 
I get Run not found error. 

```
(mlflow_demos) ankitamakker@Ankitas-MacBook-Pro mlops % python3.7 cifar_train_mlflow.py --exp-name cifar_mlflow_model --num-epochs 1 --datamodule-path cifar10/datamodule
Run id:  9202f6188a43411a9ecd08da0a0bcae7
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name       | Type             | Params
------------------------------------------------
0 | _model     | VGG              | 134 M 
1 | _criterion | CrossEntropyLoss | 0     
------------------------------------------------
134 M     Trainable params
0         Non-trainable params
134 M     Total params
537.206   Total estimated model params size (MB)
Traceback (most recent call last):
  File "cifar_train_mlflow.py", line 65, in <module>
    main(args)
  File "cifar_train_mlflow.py", line 44, in main
    trainer.fit(cifar_module, cifar_datamodule)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 583, in fit
    self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run
    self._log_hyperparams()
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1117, in _log_hyperparams
    logger.log_hyperparams(hparams_initial)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/lightning_utilities/core/rank_zero.py", line 24, in wrapped_fn
    return fn(*args, **kwargs)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/loggers/mlflow.py", line 231, in log_hyperparams
    self.experiment.log_param(self.run_id, k, v)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/loggers/logger.py", line 53, in experiment
    return get_experiment() or DummyExperiment()
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/lightning_utilities/core/rank_zero.py", line 24, in wrapped_fn
    return fn(*args, **kwargs)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/loggers/logger.py", line 51, in get_experiment
    return fn(self)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/pytorch_lightning/loggers/mlflow.py", line 172, in experiment
    run = self._mlflow_client.get_run(self._run_id)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/mlflow/tracking/client.py", line 150, in get_run
    return self._tracking_client.get_run(run_id)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 72, in get_run
    return self.store.get_run(run_id)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 642, in get_run
    run_info = self._get_run_info(run_id)
  File "/Users/ankitamakker/opt/anaconda3/envs/mlflow_demos/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 666, in _get_run_info
    "Run '%s' not found" % run_uuid, databricks_pb2.RESOURCE_DOES_NOT_EXIST
mlflow.exceptions.MlflowException: Run '9202f6188a43411a9ecd08da0a0bcae7' not found

```
Can you provide your environment details?
I'm using pytorch-lightning (1.8.3), mlflow(1.30.0)

Thanks

**Comment by satyajitghana** [comment]
use this

`logger_` is your `MLFlowLogger` Instance

```
                ckpt = torch.load(ckpt_path)
                model.load_state_dict(ckpt["state_dict"])
                os.environ['MLFLOW_RUN_ID'] = logger_.run_id
                os.environ['MLFLOW_EXPERIMENT_ID'] = logger_.experiment_id
                os.environ['MLFLOW_EXPERIMENT_NAME'] = logger_._experiment_name
                os.environ['MLFLOW_TRACKING_URI'] = logger_._tracking_uri
                mlflow.pytorch.log_model(model, "model")
```
