### ISSUE TITLE
ValueError: unable to save hyperparameters for combining lightning modules

### ISSUE THREAD

**Issue by cxyzen** [PyTorchLightning/pytorch-lightning#7447]
## 🐛 Bug

Passing the entire module as argument will result in this error/bug. How can I save the input modules as hyperparameters?

### To Reproduce

```python
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

import pytorch_lightning as pl

class BaseModule(pl.LightningModule):
    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr = 1e-3)
        return optimizer
    
    def training_step(self, batch, batch_idx):
        x,y = batch
        return F.mse_loss(self.forward(x), y)
    
    def forward(self, x):
        x = self.fc(x)
        return x 

class PretrainModelA(BaseModule):
    def __init__(self, in_dim):
        super(PretrainModelA, self).__init__()
        self.save_hyperparameters()
        self.fc = torch.nn.Linear(in_dim, 1)

class PretrainModelB(BaseModule):
    def __init__(self, in_dim):
        super(PretrainModelB, self).__init__()
        self.save_hyperparameters()
        self.fc = torch.nn.Linear(in_dim, 1)

class CombineModel(BaseModule):
    def __init__(self, pretrainA, pretrainB):
        super(CombineModel, self).__init__()
        self.save_hyperparameters()
        self.pretrainA = pretrainA
        self.pretrainA.freeze()
        self.pretrainB = pretrainB
        self.pretrainB.freeze()     
        self.fc = torch.nn.Linear(2, 1)  

    def forward(self, x):
        x = torch.cat((self.pretrainA(x), self.pretrainB(x)), dim=1)
        return super().forward(x)
   
def run():
    ds = TensorDataset(torch.randn(10, 10), torch.randn(10, 1))
    dl = DataLoader(ds)

    pretrainA = PretrainModelA(10)
    trainerA = pl.Trainer(gpus = 0, max_epochs = 1)
    trainerA.fit(pretrainA, dl)

    pretrainB = PretrainModelA(10)
    trainerB = pl.Trainer(gpus = 0, max_epochs = 1)
    trainerB.fit(pretrainA, dl)

    # Error here
    combine = CombineModel(pretrainA, pretrainB)
    trainerC = pl.Trainer(gpus = 0, max_epochs = 1)
    trainerC.fit(combine, dl)

if __name__ == '__main__':
    run()
```

### Output
```
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  warnings.warn(*args, **kwargs)

  | Name | Type   | Params
--------------------------------
0 | fc   | Linear | 11    
--------------------------------
11        Trainable params
0         Non-trainable params
11        Total params
0.000     Total estimated model params size (MB)
/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 658.14it/s, loss=1.61, v_num=23]
GPU available: True, used: False
TPU available: False, using: 0 TPU cores

  | Name | Type   | Params
--------------------------------
0 | fc   | Linear | 11    
--------------------------------
11        Trainable params
0         Non-trainable params
11        Total params
0.000     Total estimated model params size (MB)
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 739.15it/s, loss=1.55, v_num=24]
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    run()
  File "test.py", line 60, in run
    trainerC.fit(combine, dl)
  File "/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in _run
    self.pre_dispatch()
  File "/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 785, in pre_dispatch
    self.logger.save()
  File "/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py", line 49, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/loggers/tensorboard.py", line 238, in save
    save_hparams_to_yaml(hparams_file, self.hparams)
  File "/home/usr/project/env/lib/python3.6/site-packages/pytorch_lightning/core/saving.py", line 400, in save_hparams_to_yaml
    yaml.dump(v)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/representer.py", line 343, in represent_object
    'tag:yaml.org,2002:python/object:'+function_name, state)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/usr/project/env/lib/python3.6/site-packages/yaml/representer.py", line 330, in represent_object
    dictitems = dict(dictitems)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

### Expected behavior

Able to save hyperparameters for `CombineModel`.

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.13
 - CUDA/cuDNN version: Cuda compilation tools, release 11.3, V11.3.58
 - GPU models and configuration: GTX 1050 Ti

### Additional information
However, this will work if I passed the pretrained models as `torch.nn.Module`. For example:
```python
class PretrainModelA(torch.nn.Module):
    ...

class PretrainModelB(torch.nn.Module):
    ...
```

**Comment by KyleOng** [comment]
Hello my friend, 

I have wrote a discussion about this and listed out several solutions, which you can read [here](https://github.com/PyTorchLightning/pytorch-lightning/discussions/7249#discussioncomment-677516). However, I have now finally know why this is happening, and come out with the final solution.

The reason behind this is that the entire model can't be saved by the logger. What you want is to save the model without the parameters/weights but the hyperparameters only. To do this, you can  write your own `TensorBoardLogger` class and remove the weights from the input models in `hparams` before saving.

Here's my final solution.
```python
import pytorch_lightning as pl
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

class MyModelA(pl.LightningModule):
    def __init__(self, hidden_dim = 10):
        super(MyModelA, self).__init__()
        self.fc1 = torch.nn.Linear(hidden_dim, 2)
        self.save_hyperparameters()

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr = 1e-3)
        return optimizer
        
    def forward(self, x):
        x = self.fc1(x)
        return x

    def training_step(self, batch, batch_idx):
        x,y = batch
        return F.mse_loss(self.forward(x), y)
    
class MyModelB(pl.LightningModule):
    def __init__(self, hidden_dim = 10):
        super(MyModelB, self).__init__()
        self.fc1 = torch.nn.Linear(hidden_dim, 2)
        self.save_hyperparameters()
    
    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr = 1e-3)
        return optimizer
        
    def forward(self, x):
        x = self.fc1(x)
        return x

    def training_step(self, batch, batch_idx):
        x,y = batch
        return F.mse_loss(self.forward(x), y)

class MyEnsemble(pl.LightningModule):
    def __init__(self, modelA, modelB):
        super(MyEnsemble, self).__init__()
        self.modelA = modelA
        self.modelB = modelB
        self.modelA.freeze()
        self.modelB.freeze()
        self.classifier = torch.nn.Linear(4, 2)

        self.save_hyperparameters() # Uncomment to show error

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr = 1e-3)
        return optimizer
        
    def forward(self, x):
        x1 = self.modelA(x)
        x2 = self.modelB(x)
        x = torch.cat((x1, x2), dim=1)
        x = self.classifier(x)
        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        return F.mse_loss(self.forward(x), y)

    def test_step(self, batch, batch_idx):
        x, y = batch
        return F.mse_loss(self.forward(x), y)

# Create your own TensorBoardLogger which save input models' hparams
from pytorch_lightning.loggers import TensorBoardLogger
class MyTensorBoardLogger(TensorBoardLogger):
    def save(self):
        for hparam_key, hparam_value in self.hparams.items():
            # check if hparam is child of pl.LightningModule
            if pl.LightningModule in hparam_value.__class__.__bases__:
                self.hparams[hparam_key] = hparam_value.hparams
        super().save()

dl = DataLoader(TensorDataset(torch.randn(1000, 10), 
                              torch.randn(1000, 2)), 
                batch_size = 10)

modelA = MyModelA()
modelB = MyModelB()

# pretrained modelA and modelB
trainerA = pl.Trainer(gpus = 0, max_epochs = 5, progress_bar_refresh_rate = 50)
trainerA.fit(modelA, dl)
trainerB = pl.Trainer(gpus = 0, max_epochs = 5, progress_bar_refresh_rate = 50)
trainerB.fit(modelB, dl)

# modelA and modelB contains pretrained weights
model = MyEnsemble(modelA, modelB)

logger = MyTensorBoardLogger("logs")
checkpoint_callback = pl.callbacks.ModelCheckpoint()

# Add your custom logger into trainer
trainer = pl.Trainer(gpus = 0, max_epochs = 5, progress_bar_refresh_rate = 50, 
                     logger = logger, callbacks=[checkpoint_callback])
trainer.fit(model, dl)

# Check all model weights are equal after training
model_test = MyEnsemble.load_from_checkpoint(checkpoint_callback.best_model_path)

def compare_models(model_1, model_2):
    models_differ = 0
    for key_item_1, key_item_2 in zip(model_1.state_dict().items(), model_2.state_dict().items()):
        if torch.equal(key_item_1[1], key_item_2[1]):
            pass
        else:
            models_differ += 1
            if (key_item_1[0] == key_item_2[0]):
                print('Mismtach found at', key_item_1[0])
            else:
                raise Exception
    if models_differ == 0:
        print('Models match perfectly!')

compare_models(modelA, model.modelA)
compare_models(model.modelA, model_test.modelA)
compare_models(modelB, model.modelB)
compare_models(model.modelB, model_test.modelB)
```

### Output
```
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
/home/kyleong/projects/env/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  warnings.warn(*args, **kwargs)

  | Name | Type   | Params
--------------------------------
0 | fc1  | Linear | 22    
--------------------------------
22        Trainable params
0         Non-trainable params
22        Total params
0.000     Total estimated model params size (MB)
/home/kyleong/projects/env/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Epoch 4: 100%|███████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1151.01it/s, loss=1.02, v_num=0]
GPU available: True, used: False
TPU available: False, using: 0 TPU cores

  | Name | Type   | Params
--------------------------------
0 | fc1  | Linear | 22    
--------------------------------
22        Trainable params
0         Non-trainable params
22        Total params
0.000     Total estimated model params size (MB)
Epoch 4: 100%|███████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1142.66it/s, loss=1.01, v_num=1]
GPU available: True, used: False
TPU available: False, using: 0 TPU cores

  | Name       | Type     | Params
----------------------------------------
0 | modelA     | MyModelA | 22    
1 | modelB     | MyModelB | 22    
2 | classifier | Linear   | 10    
----------------------------------------
10        Trainable params
44        Non-trainable params
54        Total params
0.000     Total estimated model params size (MB)
Epoch 4: 100%|███████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 946.92it/s, loss=0.974, v_num=0]
Models match perfectly!
Models match perfectly!
Models match perfectly!
Models match perfectly!
```

**Comment by Lucklyric** [comment]
Hello there, @KyleOng. Your solution completely solves the problem of creating a hapams file.  However, saving such parameters in hparams.yaml, on the other hand, will break the logic when init model with `hparams_file` arguments in `load_from_checkpoint()`. I think a best practice might be not initializing a model with non-basic type elements. Initializing sub-models within the Ensemble model and passing their configurations as args could be a safer choice.

**Comment by KyleOng** [comment]
Hi @Lucklyric 

I see. Then I think something like this will be better. 

Here, I passed the configuration of the submodels, which are the hyperparameters (`hparams`) and parameters/weights (`state_dict`),  to the `Ensemble` model. But the weights of the submodels are ignored and not saved to the `yaml file`. as all the weights including the pretrained weights of the submodels will be saved in `checkpoints`,

Am I right? @Lucklyric 

```python
import pytorch_lightning as pl
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

class MyModelA(pl.LightningModule):
    def __init__(self, hidden_dim = 10):
        super(MyModelA, self).__init__()
        self.fc1 = torch.nn.Linear(hidden_dim, 2)
        self.save_hyperparameters()

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr = 1e-3)
        return optimizer
        
    def forward(self, x):
        x = self.fc1(x)
        return x

    def training_step(self, batch, batch_idx):
        x,y = batch
        return F.mse_loss(self.forward(x), y)
    
class MyModelB(pl.LightningModule):
    def __init__(self, hidden_dim = 10):
        super(MyModelB, self).__init__()
        self.fc1 = torch.nn.Linear(hidden_dim, 2)
        self.save_hyperparameters()
    
    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr = 1e-3)
        return optimizer
        
    def forward(self, x):
        x = self.fc1(x)
        return x

    def training_step(self, batch, batch_idx):
        x,y = batch
        return F.mse_loss(self.forward(x), y)

class MyEnsemble(pl.LightningModule):
    def __init__(self, 
                 modelA_hparams, modelB_hparams,
                 modelA_params = None, modelB_params = None):
        super(MyEnsemble, self).__init__()
        self.modelA = MyModelA(**modelA_hparams)
        self.modelB = MyModelB(**modelB_hparams)

        if modelA_params:
            self.modelA.load_state_dict(modelA_params)
        if modelB_params:
            self.modelB.load_state_dict(modelB_params)

        self.modelA.freeze()
        self.modelB.freeze()
        self.classifier = torch.nn.Linear(4, 2)

        self.save_hyperparameters(ignore = ["modelA_params", "modelB_params"])

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr = 1e-3)
        return optimizer
        
    def forward(self, x):
        x1 = self.modelA(x)
        x2 = self.modelB(x)
        x = torch.cat((x1, x2), dim=1)
        x = self.classifier(x)
        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        return F.mse_loss(self.forward(x), y)

    def test_step(self, batch, batch_idx):
        x, y = batch
        return F.mse_loss(self.forward(x), y)


dl = DataLoader(TensorDataset(torch.randn(1000, 10), 
                              torch.randn(1000, 2)), 
                batch_size = 10)

modelA = MyModelA()
modelB = MyModelB()

# pretrained modelA and modelB
trainerA = pl.Trainer(gpus = 0, max_epochs = 5, progress_bar_refresh_rate = 50)
trainerA.fit(modelA, dl)
trainerB = pl.Trainer(gpus = 0, max_epochs = 5, progress_bar_refresh_rate = 50)
trainerB.fit(modelB, dl)

checkpoint_callback = pl.callbacks.ModelCheckpoint()

# modelA and modelB contains pretrained weights
model = MyEnsemble(modelA.hparams, modelB.hparams, modelA.state_dict(), modelB.state_dict())
trainer = pl.Trainer(gpus = 0, max_epochs = 5, progress_bar_refresh_rate = 50, callbacks=[checkpoint_callback])
trainer.fit(model, dl)

# Check all model weights are equal after training
model_test = MyEnsemble.load_from_checkpoint(checkpoint_callback.best_model_path,
                                             hparams_file = checkpoint_callback.best_model_path.split("checkpoints")[0]+"hparams.yaml")

def compare_models(model_1, model_2):
    models_differ = 0
    for key_item_1, key_item_2 in zip(model_1.state_dict().items(), model_2.state_dict().items()):
        if torch.equal(key_item_1[1], key_item_2[1]):
            pass
        else:
            models_differ += 1
            if (key_item_1[0] == key_item_2[0]):
                print('Mismtach found at', key_item_1[0])
            else:
                raise Exception
    if models_differ == 0:
        print('Models match perfectly!')

compare_models(modelA, model.modelA)
compare_models(model.modelA, model_test.modelA)
compare_models(modelB, model.modelB)
compare_models(model.modelB, model_test.modelB)


```
The output is the same as my previous reply.

**Comment by cxyzen** [comment]
Hi @KyleOng, thanks for the reply. 

The code works wonderfully, and I think it works just like what @Lucklyric said. Just hope that someone can verify.

Again, thank you very much!

**Comment by Lucklyric** [comment]
Hi, @KyleOng. Thank you for the updates; it's a neat solution.  @cxyzen In fact, I believe it is possible to include high-level objects in the hparams along with their module paths. Then more efforts on saving and parsing both sides are needed, so we'll see what the maintainers think of it.
