### ISSUE TITLE
Impossible to call trainer.test when using stochastic_weight_avg=True + ddp

### ISSUE THREAD

**Issue by dfioravanti** [PyTorchLightning/pytorch-lightning#7505]
## 🐛 Bug

I am using `ddp` as a backend. Follwing the "training tricks" page I used `stochastic_weight_avg=true` in the Trainer. Doing so makes training works like a charm but when I try to use `trainer.test` the program crashes when it tries to reload the best model with a 
```
AttributeError: 'Net' object has no attribute '_parameters'
```
if I patch the network to have `_parameters` it crashes on `_modules`. If patch `_modules` it crashes on `_buffers`. If I patch that it crashes with an assertion error from pytorch. 

If I remove the `stochastic_weight_avg=true` everything works as expected.

### Expected behavior

It should not crash

### Enviroment

* CUDA:
	- GPU:
		- RTX A6000
		- RTX A6000
	- available:         True
	- version:           11.0
* Packages:
	- numpy:             1.19.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu110
	- pytorch-lightning: 1.3.1
	- tqdm:              4.60.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Thu Nov 19 17:20:08 UTC 2020

**Comment by addisonklinke** [comment]
Noting what appears to be related behavior in Lightning v1.3.0
```
trainer = pl.Trainer(accelerator='ddp', callbacks=[ModelPruning('l1_unstructured', amount=0.5)])
trainer.fit(net, datamodule)
AttributeError: 'Net' object has no attribute '_parameters'  # Occurs during the `on_validation_end` hook
```

**Comment by rahumble** [comment]
I have the same issue as @addisonklinke. When combining ModelPruning + DDP, I get a `deepcopy` failure during checkpointing. This issue seems to have existed from at least 1.3.0 and still exists in master (as of today 7/11).

Repro steps:
1. Copy the boring model colab [code](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) to somewhere you can run DDP
2. Change the trainer setup to
```
trainer = pl.Trainer(
        max_epochs=1, gpus=1, accelerator="ddp",
        progress_bar_refresh_rate=20,
        callbacks=[pl.callbacks.ModelPruning("l1_unstructured", amount=0.5)]
    )
```
3. Get a failure on checkpointing
```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                      
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/code/combinedpruning/bug.py", line 102, in <module>
    test_x(tmpdir)
  File "/workspace/code/combinedpruning/bug.py", line 98, in test_x
    trainer.fit(model, train, val)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 871, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 915, in _dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 97, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 925, in run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 974, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 102, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 217, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 103, in run
    self.on_advance_end()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 164, in on_advance_end
    self._run_validation()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 240, in _run_validation
    self.val_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 108, in run
    output = self.on_run_end()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 154, in on_run_end
    self.on_evaluation_end()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 219, in on_evaluation_end
    self.trainer.call_hook("on_validation_end", *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in call_hook
    trainer_hook(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 227, in on_validation_end
    callback.on_validation_end(self, self.lightning_module)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 279, in on_validation_end
    self.save_checkpoint(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 330, in save_checkpoint
    self._save_none_monitor_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 717, in _save_none_monitor_checkpoint
    self._save_model(trainer, filepath)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 494, in _save_model
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/properties.py", line 379, in save_checkpoint
    self.checkpoint_connector.save_checkpoint(filepath, weights_only)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 431, in save_checkpoint
    _checkpoint = self.dump_checkpoint(weights_only)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 339, in dump_checkpoint
    checkpoint['callbacks'] = self.trainer.on_save_checkpoint(checkpoint)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 276, in on_save_checkpoint
    state = callback.on_save_checkpoint(self, self.lightning_module, checkpoint)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py", line 420, in on_save_checkpoint
    copy = deepcopy(pl_module.to("cpu"))
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 272, in _reconstruct
    y.__setstate__(state)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 542, in __setstate__
    parameters, expect_sparse_gradient = self._build_params_for_reducer()
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 602, in _build_params_for_reducer
    modules_and_parameters = [
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 603, in <listcomp>
    [
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 606, in <listcomp>
    for parameter in [
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 606, in <listcomp>
    for parameter in [
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1434, in named_parameters
    for elem in gen:
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1379, in _named_members
    members = get_members_fn(module)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1432, in <lambda>
    lambda module: module._parameters.items(),
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1094, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BoringModel' object has no attribute '_parameters'
```

Environment (using latest pytorch_lightning):
```
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3080
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.21.0
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0a0+2ecb2c7
        - pytorch-lightning: 1.4.0dev
        - tqdm:              4.53.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.8
        - version:           #86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021
```

**Comment by rahumble** [comment]
I dug into this a bit more, and I think it's because the deepcopy involves a circular reference:
```model.trainer.accelerator_connector.training_type_plugin._model.module.module == model```

The error arises when trying to deepcopy the model's `.trainer` (Trainer)
  --> which involves deepcopying the trainer's `.accelerator_connector` (AcceleratorConnector)
  --> which involves deepcopying the connector's `.training_type_plugin` (DDPPlugin)
  --> which involves deepcopying the plugin's `._model` (DistributedDataParallel)
  --> which involves deepcopying the DDP's `.module` (LightingDistributedModule)
  --> which involves deepcopying the LightningDistributedModule's `.module` (BoringModel here)

But in order to deepcopy that we need the deepcopy of the original model, which we don't yet have, so the deepcopy mechanism simply returns an empty `BoringModel` (with no attributes).

**Comment by rahumble** [comment]
@Borda @ananthsub @tchaton @edenlightning, just bumping this.

Willing to help work on a fix/PR if I can get some guidance on how this should be addressed.

**Comment by rahumble** [comment]
Still blocked by this issue and don't want this issue to be closed. Is there anyone who can comment on how this should get fixed?

**Comment by rahumble** [comment]
Bumping again. Bad bot

**Comment by amorehead** [comment]
Hey, there. Has anyone here found a way to call `copy.deepcopy()` on a LightningModule? I am trying to implement a custom EMA callback for model weight averaging, however, my implementation relies on calling deepcopy().

**Comment by johnathanchiu** [comment]
Hey @amorehead, I had trouble doing this as well. The issue I was running into when calling `copy.deepcopy()` was along the lines of:
`AttributeError: 'MyModel' object has no attribute '_parameters'`

I was able to get something to work similarly by removing the `"_trainer"` attribute. As an example:
```
ref_trainer_attr = model.__dict__["_trainer"]
model.__dict__["_trainer"] = None
model_copied = copy.deepcopy(model)
model_copied.__dict__["_trainer"] = ref_trainer_attr
```
