### ISSUE TITLE
Lightning fails when LARS wrapper is used for optimizer

### ISSUE THREAD

**Issue by MkuuWaUjinga** [PyTorchLightning/pytorch-lightning#7527]
## 🐛 Bug

When optimizer is wrapped by LARS wrapper from `from pl_bolts.optimizers.lars_scheduling import LARSWrapper` PL fails with
```
Traceback (most recent call last):
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/site-packages/pl_bolts/models/self_supervised/swav/swav_module.py", line 608, in <module>
    cli_main()
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/site-packages/pl_bolts/models/self_supervised/swav/swav_module.py", line 604, in cli_main
    trainer.fit(model, datamodule=dm)
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in _run
    self.pre_dispatch()
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 778, in pre_dispatch
    self.accelerator.pre_dispatch(self)
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 106, in pre_dispatch
    self._move_optimizer_state()
  File "/anaconda/envs/unsup-obj-det/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 120, in _move_optimizer_state
    opt.state = state
AttributeError: can't set attribute
```

### To Reproduce
Just use any pl module using a lars wrapper e.g.
`python -m pl_bolts.models.self_supervised.swav.swav_module --gpus 1 --lars_wrapper`

### Environment
pytorch-lightning == 1.3.1

This is likely due to #7277. Earlier versions seem work well.

**Comment by MkuuWaUjinga** [comment]
Hi,
any update on this? Would like to use pl_bolts with the newest pl version...
