### ISSUE TITLE
NLP-BERT example: Scheduler Not Pickleable

### ISSUE THREAD

**Issue by shaomai00** [PyTorchLightning/pytorch-lightning#7618]
## 🐛 Bug
When I run script -NLP -BERT (using transformers) [https://colab.research.google.com/github/PytorchLightning/pytorch-lightning/blob/master/notebooks/04-transformers-text-classification.ipynb](url) with multi gpus, an error appeared :  
`LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    trainer.fit(model, dm)
  File "/home/admin/workspace/project/double_tower_keywords_venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/admin/workspace/project/double_tower_keywords_venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/home/admin/workspace/project/double_tower_keywords_venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/home/admin/workspace/project/double_tower_keywords_venv/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/admin/workspace/project/double_tower_keywords_venv/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 122, in start_training
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)
  File "/home/admin/workspace/project/double_tower_keywords_venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/admin/workspace/project/double_tower_keywords_venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_linear_schedule_with_warmup.<locals>.lr_lambda'`

It seems DDP Spawn forces the model to be pickleable.

**Comment by shaomai00** [comment]
I fixed by adding 
`--accelerator ddp `
instead
