### ISSUE TITLE
`stochastic_weight_avg=True` incompatible with `max_steps`

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#7710]
## 🐛 Bug

If I try to use a Trainer with `stochastic_weight_avg=True` along with `max_steps` like in:

```python
import pytorch_lightning as pl
import torch
from torch import nn

class BoringModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        self.loss = nn.MSELoss()
    def configure_optimizers(self):
        return torch.optim.Adam(self.linear.parameters())
    def training_step(self, batch, batch_idx):
        X, y = batch
        return self.loss(self.linear.forward(X), y)
    def validation_step(self, batch, batch_idx):
        X, y = batch
        loss = self.loss(self.linear.forward(X), y)
        self.log("val_loss", loss)

data = [
    (torch.tensor([X]), 5 * torch.tensor([X]) + 1)
    for X in torch.linspace(0, 100, 24)
]
dataloader = torch.utils.data.DataLoader(dataset=data, batch_size=4)

trainer = pl.Trainer(max_steps=10000, stochastic_weight_avg=True)
trainer.fit(BoringModel(), dataloader)
```

I get a failure:
```python
Traceback (most recent call last):
  File "lightning.py", line 27, in <module>
    trainer.fit(BoringModel(), dataloader)
  File "/home/alandu/miniconda3/envs/ctrldev/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/alandu/miniconda3/envs/ctrldev/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 750, in _run
    self.call_hook("on_fit_start")
  File "/home/alandu/miniconda3/envs/ctrldev/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1223, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/alandu/miniconda3/envs/ctrldev/lib/python3.6/site-packages/pytorch_lightning/trainer/callback_hook.py", line 70, in on_fit_start
    callback.on_fit_start(self, self.lightning_module)
  File "/home/alandu/miniconda3/envs/ctrldev/lib/python3.6/site-packages/pytorch_lightning/callbacks/stochastic_weight_avg.py", line 155, in on_fit_start
    self._swa_epoch_start = int(trainer.max_epochs * self._swa_epoch_start)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```
### Environment
```
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1
	- pytorch-lightning: 1.3.2
	- tqdm:              4.60.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.6.10
	- version:           #1 SMP Sat May 15 20:31:00 UTC 2021
```

**Comment by edgarriba** [comment]
@alanhdu thanks for raising this issue. The [StochasticWeightAveraging](https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.callbacks.StochasticWeightAveraging.html#pytorch_lightning.callbacks.StochasticWeightAveraging) callback internally instantiates the PyTorch Stochastic Weight Averaging (SWALR) learning rate scheduler which is based on the number of epochs in your training loop.

For now I'd suggest to setup your trainer defining the `max_epochs`. In the meantime, I opened a quick PR #8015 to raise a misconfiguration exception message when using the SWALR and no `max_epochs` specified.

**Comment by alanhdu** [comment]
@edgarriba -- sorry for the confusion, but was your fix merged or is this issue still open?
