### ISSUE TITLE
TypeError: validation_step() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Ycblue** [PyTorchLightning/pytorch-lightning#781]
Hi, I just started using lightning and I've been running into this bug lately. 

Here's my code for the validation_step and validation_end:
```
def validation_step(self, batch, batch_idx):  
        imgs = batch
        (z1, z2) = torch.split(imgs['X'], 1, 1)
        ct = imgs['CT']
        y_hat = self.discriminator(self(z1, z2).detach())
        y = self.discriminator(ct.detach())
        print('Validation Step: \n')
        print('y_hat = ', y_hat)
        print('y_hat.shape = ', y_hat.shape)
        print('y = ', y)
        print('y.shape = ', y.shape)
        return {'val_loss': F.cross_entropy(y_hat, y)}

def validation_end(self, outputs):
       avg_loss = torch.stack([x['val_loss'] for x in outputs]).mean()
       return {'val_loss': avg_loss, 
                  'progress_bar': {avg_loss}}
```
Stacktrace: 

```
Traceback (most recent call last):
  File "/home/students/lan/Schreibtisch/Code/x2ct_architecture_ff/gan.py", line 333, in <module>
    main(hparams)
  File "/home/students/lan/Schreibtisch/Code/x2ct_architecture_ff/gan.py", line 308, in main
    trainer.fit(model)
  File "/work/scratch/lan/conda/envs/pytorch_thesis/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 692, in fit
    self.dp_train(model)
  File "/work/scratch/lan/conda/envs/pytorch_thesis/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 471, in dp_train
    self.run_pretrain_routine(model)
  File "/work/scratch/lan/conda/envs/pytorch_thesis/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 812, in run_pretrain_routine
    self.evaluate(model, self.get_val_dataloaders(), self.num_sanity_val_steps, self.testing)
  File "/work/scratch/lan/conda/envs/pytorch_thesis/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 234, in evaluate
    test)
  File "/work/scratch/lan/conda/envs/pytorch_thesis/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 349, in evaluation_forward
    output = model(*args)
  File "/work/scratch/lan/conda/envs/pytorch_thesis/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/scratch/lan/conda/envs/pytorch_thesis/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 62, in forward
    return self.module.validation_step(*inputs[0], **kwargs[0])
TypeError: validation_step() takes 3 positional arguments but 4 were given
```

There has been a similar issue in the past, namely #105, but the bug was resolved in an earlier version and couldn't help me much. 

Environment: 
* Ubuntu: 18.04.3 LTS
* Python: 3.7.5
* Pytorch: 1.3.1
* Pytorch-Lightning: 0.6.0
* Anaconda: 4.7.12

Thanks for the help!

**Comment by williamFalcon** [comment]
when using two optimizers training_step gets a 4th argument: optimizer_idx

**Comment by Ycblue** [comment]
> 
> 
> when using two optimizers training_step gets a 4th argument: optimizer_idx

Thanks for the fast response! 
However, the issue is with the validation_step and not with the training_step, where I did include optimizer_idx as the 4th argument! 

Does this mean that I have to include optimizer_idx as an argument in the validation_step as well?

**Comment by williamFalcon** [comment]
yup. the trace hints at that

**Comment by sonam-saarthi** [comment]
val_loop.run()
  File "/root/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/root/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 376, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 393, in validation_step  
    return self.model.validation_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/***/project/models/text_classifiers.py", line 101, in validation_step
    loss_dict = {
                ^
  File "/root/saarthi-workspace/Sales-And-onboarding-NLU/saarthi_train/models/text_classifiers.py", line 102, in <dictcomp>
    classname: self.loss[classname](out[classname], batch[classname])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/pytorch_env/lib/python3.11/site-packages/balanced_loss/losses.py", line 106, in forward
    weights = weights.repeat(batch_size, 1) * labels_one_hot
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (78) must match the size of tensor b (80) at non-singleton dimension 1


What could be the possibility of this error? I am using 'xlm-roberta' for transfer learning for text classification.
