### ISSUE TITLE
horovod bug: TypeError: __init__() missing 2 required positional arguments: 'named_parameters' and 'compression'

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#7839]
### To Reproduce

```python
import os

import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, random_split
from torchvision.datasets import MNIST
from torchvision import transforms
import pytorch_lightning as pl
from pytorch_lightning.metrics.functional import accuracy
from pl_bolts.datasets import DummyDataset

train = DummyDataset((1, 28, 28), (1,))
train = DataLoader(train, batch_size=32)

val = DummyDataset((1, 28, 28), (1,))
val = DataLoader(val, batch_size=32)

test = DummyDataset((1, 28, 28), (1,))
test = DataLoader(test, batch_size=32)

class LitAutoEncoder(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(28 * 28, 128), nn.ReLU(), nn.Linear(128, 3))
        self.decoder = nn.Sequential(nn.Linear(3, 128), nn.ReLU(), nn.Linear(128, 28 * 28))

    def training_step(self, batch, batch_idx):
        # --------------------------
        # REPLACE WITH YOUR OWN
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log('train_loss', loss)
        return loss
        # --------------------------

    def validation_step(self, batch, batch_idx):
        # --------------------------
        # REPLACE WITH YOUR OWN
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log('val_loss', loss)
        # --------------------------

    def test_step(self, batch, batch_idx):
        # --------------------------
        # REPLACE WITH YOUR OWN
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log('test_loss', loss)
        # --------------------------

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

# init model
ae = LitAutoEncoder()

# Initialize a trainer
trainer = pl.Trainer(gpus=1, max_epochs=2, progress_bar_refresh_rate=20, accelerator='horovod')

# Train the model ⚡
trainer.fit(ae, train, val)
trainer.test(test_dataloaders=test)
```

### Error information

```bash
Traceback (most recent call last):
  File "run.py", line 36, in main
    return train(config)
  File "/home/marsggbo/code/hyperbox/src/train.py", line 82, in train
    trainer.test()
  File "/home/marsggbo/.conda/envs/torch18/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in test
    results = self._run(model)
  File "/home/marsggbo/.conda/envs/torch18/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in _run
    self.pre_dispatch()
  File "/home/marsggbo/.conda/envs/torch18/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 778, in pre_dispatch
    self.accelerator.pre_dispatch(self)
  File "/home/marsggbo/.conda/envs/torch18/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 108, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/home/marsggbo/.conda/envs/torch18/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/horovod.py", line 98, in pre_dispatch
    h_opt = hvd.DistributedOptimizer(
  File "/home/marsggbo/.conda/envs/torch18/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 590, in DistributedOptimizer
    return cls(optimizer.param_groups, named_parameters, compression, backward_passes_per_step, op,
  File "/home/marsggbo/.conda/envs/torch18/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 41, in __init__
    super(self.__class__, self).__init__(params)
TypeError: __init__() missing 2 required positional arguments: 'named_parameters' and 'compression'
```

### Environment

* CUDA:
        - GPU:
                - Tesla V100-PCIE-32GB
                - Tesla V100-PCIE-32GB
                - Tesla V100-PCIE-32GB
                - Tesla V100-PCIE-32GB
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.20.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.7.1+cu101
        - pytorch-lightning: 1.3.4
        - tqdm:              4.61.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #1 SMP Fri Oct 18 17:15:30 UTC 2019
* horovod: 0.22.0

**Comment by marsggbo** [comment]
I found the cause. After finishing `trainer.fit(...)`, the optimizers have already wrapped as `hvd.DistributedOptimizer`. When we start running `trainer.test()`, the framework will wrap the optimizers again, which is why the error is thrown. I've send PR #7840 to solve this problem.

**Comment by awaelchli** [comment]
Great job! Are you able to finish the PR? 
I suggest to simply add a trainer.test() call to one of the existing horovod test cases (look for them in tests/models/test_horovod.py) to cover this problem.
