### ISSUE TITLE
Memory explodes when limit_train_batches argument used

### ISSUE THREAD

**Issue by EdwardJB** [PyTorchLightning/pytorch-lightning#8040]
## 🐛 Bug

My training uses an iterable dataset with 60 workers and memory consumption sits around 150GB. This is all expected and fine.

However, if I set the `limit_train_batches` arguments (e.g. to `500`), memory rises (more or less) constantly until training crashes with OOM errors.

### To Reproduce

I want to know if this behaviour is expected or does it sound like a bug? If the latter, I'll happily provide further details if needed.

### Expected behavior

Limiting batches per epoch should use the same (or less) memory than not.

### Environment

```
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
                - NVIDIA GeForce RTX 2060 SUPER
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.20.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1+cu111
        - pytorch-lightning: 1.3.1
        - tqdm:              4.60.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:
        - python:            3.9.4
        - version:           #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

**Comment by ethanwharris** [comment]
Hi @EdwardJB thanks for the issue! This does sound like unexpected behaviour. Could you try installing from master with `pip install https://github.com/PyTorchLightning/pytorch-lightning/archive/master.zip` and see if it persists? If so, then a notebook which reproduces the issue would be much appreciated.

Thanks :smiley:

**Comment by EdwardJB** [comment]
Hi @ethanwharris 

I tried using master and the problem persists. I've been trying to replicate also from the master branch today. This is the best I can do:

```python
import os
import pytorch_lightning as pl
from torch.utils.data import DataLoader, IterableDataset

tmpdir = os.getcwd()


class RandomDataset(IterableDataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __iter__(self):
        for i in range(self.num_samples):
            yield {'a': torch.rand((1000, 1000, 100)), }


num_samples = 10000
num_workers = 20

train = RandomDataset(num_samples)
train = DataLoader(train, batch_size=2, num_workers=num_workers)

val = RandomDataset(num_samples)
val = DataLoader(val, batch_size=2, num_workers=num_workers)

test = RandomDataset(num_samples)
test = DataLoader(test, batch_size=2, num_workers=num_workers)

import torch
from pytorch_lightning import LightningModule


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(2, 2)

    def forward(self, x):
        output = torch.tensor([0., 0.])
        output.requires_grad = True
        return output

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = torch.tensor(0.)
        output.requires_grad = True
        return output

    def training_epoch_end(self, outputs) -> None:
        return None
        # torch.stack([x["loss"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def tst_x(tmpdir):
    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = pl.Trainer(
        # max_epochs=1,
        # progress_bar_refresh_rate=20,

        limit_train_batches=10,
        limit_val_batches=10,
        limit_test_batches=10
    )

    trainer.fit(model, train, val)

    trainer.test(test_dataloaders=test)


tst_x(tmpdir)
```

This _looks_ to start consuming more and more memory, but I cannot confirm because training eventually hangs with a seemingly unrelated bug:


```
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/usr/local/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
  warnings.warn(*args, **kwargs)
  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 6     
---------------------------------
6         Trainable params
0         Non-trainable params
6         Total params
0.000     Total estimated model params size (MB)
/usr/local/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: The number of training samples (10) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  warnings.warn(*args, **kwargs)
Epoch 1:   0%|          | 0/10.0 [00:00<?, ?it/s, loss=0, v_num=10]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Epoch 2:   0%|          | 0/10.0 [00:00<?, ?it/s, loss=0, v_num=10]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Epoch 4:   0%|          | 0/10.0 [00:00<?, ?it/s, loss=0, v_num=10]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f722f0f35e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Epoch 4:   0%|          | 0/10.0 [00:14<?, ?it/s, loss=0, v_num=10]
```

**Comment by tchaton** [comment]
Dear @EdwardJB,

Thanks for sharing this script. We will look into it promptly.

Best,
T.C

**Comment by tchaton** [comment]
Dear @EdwardJB,

Small correction to the above script.
```python
class RandomDataset(IterableDataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples
        self.counter = 0

    def __iter__(self):
        self.counter = 0
        return self
    
    def __next__(self):
        if self.counter > self.num_samples:
            raise StopIteration
        self.counter += 1
        return {'a': torch.rand((1000, 1000, 100)), }
```

I tried to debug this behaviour but couldn't reproduce it. 

Do you use any additional callbacks ? 

I will keep investigating.

Best,
T.C

**Comment by EdwardJB** [comment]
> Dear @EdwardJB,
> Do you use any additional callbacks ?
> 
> I will keep investigating.
> 
> Best,
> T.C

Hi! Thanks for coming back to me. Yes my real-world model uses the following: 

```
    # Configure callbacks
    early_stopper = EarlyStopping(
        monitor='F1',
        patience=config.EARLY_STOPPING_PATIENCE,
        verbose=True,
        mode=config.MODE_MAX,
        min_delta=config.EARLY_STOPPING_MIN_DELTA
    )
    checkpointer = ModelCheckpoint(
        dirpath=run.path_run,
        filename='best-{epoch}-F1-{:.2f}',
        monitor=config.MONITOR_METRIC,
        mode=config.MODE_MAX,
        save_last=True,
    )
    validate_on_start = ValidateOnStart(
        is_resume=run.is_resume
    )
    lr_monitor = LearningRateMonitor(
        logging_interval='epoch'
    )
    callbacks = [validate_on_start, lr_monitor, checkpointer, early_stopper]
```

Let me know if you need anything else.

**Comment by Joaquin-Gajardo** [comment]
I've found a very similar issue, but with an exploding /dev/shm shared memory after a few epochs. The issue only appears when workers>0 in the train dataloader and with any limit_train_batches<1.0.
Here are the error [logs](https://github.com/Lightning-AI/pytorch-lightning/files/14336546/logs_shared_memory_error_20240216_132019_mix_wgangp_tf_0_dim_512_pe_add_img_256_z_16.txt) if I let it run until it crashes. I'm using lightning version 1.6.5.
Since this issue is quite old I don't know if it has been reported and/or solved in the meantime.

**Comment by konmue** [comment]
Any update on this? I ran into the same issue. Without setting limit_train_batches, training works; but when setting limit_train_batches < 1, I quickly run out of memory.
