### ISSUE TITLE
SWA error with Iterable Dataset and DDP after the last epoch

### ISSUE THREAD

**Issue by thecooltechguy** [PyTorchLightning/pytorch-lightning#8150]
## 🐛 Bug

I’m encountering the following error only once training finishes the last epoch successfully, (I’m using Trainer’s stochastic_weight_avg=True in a multi-GPU fp16 training setup with DDP,  my dataloaders are all for IterableDatasets without a length, and my limit_train_batches=2, limit_val_batches=0, limit_test_batches=0):

```
Traceback (most recent call last):
  File "/home/abc/environment/abc/src/train.py", line 75, in <module>
    cli = CustomCLI(
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 173, in __init__
    self.fit()
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 256, in fit
    self.trainer.fit(**self.fit_kwargs)
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in run_train
    self.train_loop.on_train_epoch_start(epoch)
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 169, in on_train_epoch_start
    self.trainer.call_hook("on_train_epoch_start")
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1223, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/trainer/callback_hook.py", line 90, in on_train_epoch_start
    callback.on_train_epoch_start(self, self.lightning_module)
  File "/home/abc/anaconda3/envs/abc/lib/python3.9/site-packages/pytorch_lightning/callbacks/stochastic_weight_avg.py", line 225, in on_train_epoch_start
    trainer.accumulate_grad_batches = len(trainer.train_dataloader)
TypeError: 'float' object cannot be interpreted as an integer
```

### To Reproduce

For some reason, I couldn't repro with the Boring model using a dummy Iterable dataset and `stochastic_weight_average=True`.

However, to reproduce this issue, I used multi-gpu DDP (8 gpus on the same instance), an iterable dataset (with **no** `_len` function defined), and provided `limit_train/val/test_batches=<some number>` to fix the epoch length. Then, after the last epoch, the error will be raised.

I think its due a Type mismatch here: https://github.com/PyTorchLightning/pytorch-lightning/blob/59d0c65613d7543edee51cd05f45e21b507ed9c1/pytorch_lightning/trainer/supporters.py#L405

Basically the `CombinedLoader` class’s `_len_` function is typed with a return type of `int`, but it returns `self._calc_num_batches(self.loaders)` and `_calc_num_batches` is typed with a return type of `Union[int, float]`.
So I think whenever `_calc_num_batches`  returns a `float` and this value is returned from `CombinedLoader` class’s `_len_` function, a `TypeError` is raised. 

In my case, `_calc_num_batches` returns `float("inf")`, and I think this is because my `IterableDataset` has no length, and it seems like this error only occurs at the end of training, since the swa callback only computes the length of the train dataloader (of type `CombinedLoader` ) after the last epoch.

### Expected behavior

No error, and a successful completion of the training job.

### Environment

 - PyTorch Version (e.g., 1.0): 1.3.7.post0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by justusschock** [comment]
hi @thecooltechguy ,

i think you may be right although i still wonder why this cannot be reproduced with a basic boringmodel. Anyways, Im going to have a look.

**Comment by justusschock** [comment]
Hi @thecooltechguy , for me this is fixed by https://github.com/PyTorchLightning/pytorch-lightning/pull/8172

**Comment by thecooltechguy** [comment]
Hi @justusschock , got it, thanks a lot for the fix! Looking forward to trying it out in a lightning release soon! :)
