### ISSUE TITLE
Quantization doc doesn't have working code

### ISSUE THREAD

**Issue by msaroufim** [PyTorchLightning/pytorch-lightning#8570]
## 📚 Documentation

This page https://pytorch-lightning.readthedocs.io/en/stable/advanced/pruning_quantization.html

Doesn't contain working code - I'm currently working through how to make this work with an example from the HuggingFace repo with a BERT model but a toy data loader or something from IMDB could work well

```
trainer = Trainer(callbacks=[QuantizationAwareTraining()])
qmodel = RegressionModel()
trainer.fit(qmodel, ...) ##THIS LINE

batch = iter(my_dataloader()).next()
qmodel(qmodel.quant(batch[0]))

tsmodel = qmodel.to_torchscript()
tsmodel(tsmodel.quant(batch[0]))
```

**Comment by kaushikb11** [comment]
@Borda Mind looking into it?

**Comment by Borda** [comment]
@msaroufim what kind of error are you getting or the problem is with missing data module from example?
mind also share your sample code with BERT?

**Comment by msaroufim** [comment]
Hi @Borda yes it's the latter, the code doesn't compile just throws a syntax error because there's three dots instead of a dataa module.

 I'm still working on an example that would compile with a HF model, it's my first time using Lighting so still working through it https://gist.github.com/msaroufim/55afeefe613e6ad08dbb42839ba5decd

**Comment by msaroufim** [comment]
Ok here are some instructions that work better to repro what a fully working example could look like https://gist.github.com/msaroufim/7b0e8e6ab60fb13c2ec899288f249006

If you just change 

`callbacks=[]`

to 

``
  callbacks=[QuantizationAwareTraining()],

```

It fails with

```
Traceback (most recent call last):
  File "/home/ubuntu/serve/examples/Huggingface_Transformers/11_multi_label_text_classification_with_bert.py", line 572, in <module>
    trainer.fit(model, data_module)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 967, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/ubuntu/serve/examples/Huggingface_Transformers/11_multi_label_text_classification_with_bert.py", line 366, in validation_step
    loss, outputs = self(input_ids, attention_mask, labels)
  File "/home/ubuntu/anaconda3/envs/opt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: wrapper() takes 1 positional argument but 3 were given
```

**Comment by msaroufim** [comment]
Ok so as a workaround I'm going to stack all the tensors on top of each other and then split them so `forward` takes a single argument, would be nice to handle this by default otherwise anyone needs to change their `forward` function anytime they want to support quantization - Let me know if there's any way I can help, I'm new to the codebase

But now the weird part, I'm getting unsupported data type errors for all the possible data types so would appreciate some pointers

``input_ids = batch["input_ids"].to(dtype=torch.float32)`

 
![Screen Shot 2021-07-28 at 3 04 10 PM](https://user-images.githubusercontent.com/3282513/127402661-ae54631d-1526-4047-a400-49ce6ab54552.png)

Ok so lemme try long and int


`input_ids = batch["input_ids"].to(dtype=torch.long)`

![Screen Shot 2021-07-28 at 3 06 43 PM](https://user-images.githubusercontent.com/3282513/127402691-f8ae8178-489c-4103-8589-dd349c8daec5.png)

Ok maybe int?

`input_ids = batch["input_ids"].to(dtype=torch.int)`

![Screen Shot 2021-07-28 at 3 05 32 PM](https://user-images.githubusercontent.com/3282513/127402742-51f3ee4c-1bf3-4fa7-b01a-22d1b10fdce4.png)

XD
