### ISSUE TITLE
(ckpt_path="b' pytorch_lightning.utilities.exceptions.MisconfigurationException: `.test(ckpt_path="best")` is set but `ModelCheckpoint` is not configured to save the best model.

### ISSUE THREAD

**Issue by etetteh** [PyTorchLightning/pytorch-lightning#8605]
I have been trying to debug this for over a day, now. 
This is a snapshot of my code:
```
classifier = Classifier(model.moco)
class_trainer = pl.Trainer(max_epochs=args.epochs//2, 
                     gpus=gpus, gradient_clip_val=1.0, 
                     auto_lr_find=True,
                     progress_bar_refresh_rate=2,
                     )
print(f'\n Training {model_name} Classifier')                            
class_trainer.fit(
        model=classifier,
        train_dataloader=classifier_train_dataloader,
        val_dataloaders=valid_dataloader,
        )

results = class_trainer.test(dataloaders=test_dataloader) 
```

Error:
```
Traceback (most recent call last):
  File "train_moco_.py", line 380, in <module>
    results = class_trainer.test(test_dataloaders=test_dataloader)
  File "/home/jupyter-belona/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 703, in test
    self.tested_ckpt_path = self.__load_ckpt_weights(ckpt_path)
  File "/home/jupyter-belona/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1144, in __load_ckpt_weights
    f'`.{fn}(ckpt_path="best")` is set but `ModelCheckpoint` is not configured to save the best model.'
pytorch_lightning.utilities.exceptions.MisconfigurationException: `.test(ckpt_path="best")` is set but `ModelCheckpoint` is not configured to save the best model.
```

**Comment by ananthsub** [comment]
What version of Lightning are you using? 
In this case, you're calling `trainer.test` without passing the model in. You're also not using any checkpoint callbacks that monitor a value to determine what the "best" model checkpoint to use is. 

Have you tried `class_trainer.test(classifier, dataloaders=test_dataloader)` ?

**Comment by tchaton** [comment]
Dear @etetteh, any progress on your side ?

**Comment by etetteh** [comment]
I am using the latest version of lightning.
I get the same error whether I use model checkpointing, by monitoring validation accuracy or not.

I just tried .test(classifier, test_dataloader), and I'm getting the same error
