### ISSUE TITLE
Metrics cannot used with dictionaries in pl.LightningModule

### ISSUE THREAD

**Issue by ifsheldon** [PyTorchLightning/pytorch-lightning#8775]
## 🐛 Bug

When I try to use a dictionary to store my metrics, it seems those stored metrics will not be correctly registered, which leads to `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

### To Reproduce

```python
import torchmetrics as metrics
# in __init__ of a pl.LightningModule
def __init__(self):
    # ...
    self.train_metrics = {
            "top1_acc": metrics.Accuracy(top_k=1),
            "top5_acc": metrics.Accuracy(top_k=5),
        }

def training_step_end(self, step_outputs):
    preds = step_outputs["preds"]
    targets = step_outputs["targets"]
    for metric_name in self.train_metrics:
        metric = self.train_metrics[metric_name]
        self.log(metric_name, metric(preds, targets))
```
but this is okay
```python
def __init__(self):
    # ...
    self.top1 = metrics.Accuracy(top_k=1)
    self.top5 = metrics.Accuracy(top_k=5)
    self.train_metrics = {
            "top1_acc": self.top1,
            "top5_acc": self.top5,
        }
```

### Expected behavior
It gives the below error messages. I think it's because metrics stored in the dictionary were not registered.

```shell
Traceback (most recent call last):
  File "E:\code\MPL_Lightning\tests\simple_tests.py", line 13, in <module>
    test_data()
  File "E:\code\MPL_Lightning\tests\simple_tests.py", line 9, in test_data
    trainer.fit(model, data_module)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 553, in fit
    self._run(model)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 918, in _run
    self._dispatch()
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 996, in run_stage
    return self._run_train()
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 101, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 153, in advance
    result = self._run_optimization(batch_idx, split_batch)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 204, in _run_optimization
    result = self._training_step(split_batch, batch_idx, opt_idx, self._hiddens)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 310, in _training_step
    training_step_output = self.trainer.call_hook("training_step_end", training_step_output)
  File "E:\conda\envs\torch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1224, in call_hook
    output = hook_fx(*args, **kwargs)
  File "E:\code\MPL_Lightning\mpl_lightning\pl_modules.py", line 257, in training_step_end
    metric(s_pred_labeled, targets)
  File "E:\conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\conda\envs\torch\lib\site-packages\torchmetrics\metric.py", line 190, in forward
    self.update(*args, **kwargs)
  File "E:\conda\envs\torch\lib\site-packages\torchmetrics\metric.py", line 249, in wrapped_func
    return update(*args, **kwargs)
  File "E:\conda\envs\torch\lib\site-packages\torchmetrics\classification\accuracy.py", line 263, in update
    self.tp += tp
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Epoch 0:   0%|          | 0/1 [00:07<00:07,  7.47s/it] 

Process finished with exit code 1


```

### Environment

```shell
* CUDA:
        - GPU:
                - Quadro RTX 8000
                - Quadro RTX 8000
        - available:         True
        - version:           11.0
* Packages:
        - numpy:             1.20.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.7.1
        - pytorch-lightning: 1.4.1
        - tqdm:              4.61.2
        - torchmetrics   0.4.1
* System:
        - OS:                Windows
        - architecture:
                - 64bit
                - WindowsPE
        - processor:         Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
        - python:            3.9.1
        - version:           10.0.18362
```

**Comment by ananthsub** [comment]
Instead of using a dict, use ModuleDict for these to be automatically moved to the right device: https://torchmetrics.readthedocs.io/en/latest/pages/overview.html#metrics-and-devices

**Comment by ifsheldon** [comment]
I see and sorry for missing that of the doc. Thank you!
