### ISSUE TITLE
cannot import name 'container_abcs' from 'torch._six'

### ISSUE THREAD

**Issue by bobiblazeski** [PyTorchLightning/pytorch-lightning#8820]
## 🐛 Bug

I've just created new environment with  python 3.8,  torch 1.9.0 and cuda 11 and I'm unable to use lightning
### Expected behavior
Being able to import lightning
import pytorch_lightning as pl

### Environment

I've commented pl code because the script fail to import it
-->
python collect_env_details.py
* CUDA:
	- GPU:
		- GeForce RTX 2070
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.18.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0
	- tqdm:              4.46.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.11
	- version:           #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021

- How you installed PyTorch (`conda`, `pip`, source): conda
- Any other relevant information:
```
raceback (most recent call last):
  File "collect_env_details.py", line 29, in <module>
    import pytorch_lightning  # noqa: E402
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 27, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_AVAILABLE
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py", line 72, in <module>
    _APEX_AVAILABLE = _module_available("apex.amp")
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py", line 37, in _module_available
    return find_spec(module_path) is not None
  File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/home/bobi/.local/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/home/bobi/.local/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/bobi/.local/lib/python3.8/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/home/bobi/.local/lib/python3.8/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/home/bobi/.local/lib/python3.8/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/home/bobi/.local/lib/python3.8/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/torch/_six.py)
```

**Comment by Borda** [comment]
can you share what Torch version are you using?

**Comment by bobiblazeski** [comment]
>>> import torch
>>> torch.__version__
'1.9.0'

**Comment by Borda** [comment]
mind try re-build your AMP from latest?

**Comment by bobiblazeski** [comment]
Could you point the instructions how to do that?

Is that the same as apex, since  I'm unable to build apex manually. I could only use  it previously via the one included in pytorch 

> git clone https://github.com/NVIDIA/apex
> cd apex
> pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
apex$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pip/_internal/commands/install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.2.2 from /home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/site-packages/pip (python 3.8)
Processing /home/bobi/Desktop/pic2mesh/apex
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Running command python setup.py egg_info


    torch.__version__  = 1.9.0


    running egg_info
    creating /tmp/pip-pip-egg-info-sbavbw2w/apex.egg-info
    writing /tmp/pip-pip-egg-info-sbavbw2w/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-sbavbw2w/apex.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-sbavbw2w/apex.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-sbavbw2w/apex.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-sbavbw2w/apex.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-sbavbw2w/apex.egg-info/SOURCES.txt'
    /tmp/pip-req-build-rm6xte2z/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
  Attempting uninstall: apex
    Found existing installation: apex 0.1
    Uninstalling apex-0.1:
      Removing file or directory /home/bobi/.local/lib/python3.8/site-packages/apex-0.1.dist-info/
      Removing file or directory /home/bobi/.local/lib/python3.8/site-packages/apex/
      Successfully uninstalled apex-0.1
    Running command /home/bobi/miniconda3/envs/pytorch3d_05/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rm6xte2z/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rm6xte2z/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-2msa4fle/install-record.txt --single-version-externally-managed --compile --install-headers /home/bobi/miniconda3/envs/pytorch3d_05/include/python3.8/apex


    torch.__version__  = 1.9.0


    /tmp/pip-req-build-rm6xte2z/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-rm6xte2z/setup.py", line 171, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-rm6xte2z/setup.py", line 94, in check_cuda_torch_binary_vs_bare_metal
        raw_output, bare_metal_major, bare_metal_minor = get_cuda_bare_metal_version(cuda_dir)
      File "/tmp/pip-req-build-rm6xte2z/setup.py", line 84, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
      File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/subprocess.py", line 493, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/bobi/miniconda3/envs/pytorch3d_05/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/lib/nvidia-cuda-toolkit/bin/nvcc'
    Running setup.py install for apex ... error
  Rolling back uninstall of apex
  Moving to /home/bobi/.local/lib/python3.8/site-packages/apex-0.1.dist-info/
   from /home/bobi/.local/lib/python3.8/site-packages/~pex-0.1.dist-info
  Moving to /home/bobi/.local/lib/python3.8/site-packages/apex/
   from /home/bobi/.local/lib/python3.8/site-packages/~pex
ERROR: Command errored out with exit status 1: /home/bobi/miniconda3/envs/pytorch3d_05/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rm6xte2z/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rm6xte2z/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-2msa4fle/install-record.txt --single-version-externally-managed --compile --install-headers /home/bobi/miniconda3/envs/pytorch3d_05/include/python3.8/apex Check the logs for full command output.
```

**Comment by bobiblazeski** [comment]
I've managed to fix this by creating new environment, installing pytorch, then lightning then manually installing  pytz &  python-dateutil, then the rest my packages.
