### ISSUE TITLE
Unable to save prediction dict in predict_step

### ISSUE THREAD

**Issue by celsofranssa** [PyTorchLightning/pytorch-lightning#8876]
In `pytorch-lightning~=1.4.1` the predictions is normally saved using:

```python
def test_step(self, batch, batch_idx):
        idx, text, true_cls = batch["idx"], batch["text"], batch["cls"]
        rpr = self.encoder(text)
        pred_cls = torch.argmax(self.cls_head(rpr), dim=-1)

        self.write_prediction_dict(
            {
                "idx": idx,
                "rpr": rpr,
                "true_cls": true_cls,
                "pred_cls": pred_cls
            },
            self.hparams.prediction.dir + self.hparams.prediction.name)
```
Howerver in `predict_step` using the same logic:

```python
    def predict_step(self, batch, batch_idx, dataloader_idx=None):
        idx, text, true_cls = batch["idx"], batch["text"], batch["cls"]
        rpr = self.encoder(text)
        pred_cls = torch.argmax(self.cls_head(rpr), dim=-1)

        self.write_prediction_dict(
            {
                "idx": idx,
                "rpr": rpr,
                "true_cls": true_cls,
                "pred_cls": pred_cls
            },
            self.hparams.representation.dir + self.hparams.representation.name)
```
raises the following error message:

```python
Traceback (most recent call last):
  File "main.py", line 151, in perform_tasks
    predict(params)
  File "main.py", line 136, in predict
    datamodule=dm
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 776, in predict
    results = self._run(model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 984, in _dispatch
    self.accelerator.start_predicting(self)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 98, in start_predicting
    self.training_type_plugin.start_predicting(trainer)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 169, in start_predicting
    self._results = trainer.run_stage()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_predict()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1095, in _run_predict
    return self.predict_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 92, in advance
    dataloader_iter, self.current_dataloader_idx, dl_max_batches, self.num_dataloaders, self.return_predictions
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 98, in advance
    self._predict_step(batch, batch_idx, dataloader_idx)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 131, in _predict_step
    predictions = self.trainer.accelerator.predict_step(step_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 241, in predict_step
    return self.training_type_plugin.predict_step(*step_kwargs.values())
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 184, in predict_step
    return self.model.predict_step(*args, **kwargs)
  File "/content/TeCBench/source/model/TeCModel.py", line 97, in predict_step
    self.hparams.representation.dir + self.hparams.representation.name)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/lightning.py", line 605, in write_prediction_dict
    self.write_prediction(k, v, filename)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/lightning.py", line 578, in write_prediction
    self.trainer._evaluation_loop.predictions._add_prediction(name, value, filename)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/properties.py", line 606, in _evaluation_loop
    raise RuntimeError("The `Trainer._evaluation_loop` property isn't defined. Accessed outside of scope")
RuntimeError: The `Trainer._evaluation_loop` property isn't defined. Accessed outside of scope
```

**Comment by Borda** [comment]
is this related also to #8875?

**Comment by celsofranssa** [comment]
Hello @Borda,
These two issues have the same objective: save the prediction dictionary. In #8875, I was thinking about the new feature using  `BasePredictionWriter` callback, and here, I was unable to save predictions dictionary using `write_prediction_dict` which is available in PL 1.4.1.

**Comment by tchaton** [comment]
Dear @celsofranssa,

Yes, I would recommend to use the `BasePredictionWriter`, this is safer and would work better depending on which accelerators you might be using.

Best,
T.C

**Comment by celsofranssa** [comment]
Thank you @tchaton,
Currently, I am trying to apply `BasePredictionWriter` to save the predictions as it was done using `write_prediction_dict` (#8875 ).
