### ISSUE TITLE
MisconfigurationException GPUs on updating lightning

### ISSUE THREAD

**Issue by brucemuller** [PyTorchLightning/pytorch-lightning#899]
Not sure what's going on here. I updated to the latest pytorch version:
Can anyone help?
I also included my environment packages.
```
Traceback (most recent call last):
  File "train_gpu.py", line 232, in <module>
    main_local(hparam_trial)   
  File "train_gpu.py", line 106, in main_local
    trainer = Trainer(logger = tt_logger , use_amp=False, gpus=1 ,min_nb_epochs=1002, max_nb_epochs=1003)  # amp_level='O2' ,
  File "/home/bruce/anaconda3/envs/ln2/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 530, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(gpus)
  File "/home/bruce/anaconda3/envs/ln2/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 563, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/home/bruce/anaconda3/envs/ln2/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 533, in sanitize_gpu_ids
    raise MisconfigurationException(message)
pytorch_lightning.utilities.debugging.MisconfigurationException: 
            You requested GPUs: [0]
            But your machine only has: []
```
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.1                       cpu_0  
absl-py                   0.9.0                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
cachetools                4.0.0                    pypi_0    pypi
certifi                   2019.11.28               py37_0  
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
freetype                  2.9.1                h8a8886c_1  
future                    0.18.2                   pypi_0    pypi
google-auth               1.11.2                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.27.2                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
imageio                   2.8.0                    pypi_0    pypi
intel-openmp              2020.0                      166  
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
markdown                  3.2.1                    pypi_0    pypi
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0  
openssl                   1.1.1d               h7b6447c_4  
pandas                    1.0.1                    pypi_0    pypi
pillow                    6.2.1            py37hd70f55b_1    conda-forge
pip                       20.0.2                   py37_1  
protobuf                  3.11.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.19                     py37_0  
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.3.1           cpu_py37h62f834f_0  
pytorch-lightning         0.6.0                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scikit-learn              0.22.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                45.2.0                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               h7b6447c_0  
tensorboard               2.1.0                    pypi_0    pypi
test-tube                 0.7.5                    pypi_0    pypi
tk                        8.6.10               hed695b0_0    conda-forge
torchvision               0.4.2           cpu_py37h9ec355b_0  
tqdm                      4.43.0                   pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
werkzeug                  1.0.0                    pypi_0    pypi
wheel                     0.34.2                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

```

**Comment by awaelchli** [comment]
Have not tested it myself, but I suspect if you have the CPU version of PyTorch installed it won't see any CUDA devices even if you run it on a machine that has them.
Try installing the PyTorch package that was compiled with CUDA manually.

**Comment by awaelchli** [comment]
You have the CPU version of PyTorch installed but are requesting computation on a GPU. This won't work even if you have the hardware. Install PyTorch with CUDA binaries. You can select the CUDA version here: https://pytorch.org/

**Comment by Borda** [comment]
@awaelchli thx for your fast reply! 
@brucemuller feel free to reopen if you need something more :robot:

**Comment by brucemuller** [comment]
Oooops not sure how I managed that! Thanks!
