### ISSUE TITLE
AdvancedProfiler: ValueError: Attempting to stop recording an action (run_test_evaluation) which was never started.

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#9136]
## 🐛 Bug

If you have multiple Trainers and only one runs test, afterwards AdvancedProfiler crashes. This happens even if you free all Trainers except the one you want to run test on.

I have code that has multiple Trainers, doing a grid search. To each Trainer, I just added AdvancedProfiler.

I find the Trainer with the best_model_score and run test only on the best predictor. I then get this crash:

```
DATALOADER:0 TEST RESULTS
{'test_chroma_acc': 0.05000000074505806,
 'test_loss': 1763.811279296875,
 'test_pitch_acc': 0.0}
--------------------------------------------------------------------------------
Testing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 22.07it/s]
  0%|                                                                                                                                                                                                       | 0/3 [00:24<?, ?it/s]
Traceback (most recent call last):
  File "/Users/joseph/dev/neuralaudio/hear-eval-kit/heareval/predictions/runner.py", line 75, in <module>
    runner()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/joseph/dev/neuralaudio/hear-eval-kit/heareval/predictions/runner.py", line 69, in runner
    task_predictions(
  File "/Users/joseph/dev/neuralaudio/hear-eval-kit/heareval/predictions/task_predictions.py", line 772, in task_predictions
    test_scores = best_trainer.test(ckpt_path="best", test_dataloaders=test_dataloader)
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 706, in test
    results = self._run(model)
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 982, in _dispatch
    self.accelerator.start_evaluating(self)
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 95, in start_evaluating
    self.training_type_plugin.start_evaluating(trainer)
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 165, in start_evaluating
    self._results = trainer.run_stage()
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 993, in run_stage
    return self._run_evaluate()
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1079, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/profiler/base.py", line 97, in profile
    self.stop(action_name)
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/profiler/advanced.py", line 70, in stop
    raise ValueError(f"Attempting to stop recording an action ({action_name}) which was never started.")
ValueError: Attempting to stop recording an action (run_test_evaluation) which was never started.

```

### To Reproduce

https://colab.research.google.com/drive/1rnd1kmwea5BiAYwXq4WaAg5fa8T6GlUI?usp=sharing

I tried to reproduce but BoringModel is currently broken:

```
# some other options for random data
from pl_bolts.datasets import RandomDataset, DummyDataset, RandomDictDataset
/usr/local/lib/python3.7/dist-packages/pl_bolts/utils/warnings.py:32: UserWarning: You want to use `wandb` which is not installed yet, install it with `pip install wandb`.
  f' install it with `pip install {pypi_name}`.' + extra_text

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-3-da4ba0fec73f> in <module>()
      1 # some other options for random data
----> 2 from pl_bolts.datasets import RandomDataset, DummyDataset, RandomDictDataset

5 frames

/usr/local/lib/python3.7/dist-packages/pl_bolts/__init__.py in <module>()
     17 _HTTPS_AWS_HUB = "https://pl-bolts-weights.s3.us-east-2.amazonaws.com"
     18 
---> 19 from pl_bolts import (  # noqa: E402
     20     callbacks,
     21     datamodules,

/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/__init__.py in <module>()
      3 from pl_bolts.datamodules.cifar10_datamodule import CIFAR10DataModule, TinyCIFAR10DataModule
      4 from pl_bolts.datamodules.cityscapes_datamodule import CityscapesDataModule
----> 5 from pl_bolts.datamodules.experience_source import DiscountedExperienceSource, ExperienceSource, ExperienceSourceDataset
      6 from pl_bolts.datamodules.fashion_mnist_datamodule import FashionMNISTDataModule
      7 from pl_bolts.datamodules.imagenet_datamodule import ImagenetDataModule

/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/experience_source.py in <module>()
     22 
     23 
---> 24 class ExperienceSourceDataset(IterableDataset):
     25     """
     26     Basic experience source dataset. Takes a generate_batch function that returns an iterator.

/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py in __new__(cls, name, bases, namespace, **kwargs)
    271         for base in bases:
    272             if isinstance(base, _DataPipeMeta):
--> 273                 return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
    274 
    275         namespace.update({'type': _DEFAULT_TYPE,

/usr/lib/python3.7/abc.py in __new__(mcls, name, bases, namespace, **kwargs)
    124         """
    125         def __new__(mcls, name, bases, namespace, **kwargs):
--> 126             cls = super().__new__(mcls, name, bases, namespace, **kwargs)
    127             _abc_init(cls)
    128             return cls

/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py in _dp_init_subclass(sub_cls, *args, **kwargs)
    369                      return_hint.__origin__ == collections.abc.Iterator)):
    370                 raise TypeError("Expected 'Iterator' as the return annotation for `__iter__` of {}"
--> 371                                 ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
    372             data_type = return_hint.__args__[0]
    373             if not issubtype(data_type, sub_cls.type.param):

TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```

### Expected behavior

Profiling should continue as expected, and output for test only for the trainer which ran test.

### Environment
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0
	- pytorch-lightning: 1.4.1
	- tqdm:              4.62.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		-
	- processor:         i386
	- python:            3.9.6
	- version:           Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64

**Comment by Stark-developer01** [comment]
I read thorugh the comment thread, can I take up this one to help to fix the issue?

**Comment by tchaton** [comment]
Hey @ Stark-developer01,

Yes, please have a look and open a PR if you have a fix.

Best,
T.C

**Comment by Stark-developer01** [comment]
Fine, let me replicate the bug on my colab.

**Comment by Stark-developer01** [comment]
> Hey @turian,
> 
> It is interesting, I have the impression the bug is actually related to Colab.
> 
> This works locally.
> 
> ```python
> def test_advanced_profiler_on_test(tmpdir):
> 
>     ds = RandomDataset(32, 64)
>     loader = DataLoader(ds)
>     model = BoringModel()
> 
>     def run(tmpdir):
>         trainer = Trainer(
>             default_root_dir=tmpdir,
>             max_epochs=1,
>             progress_bar_refresh_rate=20,
>             profiler="advanced"
>         )
> 
>         trainer.fit(model, loader, loader)
>         trainer.test(test_dataloaders=loader)
> 
>         return trainer
> 
>     for _ in range(4):
>         trainer = run(tmpdir)
> 
>     trainer.test(test_dataloaders=loader)
> ```

Hey I successfully replicated the bug, the problem seems to be lying during the test after calling fit, specifically our dictionary object `pr = self.profiled_actions.get(action_name)` is trying to return the value of the `(action_name)` and is getting assigned a null value with nonetype. It is unable to find the value and getting a null value at the action `run_test_evaluation`.

I am trying to dig into the class `AdvancedProfiler` to look out for a possible fix, but if it is running locally then might be there are some environment variables related issue or any os  factors involved.

However I am still debugging, I will contact for any help.

`/usr/local/lib/python3.7/dist-packages/pytorch_lightning/profiler/advanced.py in stop(self, action_name)
     68         pr = self.profiled_actions.get(action_name)
     69         if pr is None:
---> 70             raise ValueError(f"Attempting to stop recording an action ({action_name}) which was never started.")
     71         pr.disable()
     72 

ValueError: Attempting to stop recording an action (run_test_evaluation) which was never started.`

**Comment by turian** [comment]
@Stark-developer01 do you have access to an OSX machine you can try on too? That's my local arch where I also have this issue.

**Comment by Stark-developer01** [comment]
@turian Yes, I have a Macbook, I will be trying out on that as well.

**Comment by breznak** [comment]
Hi, I'm having the same issue on Linux / x86_64 arch, using a single trainer (I'm running the task through PyCharm IDE). 

```
 File "xxx/lib/python3.6/site-packages/mixer/pl/trainer.py", line 44, in train
    self.fit(model=model, datamodule=datamodule)
  File "xxx/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "xxx/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 927, in _run
    self.call_hook("on_fit_end")
  File "xxx/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1235, in call_hook
    output = accelerator_output if output is None else output
  File "xxx/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "xxx/lib/python3.6/site-packages/pytorch_lightning/profiler/base.py", line 97, in profile
    self.stop(action_name)
  File "xxx/lib/python3.6/site-packages/pytorch_lightning/profiler/advanced.py", line 70, in stop
    raise ValueError(f"Attempting to stop recording an action ({action_name}) which was never started.")
ValueError: Attempting to stop recording an action (on_fit_end) which was never started.
```

Using `SimpleProfiler` passes ok, I'm using a few callbacks including ModelCheckpoint, EarlyStopping,...

**Comment by tbenst** [comment]
I have the same issue with `AdvancedProfiler` when I call `.start` and `.stop` manually. It appears to be broken. `SimpleProfiler` works just fine, however.

**Comment by pooyanazad** [comment]
Hi! I'd like to work on this issue.

I've identified the root cause: when a context manager is active during teardown, teardown() clears the profiled_actions, and then the context manager's finally block calls stop() which crashes because the action is no longer in the dict.

I will fix this by making stop() return silently if the action doesn't exist, and I'll also add regression tests. I'll submit a PR shortly!

**Comment by Educoheng1** [comment]
Hi — I’d like to work on this issue. I’ll reproduce the error using the Colab repro linked in the issue, inspect pytorch_lightning/profiler/advanced.py, and implement a minimal fix so stop() is only called for actions that were started (e.g., add a guard or track started actions). I’ll also add a regression test that exercises the multi-Trainer / test flow and prevents this ValueError from recurring. I expect to open a PR within a few days that references this issue and includes the test and change
