### ISSUE TITLE
CLI's instantiate_classes fails to instantiate Callbacks

### ISSUE THREAD

**Issue by quancs** [PyTorchLightning/pytorch-lightning#9186]
## 🐛 Bug

CLI's instantiate_classes fails to instantiate model and datamodule. Thus, when I run fit, Lightning gives me an error:

```
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
D:\projects\NBSS_lightning\pytorch_lightning\trainer\trainer.py:1360: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
  rank_zero_warn(
Traceback (most recent call last):
  File "trainer.py", line 31, in <module>
    cli = LightningCLI(model_class=MyClassModel, datamodule_class=MyDataModule)
  File "D:\projects\NBSS_lightning\pytorch_lightning\utilities\cli.py", line 284, in __init__
    self._run_subcommand(self.subcommand)
  File "D:\projects\NBSS_lightning\pytorch_lightning\utilities\cli.py", line 505, in _run_subcommand
    fn(**fn_kwargs)
  File "D:\projects\NBSS_lightning\pytorch_lightning\trainer\trainer.py", line 547, in fit
    self._call_and_handle_interrupt(self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule)
  File "D:\projects\NBSS_lightning\pytorch_lightning\trainer\trainer.py", line 502, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\projects\NBSS_lightning\pytorch_lightning\trainer\trainer.py", line 573, in _fit_impl
    self.data_connector.attach_data(
  File "D:\projects\NBSS_lightning\pytorch_lightning\trainer\connectors\data_connector.py", line 181, in attach_data
    self.attach_datamodule(model, datamodule=datamodule)
  File "D:\projects\NBSS_lightning\pytorch_lightning\trainer\connectors\data_connector.py", line 225, in attach_datamodule
    if is_overridden(method, datamodule):
  File "D:\projects\NBSS_lightning\pytorch_lightning\utilities\model_helpers.py", line 45, in is_overridden
    raise ValueError("Expected a parent")
ValueError: Expected a parent
```

When I debug the instantiate_classes func in CLI, I found:
```
        self.datamodule = self._get(self.config_init, "data") # self.datamodule is a dict not MyClassModel
```

### To Reproduce

```
# trainer.py
from pytorch_lightning.utilities.cli import LightningCLI
from pytorch_lightning import LightningModule, LightningDataModule

class MyClassModel(LightningModule):

    def __init__(self, num_classes: int = 2):
        self.num_classes = num_classes

class MyDataModule(LightningDataModule):

    def __init__(self, num_classes: int = 2, files: str = "xxx"):
        self.num_classes = num_classes

cli = LightningCLI(model_class=MyClassModel, datamodule_class=MyDataModule)
```

save configs:
```python trainer.py fit --print_config > cfg.yaml```

fit:
```python trainer.py fit --config cfg.yaml```

### Expected behavior
run fit

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): pytorch-lightning-1.5.0.dev0
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

I guess the problem here is that the `data` and `model` section in the generated config file don't have init_args and class_path.

**Comment by carmocca** [comment]
I believe you need to update your jsonargparse version

`pip install -U jsonargparse[signatures]`
(should be 3.18.0)

Please, close the issue if that works for you :)

**Comment by quancs** [comment]
It works. Thx @carmocca

**Comment by quancs** [comment]
Hi @carmocca , I found `add_lightning_class_args` not working. The trainer created by `MyLightningCLI` not containing a `EarlyStopping`

```
class MyLightningCLI(LightningCLI):

    def add_arguments_to_parser(self, parser):
        parser.add_lightning_class_args(EarlyStopping, "my_early_stopping")
        parser.set_defaults({"my_early_stopping.patience": 5})

cli = MyLightningCLI(model_class=MyClassModel, datamodule_class=MyDataModule)
```
