### ISSUE TITLE
Add TRAINS experiment manager support

### ISSUE THREAD

**Issue by bmartinn** [PyTorchLightning/pytorch-lightning#929]
## :train2: Add [TRAINS](https://github.com/allegroai/trains) experiment manager support
Integrate the TRAINS experiment manager with pytorch lightning.
Following TRAINS [Issue #107](https://github.com/allegroai/trains/issues/107)

### Motivation

Extend the compatibility of pytorch-lightning logger to support the TRAINS experiment manager.

### Pitch

PR code can be reviewed [here](https://github.com/bmartinn/pytorch-lightning/commit/3a868d82c87bb2a7aef6f086c284e194e98ccf7f)

**Comment by bmartinn** [comment]
Thanks to @S-aiueo32 + documentation and type hinting, details [here](https://github.com/bmartinn/pytorch-lightning/commit/1f53519177df7622382bfb7cf68b5e42c5b2e619)

Dear PyTorch-Lightning Team, Could I push the PR?

**Comment by Borda** [comment]
@bmartinn sure, PR is welcome :]
cc: @PyTorchLightning/core-contributors

**Comment by williamFalcon** [comment]
awesome. go for it!

**Comment by williamFalcon** [comment]
@bmartinn  this logger is causing a lot of issues. please fix asap, otherwise we'll have to remove it.

@Borda can you elaborate on the issues?

```
Traceback (most recent call last):
  File "/home/waf251/media/falcon_kcgscratch1/software/miniconda3/envs/pl10/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/waf251/media/falcon_kcgscratch1/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/backend_interface/logger.py", line 197, in run
    while not self._exit_event.wait(period or 1.0):
  File "/home/waf251/media/falcon_kcgscratch1/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/logger.py", line 522, in flush
    return self._task.flush()
  File "/home/waf251/media/falcon_kcgscratch1/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/task.py", line 751, in flush
    LoggerRoot.flush()
  File "/home/waf251/media/falcon_kcgscratch1/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/debugging/log.py", line 92, in flush
    h.flush()
  File "/home/waf251/media/falcon_kcgscratch1/software/miniconda3/envs/pl10/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
ValueError: I/O operation on closed file.
```

**Comment by bmartinn** [comment]
@williamFalcon is this on the master branch?
How do I reproduce it?

**Comment by Borda** [comment]
@bmartinn pls see #1352
