### ISSUE TITLE
'DataHooks' object has no attribute 'on_init_start'

### ISSUE THREAD

**Issue by smivv** [PyTorchLightning/pytorch-lightning#9290]
## 🐛 Bug

I am getting an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clearml/binding/hydra_bind.py", line 146, in _patched_task_function
    return task_function(a_config, *a_args, **a_kwargs)
  File "run.py", line 38, in main
    config.target.checkpoint_path = train(config)
  File "/workdir/src/train.py", line 61, in train
    trainer: Trainer = instantiate(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(target, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    self.on_init_start()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/callback_hook.py", line 62, in on_init_start
    callback.on_init_start(self)
AttributeError: Error instantiating 'pytorch_lightning.trainer.trainer.Trainer' : 'DataHooks' object has no attribute 'on_init_start'
```

### To Reproduce

It's quite hard to reproduce since my project is large.

### Expected behavior

I guess should be no error :)

### Environment

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
                - NVIDIA GeForce RTX 3090
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cu111
        - pytorch-lightning: 1.4.1
        - tqdm:              4.59.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.5
        - version:           #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021

### Additional context

Previously I had no such error, but I've changed something and now I am unable to run the pipeline.

**Comment by smivv** [comment]
Actually found the problem :)

**Comment by ananthsub** [comment]
> Actually found the problem :)

Could you comment here what the problem was and how you resolved it, so others that come to this issue know how to fix it?

**Comment by smivv** [comment]
Well, actually I made quite stupid mistake and set DataHook to callbacks 😄
