### ISSUE TITLE
Python random.setstate type error when resuming from fault-tolerant training 

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#9400]
## 🐛 Bug

Resuming from a fault-tolerant enabled checkpoint will error when resetting the python rng state through 
`random.setstate`, where a tuple is expected.

### To Reproduce

Can't reproduce on our side. User has run the following script: 

```py
import os

from torch.utils.data import DataLoader

from pytorch_lightning import Trainer
from pytorch_lightning.plugins import DeepSpeedPlugin
from tests.helpers import RandomDataset, BoringModel


class SimpleModel(BoringModel):
    def __init__(self, fail=True):
        super().__init__()
        self.fail = fail

    def training_step(self, batch, batch_idx):
        out = super().training_step(batch, batch_idx)
        if self.fail and self.current_epoch == 0 and batch_idx == 1:
            raise RuntimeError("fault tolerant exception")
        return out


def run(simulate_failure):
    os.environ["PL_FAULT_TOLERANT_TRAINING"] = "1"
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=2)

    model = SimpleModel(fail=simulate_failure)
    model.training_epoch_end = None
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        num_sanity_val_steps=0,
        max_epochs=1,
        weights_summary=None,
        precision=16,
        gpus=2,
        resume_from_checkpoint=(None if simulate_failure else ".pl_auto_save.ckpt"),
        plugins="deepspeed_stage_2",
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)


if __name__ == "__main__":
    run(simulate_failure=True)
    # run(simulate_failure=False)
```

```bash
Original Traceback (most recent call last):
  File "/cluster/projects/nn5018k/.conda/dnagen/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/cluster/projects/nn5018k/.conda/dnagen/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cluster/projects/nn5018k/.conda/dnagen/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cluster/work/users/gurvinder/pytorch-lightning/pytorch_lightning/utilities/auto_restart.py", line 230, in __getitem__
    set_rng_states(self._cached_state_dict[self.worker_id]["rng_states"])
  File "/cluster/work/users/gurvinder/pytorch-lightning/pytorch_lightning/utilities/auto_restart.py", line 266, in set_rng_states
    python_set_rng_state(tuple(rng_state_dict.get("python")))
  File "/cluster/projects/nn5018k/.conda/dnagen/lib/python3.9/random.py", line 177, in setstate
    super().setstate(internalstate)
TypeError: state vector must be a tuple
```

https://github.com/python/cpython/blob/37272f5800ee1e9fcb2da4a1766366519b9b3d94/Modules/_randommodule.c#L431

### Expected behavior

The state should already be a tuple as we never modify it. The underlying check for the tuple is in cypython. 

### Environment

- PyTorch Lightning Version: master
- PyTorch Version: 1.9
- Python version: 3.9
- OS (e.g., Linux): Linux

### Additional context

Reported by @gurvindersingh on Slack

**Comment by tchaton** [comment]
Hey @awaelchli,

I seems to be working for me too.

Best,
T.C
