### ISSUE TITLE
Validation sometimes fails when training on multiple gpus, real error hidden by bad re-raise.

### ISSUE THREAD

**Issue by jmerkow** [PyTorchLightning/pytorch-lightning#9548]
I am having a strange issue training my PL model with multiple GPUs, using `accelerator="dp"` (have not tried others). My code works fine when training using one GPU, but I get an error somewhere in `parallel_apply` with multiple GPUs, then it appears the the error isn't handled correctly by re-raise so I am not sure what is going on.  The error is also appearing inconsistently, but always during validation (sometimes during sanity check, sometimes later).

I am running on Environment:
>  AzureML, VM Standard_NC24 (24 cores, 224 GB RAM, 1440 GB disk)
>  Python 3.7
>  Pytorch Lightning Version: 1.4.7
>  Pytorch Version: 1.8.0

Full Error:

```python
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    trainer.fit(vae)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in _run_train
    self.fit_loop.run()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 112, in run
    self.on_advance_end()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 177, in on_advance_end
    self._run_validation()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 257, in _run_validation
    self.val_loop.run()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dataloader_iter, self.current_dataloader_idx, dl_max_batches, self.num_dataloaders
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 158, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/dp.py", line 96, in validation_step
    return self.model(*args, **kwargs)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/azureml-envs/azureml_3a678fb3c063cd17fe3b93d28a5df6cf/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(message=msg)
TypeError: __init__() missing 1 required positional argument: 'exception_message'```

**Comment by SeanNaren** [comment]
Is there a reason you're using DP? Any chance you could try `DDP` instead?

**Comment by jmerkow** [comment]
So running with `"ddp"` seems to make it really really slow (1.5 hours per epoch, to 9 hours per epoch).  I am also now getting this error: 


```python
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    trainer.fit(vae)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in _run_train
    self.fit_loop.run()
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 147, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 201, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 403, in _optimizer_step
    using_lbfgs=is_lbfgs,
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1616, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 206, in step
    self.__optimizer_step(closure=closure, profiler_name=profiler_name, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 128, in __optimizer_step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 296, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 303, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 226, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 235, in _training_step_and_backward_closure
    result = self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, hiddens)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 536, in training_step_and_backward
    result = self._training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 384, in training_step
    return self.model(*args, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops_shared/azureml/chexpert-images-vae-new_1631984220_3cd86d7b/wd/azureml/chexpert-images-vae-new_1631984220_3cd86d7b/model.py", line 239, in training_step
    loss, logs, image_batch_recon = self.step(batch)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops_shared/azureml/chexpert-images-vae-new_1631984220_3cd86d7b/wd/azureml/chexpert-images-vae-new_1631984220_3cd86d7b/model.py", line 217, in step
    p, q, z = self.sample(mu, logvar)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops_shared/azureml/chexpert-images-vae-new_1631984220_3cd86d7b/wd/azureml/chexpert-images-vae-new_1631984220_3cd86d7b/model.py", line 154, in sample
    q = torch.distributions.Normal(mu, std)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/distributions/normal.py", line 50, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/azureml-envs/azureml_ea1196074ca4d939b40cb444c370ed4b/lib/python3.7/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter loc has invalid values
```

**Comment by jmerkow** [comment]
I figured this issue out, I have code that is similar to the vae in lighting bolts, essentially if the encoder fails (i.e. while using auto_find_lr), it produces nans, which torch.distribution.Normal cannot handle. if you update q to `q = torch.distributions.Normal(mu.nan_to_num(0), std.nan_to_num(float("inf")))` it will produce inf which should cause the early stopper to fire.  I can make a PR on LB so fix this issue.
