### ISSUE TITLE
Multi-GPU DDP hangs when saving checkpoint.

### ISSUE THREAD

**Issue by jasonf7** [PyTorchLightning/pytorch-lightning#9611]
## 🐛 Bug

In the Multi-GPU DDP setting, model training hangs after validation at the end of the first training epoch with the following stacktrace (looks like it fails while trying to save the checkpoint):
```
   trainer.fit(model, dm)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/training_loop.py", line 574, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 1006, in run_evaluation
    self.evaluation_loop.on_evaluation_end()
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/evaluation_loop.py", line 102, in on_evaluation_end
    self.trainer.call_hook('on_validation_end', *args, **kwargs)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 1223, in call_hook
    trainer_hook(*args, **kwargs)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/callback_hook.py", line 227, in on_validation_end
    callback.on_validation_end(self, self.lightning_module)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 249, in on_validation_end
    self.save_checkpoint(trainer)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 300, in save_checkpoint
    self._save_none_monitor_checkpoint(trainer, monitor_candidates)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 679, in _save_none_monitor_checkpoint
    filepath = self._get_metric_interpolated_filepath_name(monitor_candidates, trainer)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 637, in _get_metric_interpolated_filepath_name
    while self.file_exists(filepath, trainer) and filepath != del_filepath:
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 752, in file_exists
    return trainer.training_type_plugin.broadcast(exists)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/plugins/training_type/ddp.py", line 289, in broadcast
    return self.dist.broadcast(obj)
  File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/distributed/dist.py", line 33, in broadcast
    broadcast_object_list(obj, 0, group=group or _group.WORLD)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 1699, in broadcast_object_list
    object_list[i] = _tensor_to_object(obj_view, obj_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 1418, in _tensor_to_object
    out = pickle.loads(buf)
Traceback (most recent call last): File "/av.runfiles/__main__/perception/sign_classifier/training/trainer.py", line 236, in <module> main(sys.argv[1:]) File "/av.runfiles/__main__/perception/sign_classifier/training/trainer.py", line 232, in main trainer.fit(model, dm) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 458, in fit self._run(model) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 756, in _run self.dispatch() File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 797, in dispatch self.accelerator.start_training(self) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training self.training_type_plugin.start_training(trainer) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training self._results = trainer.run_stage() File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 807, in run_stage return self.run_train() File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 869, in run_train self.train_loop.run_training_epoch() File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/training_loop.py", line 574, in run_training_epoch self.trainer.run_evaluation(on_epoch=True) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 1006, in run_evaluation self.evaluation_loop.on_evaluation_end() File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/evaluation_loop.py", line 102, in on_evaluation_end self.trainer.call_hook('on_validation_end', *args, **kwargs) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/trainer.py", line 1223, in call_hook trainer_hook(*args, **kwargs) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/trainer/callback_hook.py", line 227, in on_validation_end callback.on_validation_end(self, self.lightning_module) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 249, in on_validation_end self.save_checkpoint(trainer) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 300, in save_checkpoint self._save_none_monitor_checkpoint(trainer, monitor_candidates) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 679, in _save_none_monitor_checkpoint filepath = self._get_metric_interpolated_filepath_name(monitor_candidates, trainer) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 637, in _get_metric_interpolated_filepath_name while self.file_exists(filepath, trainer) and filepath != del_filepath: File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 752, in file_exists return trainer.training_type_plugin.broadcast(exists) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/plugins/training_type/ddp.py", line 289, in broadcast return self.dist.broadcast(obj) File "/av/internal_pip_override_dependency_pytorch_lightning/pytorch_lightning/distributed/dist.py", line 33, in broadcast broadcast_object_list(obj, 0, group=group or _group.WORLD) File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 1699, in broadcast_object_list object_list[i] = _tensor_to_object(obj_view, obj_size) File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 1418, in _tensor_to_object out = pickle.loads(buf)

2021-09-17T21:53:10.289-04:00

Copy
EOFError: Ran out of input
```

### To Reproduce

I don't think I can reproduce it, my guess is it might be something wrong with the way I implemented things, any pointers would be greatly appreciated!

### Expected behavior

Should save a checkpoint and continue training.

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): 1.3.2
- PyTorch Version (e.g., 1.8): 1.8.1
- Python version: 3.6.9
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.0/8.0.4
- GPU models and configuration: Tesla V100
- How you installed PyTorch (`conda`, `pip`, source): source
- If compiling from source, the output of `torch.__config__.show()`:
```
'PyTorch built with:\n  - GCC 7.5\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.0\n  - NVCC architecture flags: -gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_37,code=sm_37\n  - CuDNN 8.0.4\n  - Magma 2.5.4\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.0, CUDNN_VERSION=8.0.4, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-march=haswell -mtune=broadwell -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n'
```
- Any other relevant information:

### Additional context

Works fine on single GPU and I did verify that my model is pickleable.

**Comment by tchaton** [comment]
Dear @jasonf7,

Would it be possible for you to provide a reproducible script, with the BoringModel if you ?

Best,
T.C

**Comment by tchaton** [comment]
Dear @jasonf7,

Could it be possible you have uneven number of batches on each rank ? 

Best,
T.C

**Comment by jasonf7** [comment]
Yes I think you hit the nail on the coffin! I'm using webdataset for the data interface and following an example here https://github.com/webdataset/webdataset-lightning/blob/main/train.py I needed to add the `ddp_equalize` function for making sure batches are even across ranks.

What I'm noticing now is that checkpoints are not always being saved. I'm not using a custom `ModelCheckpoint` callback so based on the default behavior I usually see a checkpoint saved after each epoch. However under DDP if I train a model for 10 epochs I would see a checkpoint being saved for the first 3 epochs but not the next 7.

Do you have an idea why that might happen?

**Comment by tchaton** [comment]
Dear @asonf7,

Dope ! Happy you find your issue.

Could it be your model isn't doing performing better and you configured your `ModelCheckpoint` to save only the best ?

Best,
T.C

**Comment by jasonf7** [comment]
I haven't configured `ModelCheckpoint` at all so the default behavior should to be always saving a checkpoint after each epoch, right?
