### ISSUE TITLE
Totally lacking of a proper way to log 2D metrics 

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [PyTorchLightning/pytorch-lightning#9869]
Hi guys,

I hope you are doing great!

## 🐛 Bug
Assume I want to log a 2D metric, e.g. ConfusionMatrix, in my `Module` I have a function that takes all the metrics al log them, e.g.

```python
   ....
   def namespaced(self, name: str, metrics: Dict[str, Any]):
        return {f"{name}_{k}": v for k, v in metrics.items()}

    def default_on_epoch_end(self, namespace: str, metrics: Metric, avg_loss: Metric):
        computed = metrics.compute()
        computed = {"loss": avg_loss.compute(), **computed}
        computed = self.namespaced(f"{namespace}_avg", computed)
        self.log_dict(computed)
        # self.logger.log_metrics(computed)
        metrics.reset()
        avg_loss.reset()
        
    def on_train_epoch_end(self) -> None:
        self.default_on_epoch_end("train", self.train_metrics, self.train_avg_loss)
```
Where `metrics` is passed (from torchmetrics)

```python
metrics = M.MetricCollection(
                {
                    "accuracy": M.Accuracy(num_classes=dm.num_classes),
                    "recall": M.Recall(num_classes=dm.num_classes),
                    "f1": M.F1(num_classes=dm.num_classes),
                    "precision": M.Precision(num_classes=dm.num_classes),
                    "confusion_matrix": M.ConfusionMatrix(num_classes=dm.num_classes),
                }
            )
```
First of all, it is totally unclear how a 2D metric such as `ConfusionMatrix` is reduced by the logger. If I try to run a normal image classifier, randomly at a certain point I'll have 

```
pytorch_lightning.utilities.exceptions.MisconfigurationException: The metric `tensor([[ 0.,  2.,  0.],
        [ 0., 16.,  0.],
        [ 0.,  0.,  0.]], device='cuda:0')` does not contain a single element, thus it cannot be converted to a scalar.
 ```

Full-stack trace:
```
Traceback (most recent call last):
  File "entry.py", line 270, in train_function
    trainer.fit(classifier, datamodule=dm)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 163, in advance
    self.trainer.logger_connector.update_train_step_metrics()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 221, in update_train_step_metrics
    self.log_metrics(self.metrics[MetricSource.LOG])
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 96, in log_metrics
    scalar_metrics = metrics_to_scalars(metrics)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/metrics.py", line 40, in metrics_to_scalars
    return apply_to_collection(metrics, torch.Tensor, to_item)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 104, in apply_to_collection
    v = apply_to_collection(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 96, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/metrics.py", line 35, in to_item
    raise MisconfigurationException(
```

Weirdly enough, this is random, doesn't happen in all epochs. Now, how *the hell do I log a 2D metric*?

Thank you

**Comment by rohitgr7** [comment]
> [EDIT] that was due to a second call in the train loop where I was passing all the metrics to self.log, the above solution works

hey @FrancescoSaverioZuppichini looks like it worked for you. closing this issue. feel free to reopen if required :)
