### ISSUE TITLE
LightningCLI: Linking arguments from model to checkpoint 

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#9887]
### To Reproduce

```bash
python test.py fit --model.generator chco --optimizer=Adam --optimizer.lr=0.001
```

```py
import torch
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.utilities.cli import LightningCLI
from pytorch_lightning import LightningModule
from torch.utils.data import DataLoader


class Model(LightningModule):
    def __init__(self, generator: str):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        self.generator = generator

    def training_step(self, batch):
        loss  = self.layer(batch).abs().sum()
        self.log("train_loss", loss)
        return loss

    def train_dataloader(self):
        return DataLoader(torch.randn(64, 32))

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

class MyLightningCLI(LightningCLI):
    def add_arguments_to_parser(self, parser):
        parser.add_lightning_class_args(ModelCheckpoint, "checkpoint")
        parser.set_defaults({
            "checkpoint.monitor": "train_loss",
            "checkpoint.filename": "{model.base_encoder}-{epoch}-{train_loss:.2f}-{train_loss:.2f}",
            "checkpoint.mode": "min",
        })


MyLightningCLI(Model)
```

As expected the model isn't available within the callback_metrics for the filename resolution.

```py
  rank_zero_warn(
Epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 391.95it/s, loss=0.798, v_num=16]Traceback (most recent call last):
  File "test.py", line 37, in <module>
    MyLightningCLI(Model)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/utilities/cli.py", line 490, in __init__
    self._run_subcommand(self.subcommand)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/utilities/cli.py", line 741, in _run_subcommand
    fn(**fn_kwargs)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 599, in fit
    self._call_and_handle_interrupt(self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 551, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 629, in _fit_impl
    self._run(model)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1058, in _run
    self._dispatch()
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1137, in _dispatch
    self.accelerator.start_training(self)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/accelerators/accelerator.py", line 85, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 183, in start_training
    self._results = trainer.run_stage()
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1147, in run_stage
    return self._run_train()
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1183, in _run_train
    self.fit_loop.run()
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/loops/base.py", line 114, in run
    self.advance(*args, **kwargs)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/loops/fit_loop.py", line 211, in advance
    self.epoch_loop.run(data_fetcher)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/loops/base.py", line 120, in run
    output = self.on_run_end()
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 255, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1342, in call_hook
    callback_fx(*args, **kwargs)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/trainer/callback_hook.py", line 92, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 319, in on_train_epoch_end
    self.save_checkpoint(trainer)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 386, in save_checkpoint
    self._save_top_k_checkpoint(trainer, monitor_candidates)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 677, in _save_top_k_checkpoint
    self._update_best_and_save(current, trainer, monitor_candidates)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 712, in _update_best_and_save
    filepath = self._get_metric_interpolated_filepath_name(monitor_candidates, trainer, del_filepath)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 642, in _get_metric_interpolated_filepath_name
    filepath = self.format_checkpoint_name(monitor_candidates)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 571, in format_checkpoint_name
    filename = self._format_checkpoint_name(
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 537, in _format_checkpoint_name
    filename = filename.format(**metrics)
KeyError: 'model'
Epoch 0: 100%|██████████| 64/64 [00:00<00:00, 244.03it/s, loss=0.798, v_num=16]  
```

Original conversation from Slack: https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1633943650292200

The user `Tran N.M. Hoang` wants to link the generator argument to the model filename. 

### Environment

- PyTorch Lightning Version (e.g., 1.3.0):
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

**Comment by tchaton** [comment]
Hey @carmocca. Yes, updating jsonargparse solved the previous problem.

**Comment by hoangtnm** [comment]
> The error seems expected, as you are passing a monitor key which does not get logged (model)

But `model` or `data` is accessible from `parser.link_arguments`

```python
class MyLightningCLI(LightningCLI):
    def add_arguments_to_parser(self, parser):
        parser.link_arguments("model.data_dir", "data.data_dir")
        parser.link_arguments("model.batch_size", "data.batch_size")
        parser.link_arguments("model.num_workers", "data.num_workers")
```

**Comment by hoangtnm** [comment]
@carmocca Do you think this case should be documented on lightning docs? I think saving some special hyper-parameters into checkpoint filename directly will save lots of time when just needs to read the filename and know which model was used, for example?

**Comment by hoangtnm** [comment]
As described in [slack](https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1633943650292200), I'm trying to train [Moco (v2)](https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html#moco-v2-api) from `lightning-bolts` with LightningCLI, which uses different `base_encoder` ones to find the optimal `base_encoder`. So, without saving `model.base_encoder` into the checkpoint filename, it becomes harder to track through saved checkpoints. For example, this expriment can uses `resnet50` and 50 other expriments use `densenet121` or `mobilenet_v2`... Therefore, if `base_encoder` attribute is saved into the checkpoint filename, it will become easier to keep track of expriments.
I think this case can documented in [Argument linking](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_cli.html#argument-linking) as a sub-section.

**Comment by csvance** [comment]
Ideally argument linking should support this use case, but there doesn't seem to be a way to address specific callbacks. Ie this doesn't work:

```python
        parser.link_arguments(("experiment_name", "trainer.callbacks.ModelCheckpoint.filename"), 
                              "trainer.callbacks.ModelCheckpoint.filename", 
                              compute_fn=lambda x, y: "-".join([x, y]))
```

Results in:

```
ValueError: Target key "trainer.callbacks.ModelCheckpoint.filename" must be for an individual argument.
```

This snippet should at least work around the problem, but its clunky in that it requires passing parameters to the model just to have the model substitute them in to the ModelCheckpoint:

```python
    def on_fit_start(self):
        ...
        for callback in self.trainer.callbacks:
            if isinstance(callback, ModelCheckpoint):
                callback.filename = callback.filename.replace('{experiment_name}', self._experiment_name)
```

**Comment by tchaton** [comment]
@mauvilsa for reference.

**Comment by mauvilsa** [comment]
@csvance indeed with `link_arguments` currently it is not possible to have as target some key nested in a list. Furthermore, the target key cannot be the same as one of the sources as you have it. Anyway, if I understand correctly, what you want can be done by making the callback [configurable](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_cli.html#configurable-callbacks) as follows:

```python
class MyLightningCLI(LightningCLI):
    def add_arguments_to_parser(self, parser):
        parser.add_argument("--experiment_name", default=SOME_NAME_DEFAULT)
        parser.add_argument("--checkpoint_filename", default=SOME_FILENAME_DEFAULT)
        parser.add_lightning_class_args(ModelCheckpoint, "checkpoint_callback")
        parser.link_arguments(
            ("experiment_name", "checkpoint_filename"), 
            "checkpoint_callback.filename", 
            compute_fn=lambda x, y: "-".join([x, y])
        )
```

I haven't tested the code, so there could be mistakes. It is just to give the idea.

**Comment by csvance** [comment]
> I haven't tested the code, so there could be mistakes. It is just to give the idea.

Thank you, this works for me! A very common use case is defining your experiment name once, then including it in the checkpoint path and in your LightningLogger of choice (Comet, Wandb, Tensorboard, etc). For the logger part, if I try to link the arguments I get `ValueError: Target key "trainer.logger.init_args.experiment_name" must be for an individual argument.`. It looks like the callback registration in `add_lightning_class_args` is a special case and wouldn't also work for the logger.

```python
    def add_arguments_to_parser(self, parser):
        parser.add_argument("--experiment_name", default="I_FORGOT_TO_NAME_MY_EXPERIMENT")
        parser.link_arguments("experiment_name", "trainer.logger.init_args.experiment_name")
```

```yaml
trainer:
  max_epochs: 6
  precision: 16
  gpus: 2
  accumulate_grad_batches: 1
  deterministic: true
  benchmark: true
  val_check_interval: 0.25
  logger:
    class_path: pytorch_lightning.loggers.comet.CometLogger
    init_args:
      project_name: lightning-cli-template
```

Anyways, I am going to play around with this a bit more but maybe if I could put together a full working example I could contribute it to the docs. To me this seems like a baseline use case that would be very useful to the vast majority of people trying to get started with LightningCLI.
