### ISSUE TITLE
Error in computer_vision_fine_tuning.py example

### ISSUE THREAD

**Issue by shamanez** [PyTorchLightning/pytorch-lightning#9922]
## 🐛 Bug

Give the following error 

"AttributeError: 'MyLightningCLI' object has no attribute '_get'"

### To Reproduce

**python  ./pl_examples/domain_templates/computer_vision_fine_tuning.py** 

### Environment

- PyTorch Lightning Version:  1.4.9
- Python version: 3.9
- OS: Ubuntu

**Comment by mauvilsa** [comment]
I get a different error if I run `python ./pl_examples/domain_templates/computer_vision_fine_tuning.py` with lightning 1.4.9, python 3.8 and jsonargparse 3.19.4.

```
Traceback (most recent call last):
  File "./pl_examples/domain_templates/computer_vision_fine_tuning.py", line 292, in <module>
    cli_main()
  File "./pl_examples/domain_templates/computer_vision_fine_tuning.py", line 287, in cli_main
    MyLightningCLI(TransferLearningModel, CatDogImageDataModule, seed_everything_default=1234)
  File "/home/mvillegas/repos/thirdparty/pytorch-lightning/pytorch_lightning/utilities/cli.py", line 285, in __init__
    self.instantiate_classes()
  File "/home/mvillegas/repos/thirdparty/pytorch-lightning/pytorch_lightning/utilities/cli.py", line 341, in instantiate_classes
    self.instantiate_trainer()
  File "./pl_examples/domain_templates/computer_vision_fine_tuning.py", line 281, in instantiate_trainer
    finetuning_callback = MilestonesFinetuning(**self.config_init["finetuning"])
TypeError: ABCMeta object argument after ** must be a mapping, not MilestonesFinetuning
```

@shamanez if you update jsonargparse to this version do you still have the `_get` error?

That example needs to be updated. Now the classes added with `parser.add_class_arguments` are automatically instantiated. Thus this instantiation is no longer necessary [computer_vision_fine_tuning.py#L281](https://github.com/PyTorchLightning/pytorch-lightning/blob/28fc8d201675229a8ad768131749c6c8f873714e/pl_examples/domain_templates/computer_vision_fine_tuning.py#L281).

I can fix that example.

**Comment by mauvilsa** [comment]
Created a pull request https://github.com/PyTorchLightning/pytorch-lightning/pull/9934 and tested it locally in python 3.8 and 3.9.

**Comment by shamanez** [comment]
Thanks for your response.
