### ISSUE TITLE
setup() not working with DeepSpeed

### ISSUE THREAD

**Issue by BramVanroy** [PyTorchLightning/pytorch-lightning#9974]
Attributes that are set during `setup` are not available when using DeepSpeed - even when using a single GPU.

Assume the following script is `deepspeed_test.py`:

```python
import argparse
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        self.dataloaders = None

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

    def setup(self, stage=None):
        self.dataloaders = {
            "train": DataLoader(RandomDataset(32, 64), batch_size=2),
            "val": DataLoader(RandomDataset(32, 64), batch_size=2)
        }

    def train_dataloader(self):
        return self.dataloaders["train"] if "train" in self.dataloaders else None

    def val_dataloader(self):
        return self.dataloaders["val"] if "val" in self.dataloaders else None

def run(args):
    model = BoringModel()
    trainer = Trainer.from_argparse_args(args,
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
    )
    trainer.fit(model)


if __name__ == "__main__":
    cparser = argparse.ArgumentParser()
    cparser = Trainer.add_argparse_args(cparser)
    cargs = cparser.parse_args()
    run(cargs)
```

Running `python test_deepspeed.py` works perfectly fine. However, `python deepspeed_test.py --plugins deepspeed_stage_3` does not. It leads to the following error log:

```
Traceback (most recent call last):
  File "/hone/bram/pl/deepspeed_test.py", line 75, in <module>
    run(cargs)
  File "/hone/bram/pl/deepspeed_test.py", line 68, in run
    trainer.fit(model)
  File "/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 863, in _run
    self.accelerator.setup_environment()
  File "/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 76, in setup_environment
    self.training_type_plugin.setup_environment()
  File "/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 168, in setup_environment
    self.setup_distributed()
  File "/python3.9/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 349, in setup_distributed
    self._format_config()
  File "/python3.9/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 553, in _format_config
    self._format_batch_size_and_grad_accum_config()
  File "/python3.9/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 563, in _format_batch_size_and_grad_accum_config
    batch_size = self._auto_select_batch_size()
  File "/python3.9/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 574, in _auto_select_batch_size
    train_dataloader = self.lightning_module.train_dataloader()
  File "/hone/bram/pl/deepspeed_test.py", line 54, in train_dataloader
    return self.dataloaders["train"] if "train" in self.dataloaders else None
TypeError: argument of type 'NoneType' is not iterable
```

This tells me that the `setup()` call that is supposed to execute on every GPU is not run when using DeepSpeed.

cc @SeanNaren @awaelchli

**Comment by BramVanroy** [comment]
Yes, this is a dummy example. In reality:

- prepare data: tokenizers dataset and saves as HF Dataset on disk
- setup: loads dataset from disk
- data loaders: create data loader from loaded datasets

So in my real code I get the issue that the loaded dataset is None and that the data loader does not work because dataset is still none. 

What is the recommended way to do this? It is important that my code works well both with and without deepspeed.

**Comment by SeanNaren** [comment]
@BramVanroy this should be fixed on master and the latest bugfix (`pip install pytorch-lightning -U`)! 

you shouldn't need to specify the plugin anymore (the string should be fine)
